lightbend/kalix-jvm-sdk

samples/java-valueentity-shopping-cart/src/main/proto/shoppingcart/shoppingcart_api.proto, samples/java-valueentity-shopping-cart/src/main/proto/shoppingcart/shoppingcart_domain.proto, samples/valueentity-counter/src/main/proto/value-entities/counter_api.proto, samples/valueentity-counter/src/main/proto/value-entities/counter_domain.proto
Formats Shopping Cart VE and Counter VE protos with indent 2. 
This seems to be tricky when using intellij and antora callouts `// <1>`, as the formatter will align with the callout, like in:
```proto
message IncreaseValue { // <4>
string counter_id = 1 [(akkaserverless.field).entity_key = true];
int32 value = 2;
}
```
The best would be to have a formatter that does what we want at build time, so we don't run the risk of inadvertently format the protos, miss the bad formatting and messing up with the docs.
=> fix: formatting protos

project/Dependencies.scala, project/plugins.sbt
I haven't bumped the akka-grpc version in the samples. They fail to build with the java-sdk on beta.10 and akka-grpc plugin on 2.0.0. While it seems fine with newer java-sdk (built against akka-grpc 2.0.0) and the older akka-grpc plugin — and this should be tested in CI as well.
So probably best to wait with bumping the samples until next java-sdk release, and bump both versions together. And also do this in the maven archetypes.
=> bump: update akka-grpc to 2.0.0

docs/Makefile
Rename from `java-services` to `java`. Keep a copy at the old location during the transition. Already published to the [`docs/current` branch](https://github.com/lightbend/akkaserverless-java-sdk/tree/docs/current/docs/build/src/managed/modules).
=> chore: rename docs module from java-services to java

sdk/src/main/scala/com/akkaserverless/javasdk/impl/action/ActionsImpl.scala
Otherwise, all the `ActionReflection` code (looking up methods and annotations, etc) will be re-executed for every single call.
=> cache actionHandlers on creation

maven-java/maven-archetype-akkasls-event-sourced-entity/src/main/resources/archetype-resources/README.md, maven-java/maven-archetype-akkasls-value-entity/src/main/resources/archetype-resources/README.md
Based on the maven-java feature branch.
=> doc: fix http transcoding links in archetype readmes

samples/java-eventsourced-shopping-cart/README.md, samples/java-valueentity-shopping-cart/README.md, samples/valueentity-counter/README.md, sdk/src/main/scala/com/akkaserverless/javasdk/impl/DocLinks.scala
Adapt to https://github.com/lightbend/akkaserverless-docs/issues/604﻿
Draft until production docs are updated.
=> chore: align with updated doc URLs

.circleci/config.yml, .circleci/key-gen-options.txt, maven-java/akkaserverless-maven-archetype-event-sourced-entity/pom.xml, maven-java/akkaserverless-maven-archetype-value-entity/pom.xml, maven-java/akkaserverless-maven-plugin/pom.xml, maven-java/pom.xml
=> build publish maven plugin from CI to sonatype

sdk/src/main/java/com/akkaserverless/javasdk/AkkaServerless.java, sdk/src/main/scala/com/akkaserverless/javasdk/impl/view/ViewsImpl.scala
This scenario got me confused for a bit, so adding some language
to make this easier to follow.
=> chore: `transform_updates=false` code paths better

docs/Makefile
Now that https://github.com/lightbend/akkaserverless-docs/pull/746 is merged, we should be able to switch back to `docs/current` branch again, and then also update in akkaserverless-docs.
=> doc: switch back to publishing to docs/current branch

maven-java/akkaserverless-maven-archetype-event-sourced-entity/pom.xml, maven-java/akkaserverless-maven-archetype-event-sourced-entity/src/main/resources/META-INF/maven/archetype-metadata.xml, maven-java/akkaserverless-maven-archetype-value-entity/pom.xml, maven-java/akkaserverless-maven-archetype-value-entity/src/main/resources/META-INF/maven/archetype-metadata.xml
This is two-step problem.
Following the SO link @ennru [provided](https://github.com/lightbend/akkaserverless-java-sdk/issues/80#issuecomment-850314413), I managed to have `.gitignore` in  `target/classes/archetype-resources`. But,  the `.gitignore` is not listed in `target/META-INF/maven/archetype-metadata.xml` and it doesn't end up in the jar file.
So, we must:
=> Include .gitignore #80

sdk/src/main/java/com/akkaserverless/javasdk/lowlevel/ValueEntityHandler.java, sdk/src/main/java/com/akkaserverless/javasdk/valueentity/CommandContext.java, sdk/src/main/scala/com/akkaserverless/javasdk/impl/ReflectionHelper.scala, sdk/src/main/scala/com/akkaserverless/javasdk/impl/valueentity/AnnotationBasedEntitySupport.scala, sdk/src/main/scala/com/akkaserverless/javasdk/impl/valueentity/ValueEntitiesImpl.scala, sdk/src/main/scala/com/akkaserverless/javasdk/impl/valueentity/ValueEntityEffectImpl.scala, sdk/src/test/scala/com/akkaserverless/javasdk/impl/valueentity/AnnotationBasedValueEntitySupportSpec.scala, sdk/src/test/scala/com/akkaserverless/javasdk/impl/valueentity/ValueEntitiesImplSpec.scala, tck/src/main/java/com/akkaserverless/javasdk/tck/model/localpersistenceeventing/ValueEntityOne.java, tck/src/main/java/com/akkaserverless/javasdk/tck/model/localpersistenceeventing/ValueEntityTwo.java, tck/src/main/java/com/akkaserverless/javasdk/tck/model/valueentity/ValueEntityConfiguredEntity.java, tck/src/main/java/com/akkaserverless/javasdk/tck/model/valueentity/ValueEntityTckModelEntity.java, tck/src/main/java/com/akkaserverless/javasdk/tck/model/valueentity/ValueEntityTwoEntity.java, tck/src/test/resources/logback-test.xml
Since we now have the effect system. This now also requires
returning an effect rather than a value even for the
annotation-based implementation.
Haven't updated the sample projects yet.
=> sdk codegen: remove 'setState' from value entity context, always use effects

codegen/java-gen/src/main/scala/com/lightbend/akkasls/codegen/java/ActionServiceSourceGenerator.scala, codegen/java-gen/src/main/scala/com/lightbend/akkasls/codegen/java/EntityServiceSourceGenerator.scala, codegen/java-gen/src/main/scala/com/lightbend/akkasls/codegen/java/ViewServiceSourceGenerator.scala, codegen/java-gen/src/test/scala/com/lightbend/akkasls/codegen/java/ActionServiceSourceGeneratorSuite.scala, codegen/java-gen/src/test/scala/com/lightbend/akkasls/codegen/java/EntityServiceSourceGeneratorSuite.scala, codegen/java-gen/src/test/scala/com/lightbend/akkasls/codegen/java/SourceGeneratorSuite.scala, codegen/java-gen/src/test/scala/com/lightbend/akkasls/codegen/java/ViewServiceSourceGeneratorSuite.scala, maven-java/akkaserverless-maven-plugin/src/test/java/com/akkaserverless/GenerateMojoTest.java
tested on
- codegen
- maven-java
- single application calling to codegen through maven-java-plugin (maybe unnecessary : )
=> changing Interface class name to Abstract

project/Common.scala
The `scalafmtOnCompile` setting in the `CommonSettings` auto-plugin isn't always enabled, as the `ScalafmtPlugin` also defines its default for this in global settings, and either plugin could have its settings applied last. Add a dependency on the scalafmt plugin to make sure we override the setting to enabled.
=> build: fix scalafmtOnCompile setting

.circleci/config.yml, samples/java-eventsourced-shopping-cart/pom.xml, samples/java-eventsourced-shopping-cart/src/main/java/com/example/shoppingcart/domain/ShoppingCartImpl.java
* disable sample compilation/integration tests on ci until we want to enable it again
* incorrectly changed base class in event sourced shopping cart
* wrong name for plugin version property in event sourced shopping cart pom
Should make CI green again
=> Unbreak samples ci testing in codegen-dev

project/Dependencies.scala, tck/src/main/java/com/akkaserverless/javasdk/tck/JavaSdkTck.java, tck/src/main/java/com/akkaserverless/javasdk/tck/model/view/ViewTckSourceEntity.java
The proxy will have eventing source validation, so the view in the TCK needs an existing entity as its source now.
See https://github.com/lightbend/akkaserverless-framework/pull/774 and https://github.com/lightbend/akkaserverless-framework/pull/773
=> tck: add view source entity

sdk/src/main/scala/com/akkaserverless/javasdk/impl/DocLinks.scala
Add doc links for the new error codes for eventing validation for entity types (https://github.com/lightbend/akkaserverless-framework/pull/773). Note that the docs currently only cover subscribing to event sourced entities (doc issue #121).
=> Add doc links for entity eventing error codes

.circleci/config.yml
0.7.0-beta.12 release failed because when publishing the maven plugin, we need the codegen artifact. Although we have published the codegen, this is not yet visible in maven central. 
Therefore, we need to publish locally
=> publishM2 before publishing maven artifacts

docs/src/modules/developing/pages/development-process-java.adoc, docs/src/modules/java/examples/archetype/first-service/README.md, docs/src/modules/java/partials/running-service-locally.adoc
All minor all relevant - even a couple of actual "docker" fixes.
=> Docker fixes

.circleci/config.yml, maven-java/pom.xml
For unknown reason, we were building the maven projects using jdk8. It turns out that since we first need to publish the codegen locally and the [sbt is configured](https://github.com/lightbend/akkaserverless-java-sdk/blob/main/build.sbt#L48-L49) with `--release` flag, we get the following error:
```java
-release is only supported on Java 9 and higher
```
(https://app.circleci.com/pipelines/github/lightbend/akkaserverless-java-sdk/503/workflows/fcbd35cb-21e1-44a9-a9fe-a36ef028d7f2/jobs/3088)
For the record, when I say for unknown reason I mean, I don't know why the old maven-java project was using jdk8. What we have now here is a copy-n-paste from that previous project. Anyway, my understanding is that we only build with jdk11 (not only on this project, but every akka serverless project) …
=> fix: build maven project using jdk11

.circleci/config.yml, samples/java-customer-registry/pom.xml, samples/java-eventing-shopping-cart/pom.xml, samples/java-eventsourced-shopping-cart/pom.xml, samples/java-valueentity-shopping-cart/pom.xml, samples/replicatedentity-counter/pom.xml, samples/valueentity-counter/pom.xml, updatePomVersions.sh
Those changes will allows us to:
* change the sdk version in all mvn projects in one shot (changes can be pushed or not)
* samples use its own project.version as sdk version
* remove passing -D in CI, it suffice to use `mvn versions:set`
=> feat: samples uses project.version as sdk version

updatePomVersions.sh
There is a small mistake on the updatePomVersions.sh script. We should not permanently move in `maven-java` directory.
=> fix: preserve execution dir

.circleci/config.yml, maven-java/akkaserverless-maven-archetype-event-sourced-entity/pom.xml, maven-java/akkaserverless-maven-archetype-value-entity/pom.xml, maven-java/akkaserverless-maven-plugin/pom.xml, maven-java/pom.xml, samples/java-customer-registry/pom.xml, samples/java-eventing-shopping-cart/pom.xml, samples/java-eventsourced-shopping-cart/pom.xml, samples/java-valueentity-shopping-cart/pom.xml, samples/replicatedentity-counter/pom.xml, samples/valueentity-counter/pom.xml, updatePomVersions.sh
* set the versions in all pom.xml to be 0.7.0-beta.15 (latest release)
* `updatePomVerions.sh` use `sed` to update `akkaserverless-sdk.version` property
=> fix: update sample sdk version with sed

codegen/core/src/main/scala/com/lightbend/akkasls/codegen/Log.scala, codegen/core/src/main/scala/com/lightbend/akkasls/codegen/ModelBuilder.scala, codegen/core/src/test/scala/com/lightbend/akkasls/codegen/ModelBuilderSuite.scala, codegen/java-gen/src/main/scala/com/lightbend/akkasls/codegen/java/SourceGenerator.scala, codegen/java-gen/src/test/scala/com/lightbend/akkasls/codegen/java/SourceGeneratorSuite.scala, maven-java/akkaserverless-maven-plugin/src/main/java/com/akkaserverless/GenerateMojo.java, project/Dependencies.scala, publishLocalM2.sh
Notably for the case where there is an entity service,
but no entity component configuration that matches by
the component name - in which case nothing would be
generated, silently.
=> feat: add some logging to codegen

maven-java/pom.xml
It is required since the other projects have this pom as their parent
pom. Refs #173
=> Don't skip deploying the maven-java pom

docs/src/modules/java/pages/views.adoc, samples/java-eventing-shopping-cart/src/main/java/shopping/product/ToProductPopularityAction.java
@pvlugter @ennru adding this PR as a draft. I found this example of ignoring events but it is in the context of an action that handles events. The implementation probably would be different for a View? And, it would probably be better in the context of the example we are using for the Event Sourced entity View. Could one of you please help me with this?
=> doc: describe ignoring events for views

.circleci/config.yml, RELEASING.md, codegen/core/src/main/scala/com/lightbend/akkasls/codegen/DescriptorSet.scala, codegen/core/src/test/scala/com/lightbend/akkasls/codegen/DescriptorSetSuite.scala, maven-java/akkaserverless-maven-plugin/src/main/java/com/akkaserverless/GenerateMojo.java, samples/java-customer-registry/pom.xml, samples/java-eventing-shopping-cart/pom.xml, samples/java-eventsourced-shopping-cart/pom.xml, samples/java-valueentity-shopping-cart/pom.xml, samples/replicatedentity-counter/pom.xml, samples/valueentity-counter/pom.xml
The Eventing Shopping Cart sample doesn't work with the current codegen AFAICS.﻿
=> fix: accumulate protobuf descriptors 

.circleci/config.yml, build.sbt, codegen/java-gen/src/main/scala/com/lightbend/akkasls/codegen/java/EntityServiceSourceGenerator.scala, codegen/java-gen/src/main/scala/com/lightbend/akkasls/codegen/java/ViewServiceSourceGenerator.scala, codegen/java-gen/src/test/scala/com/lightbend/akkasls/codegen/java/EntityServiceSourceGeneratorSuite.scala, codegen/java-gen/src/test/scala/com/lightbend/akkasls/codegen/java/ViewServiceSourceGeneratorSuite.scala, docs/src/modules/java/pages/views.adoc, samples/java-customer-registry/README.md, samples/java-customer-registry/pom.xml, samples/java-customer-registry/src/main/java/customer/Main.java, samples/java-customer-registry/src/main/java/customer/domain/CustomerValueEntity.java, samples/java-customer-registry/src/main/java/customer/view/CustomerByNameView.java, samples/java-customer-registry/src/main/proto/customer/customer_api.proto, samples/java-customer-registry/src/main/proto/customer/customer_domain.proto, samples/java-customer-registry/src/main/proto/customer/customer_view.proto
The current "Customer Registry" contains both a Value Entity and an Event-sourced Entity both are required for doc-snippets.
This PR enables codegen for the Value Entity and for the View and reflects that (a bit) in the documentation.
Similar to #198 
Discovered #199 during this.
=> feature: rely on some codegen in the Customer Registry sample

docs/src/modules/java/examples/archetype/first-service/docker-compose.yml, maven-java/akkaserverless-maven-archetype-event-sourced-entity/src/main/resources/archetype-resources/docker-compose.yml, maven-java/akkaserverless-maven-archetype-value-entity/src/main/resources/archetype-resources/docker-compose.yml, project/Dependencies.scala, samples/java-eventsourced-shopping-cart/docker-compose.yml, samples/java-valueentity-shopping-cart/docker-compose.yml, samples/replicatedentity-counter/docker-compose.yml, samples/valueentity-counter/docker-compose.yml, sdk/src/main/java/com/akkaserverless/javasdk/replicatedentity/ReplicatedCounterMap.java, sdk/src/main/java/com/akkaserverless/javasdk/replicatedentity/ReplicatedDataFactory.java, sdk/src/main/java/com/akkaserverless/javasdk/replicatedentity/ReplicatedMap.java, sdk/src/main/java/com/akkaserverless/javasdk/replicatedentity/ReplicatedMultiMap.java, sdk/src/main/java/com/akkaserverless/javasdk/replicatedentity/ReplicatedRegisterMap.java, sdk/src/main/scala/com/akkaserverless/javasdk/impl/replicatedentity/AbstractReplicatedEntityFactory.scala, sdk/src/main/scala/com/akkaserverless/javasdk/impl/replicatedentity/ReplicatedCounterMapImpl.scala, sdk/src/main/scala/com/akkaserverless/javasdk/impl/replicatedentity/ReplicatedEntityDeltaTransformer.scala, sdk/src/main/scala/com/akkaserverless/javasdk/impl/replicatedentity/ReplicatedEntityImpl.scala, sdk/src/main/scala/com/akkaserverless/javasdk/impl/replicatedentity/ReplicatedMapImpl.scala, sdk/src/main/scala/com/akkaserverless/javasdk/impl/replicatedentity/ReplicatedMultiMapImpl.scala, sdk/src/main/scala/com/akkaserverless/javasdk/impl/replicatedentity/ReplicatedRegisterMapImpl.scala, sdk/src/main/scala/com/akkaserverless/javasdk/impl/replicatedentity/ReplicatedSetImpl.scala, sdk/src/test/scala/com/akkaserverless/javasdk/impl/replicatedentity/AnnotationBasedReplicatedEntitySupportSpec.scala, tck/src/main/java/com/akkaserverless/javasdk/tck/model/replicatedentity/TckModelReplicatedEntity.java, tck/src/test/java/com/akkaserverless/javasdk/tck/RunTck.java
Refs #48. Test the specialised replicated maps using the new TCK tests from https://github.com/lightbend/akkaserverless-framework/pull/802 (needs to be published first, draft PR here). Support the new replicated maps from https://github.com/lightbend/akkaserverless-framework/pull/803. Resolves #49.
=> feat: add specialised replicated maps

.circleci/config.yml, docs/src/modules/java/examples/archetype/first-service/README.md, maven-java/akkaserverless-maven-archetype-event-sourced-entity/src/main/resources/archetype-resources/README.md, maven-java/akkaserverless-maven-archetype-value-entity/src/main/resources/archetype-resources/README.md, samples/customer-registry-quickstart/README.md, samples/customer-registry-quickstart/docker-compose.linux.yml, samples/customer-registry-quickstart/docker-compose.yml, samples/customer-registry-quickstart/pom.xml, samples/customer-registry-quickstart/src/it/java/customer/CustomerByNameViewIntegrationTest.java, samples/customer-registry-quickstart/src/it/java/customer/CustomerIntegrationTest.java, samples/customer-registry-quickstart/src/it/resources/logback-test.xml, samples/customer-registry-quickstart/src/main/java/customer/Main.java, samples/customer-registry-quickstart/src/main/java/customer/domain/Customer.java, samples/customer-registry-quickstart/src/main/java/customer/view/CustomerByName.java, samples/customer-registry-quickstart/src/main/java/customer/view/CustomerByNameView.java, samples/customer-registry-quickstart/src/main/proto/customer/customer_api.proto, samples/customer-registry-quickstart/src/main/proto/customer/customer_domain.proto, samples/customer-registry-quickstart/src/main/proto/customer/customer_view.proto, samples/customer-registry-quickstart/src/main/resources/application.conf, samples/customer-registry-quickstart/src/main/resources/logback.xml, samples/java-eventing-shopping-cart/pom.xml, samples/java-eventsourced-shopping-cart/README.md, samples/java-valueentity-shopping-cart/README.md
This adds a copy of relevant parts of the `java-customer-registry` sample as a base for the quickstart sources.
Discovered #202 
Refs https://github.com/lightbend/akkaserverless-framework/issues/738
=> feature: Customer Registry quickstart bootstrap

samples/java-eventsourced-shopping-cart/src/main/java/com/example/shoppingcart/domain/ShoppingCart.java
This is a proposed fix to the typo in the error message.
=> chore: Typo in sample's error message

codegen/java-gen/src/main/scala/com/lightbend/akkasls/codegen/java/SourceGenerator.scala, codegen/java-gen/src/main/scala/com/lightbend/akkasls/codegen/java/ValueEntitySourceGenerator.scala, codegen/java-gen/src/test/scala/com/lightbend/akkasls/codegen/java/SourceGeneratorSuite.scala, codegen/java-gen/src/test/scala/com/lightbend/akkasls/codegen/java/ValueEntitySourceGeneratorSuite.scala, samples/java-customer-registry/src/main/java/customer/Main.java, sdk/src/main/java/com/akkaserverless/javasdk/AkkaServerless.java, sdk/src/main/java/com/akkaserverless/javasdk/valueentity/ValueEntityProvider.java
* include options in ValueEntityProvider instead of having overloaded register
methods
* this will make it easier for us to add more optional parameters when needed
Follow up on https://github.com/lightbend/akkaserverless-java-sdk/pull/190/files#r687726999
=> Make generated ValueEntityProvider a builder

codegen/java-gen/src/main/scala/com/lightbend/akkasls/codegen/java/EntityServiceSourceGenerator.scala, codegen/java-gen/src/main/scala/com/lightbend/akkasls/codegen/java/ValueEntitySourceGenerator.scala, codegen/java-gen/src/test/scala/com/lightbend/akkasls/codegen/java/EventSourcedEntitySourceGeneratorSuite.scala, codegen/java-gen/src/test/scala/com/lightbend/akkasls/codegen/java/ValueEntitySourceGeneratorSuite.scala, maven-java/akkaserverless-maven-archetype-event-sourced-entity/pom.xml, maven-java/akkaserverless-maven-archetype-value-entity/pom.xml, maven-java/akkaserverless-maven-plugin/pom.xml, maven-java/pom.xml, sdk/src/main/scala/com/akkaserverless/javasdk/impl/eventsourcedentity/EventSourcedEntitiesImpl.scala, sdk/src/main/scala/com/akkaserverless/javasdk/impl/eventsourcedentity/EventSourcedEntityHandler.scala, sdk/src/test/java/com/akkaserverless/javasdk/eventsourcedentity/CartEntityHandler.java, sdk/src/test/java/com/akkaserverless/javasdk/eventsourcedentity/CartEntityProvider.java, sdk/src/test/scala/com/akkaserverless/javasdk/impl/eventsourcedentity/EventSourcedEntitiesImplSpec.scala, sdk/src/test/scala/com/akkaserverless/javasdk/impl/eventsourcedentity/TestEventSourced.scala, tck/src/main/java/com/akkaserverless/javasdk/tck/model/eventsourcedentity/EventSourcedConfiguredEntityHandler.java, tck/src/main/java/com/akkaserverless/javasdk/tck/model/eventsourcedentity/EventSourcedTckModelEntityHandler.java, tck/src/main/java/com/akkaserverless/javasdk/tck/model/eventsourcedentity/EventSourcedTwoEntityHandler.java, tck/src/main/java/com/akkaserverless/javasdk/tck/model/localpersistenceeventing/EventSourcedEntityOneHandler.java, tck/src/main/java/com/akkaserverless/javasdk/tck/model/localpersistenceeventing/EventSourcedEntityTwoHandler.java
This takes the approach from second commit in https://github.com/lightbend/akkaserverless-java-sdk/pull/150
* parse comand in EventSourcedEntitiesImpl
* simplify generated code for exceptions
=> Use Object command parameter in EventSourcedEntityHandler

codegen/java-gen/src/main/scala/com/lightbend/akkasls/codegen/java/ActionServiceSourceGenerator.scala, codegen/java-gen/src/test/scala/com/lightbend/akkasls/codegen/java/ActionServiceSourceGeneratorSuite.scala, samples/java-customer-registry/src/main/java/customer/action/CustomerActionImpl.java, sdk/src/main/java/com/akkaserverless/javasdk/action/Action.java, sdk/src/main/scala/com/akkaserverless/javasdk/impl/action/ActionEffectImpl.scala, sdk/src/main/scala/com/akkaserverless/javasdk/impl/action/ActionHandler.scala, sdk/src/main/scala/com/akkaserverless/javasdk/impl/action/ActionsImpl.scala, sdk/src/test/scala/com/akkaserverless/javasdk/impl/action/ActionHandlerSpec.scala, tck/src/main/java/com/akkaserverless/javasdk/tck/model/action/ActionTckModelBehavior.java, tck/src/main/java/com/akkaserverless/javasdk/tck/model/action/ActionTckModelBehaviorHandler.java, tck/src/main/java/com/akkaserverless/javasdk/tck/model/action/ActionTwoBehavior.java, tck/src/main/java/com/akkaserverless/javasdk/tck/model/action/ActionTwoBehaviorHandler.java, tck/src/main/java/com/akkaserverless/javasdk/tck/model/localpersistenceeventing/LocalPersistenceSubscriber.java, tck/src/main/java/com/akkaserverless/javasdk/tck/model/localpersistenceeventing/LocalPersistenceSubscriberHandler.java
Refs #52 
Effects API for actions and implementation plus codegen.
Old Reply type left in place even though Actions does not use it anymore since replicated entities still does.
=> Effect API+impl for actions

docs/src/modules/java/examples/archetype/first-service/README.md, docs/src/modules/java/examples/archetype/first-service/pom.xml, docs/src/modules/java/examples/archetype/first-service/src/it/java/com/example/domain/CounterIntegrationTest.java, docs/src/modules/java/examples/archetype/first-service/src/main/java/com/example/Main.java, docs/src/modules/java/examples/archetype/first-service/src/main/java/com/example/domain/Counter.java, docs/src/modules/java/examples/archetype/first-service/src/test/java/com/example/domain/CounterTest.java
This updates the Maven archetype generated sources to the current state of the Java SDK.
(They are currently out of sync as we improved codegen to consistently use the `Reply` type.)
=> fix: regenerate from Maven archetype

codegen/java-gen/src/main/scala/com/lightbend/akkasls/codegen/java/EntityServiceSourceGenerator.scala, codegen/java-gen/src/test/scala/com/lightbend/akkasls/codegen/java/SourceGeneratorSuite.scala
Integration test was only generated the very first time, when the entity impl file doesn't exist. Only look for existence of the integration test file instead.
Useful for example when regenerating the integration test (rename old file and generate new).
=> Generated integration test independent of impl existence

docs/Makefile, docs/src/modules/java/nav.adoc, docs/src/modules/java/pages/developer-tools.adoc
This PR:
- Moves the developer tools section from the main docs repo to this one
- Adds a variable for the minimum supported version of the SDK to show in the docs
=> chore(docs): move developer tools to sdk repo

docs/src/modules/developing/pages/development-process-java.adoc
Add some missing links to glossary.
=> link View and Actions to glossary definitions

docs/Makefile
The minimum supported version should come from the SDK itself, not from the main docs repo. Updating this parameter so we can remove the parameter from the main docs repo.
=> chore(docs): update makefile with latest Java SDK version

codegen/core/src/main/scala/com/lightbend/akkasls/codegen/ModelBuilder.scala
Replace the mention of the old project with the new name.
=> Correct the mention of Cloudstate in the Akka Serverless SDK

docs/src/modules/java/pages/replicated-entity.adoc, samples/replicatedentity-examples/src/main/java/com/example/replicated/map/domain/SomeMap.java, sdk/src/main/java/com/akkaserverless/javasdk/replicatedentity/ReplicatedMap.java
Since Replicated Maps will usually contain different types of Replicated Data values, add accessor methods for each of the Replicated Data types which take care of the (unchecked) casting and creating default values with the factory.
=> Add specialised accessors for replicated map

maven-java/akkaserverless-maven-archetype-event-sourced-entity/src/main/resources/archetype-resources/src/main/proto/counter_domain.proto
The events sourced archetype has commands for increase and decrease a counter with a value field meaning that we could increase by 2, 3, etc. 
The events on the other hand, doesn't not hold any value as if we should only increase/decrease by one.
=> events should indicate by how much we increase or decrease

docs/src/modules/java/pages/developer-tools.adoc, docs/src/modules/java/pages/kickstart.adoc
* seems like LATEST is not resolving to 0.7.0
* don't know why, but it's better to use the released version
Fixes https://github.com/lightbend/akkaserverless-java-sdk/issues/360
=> fix: Use specific archetypeVersion instead of LATEST

docs/src/modules/java/pages/developer-tools.adoc
Follow-up to #367. The mvn commands on the developer tools page didn't have the version substituted, so they were displaying `{akkaserverless-java-sdk-version}` instead of the actual version. Also fix the archetype and plugin names. Add a link to the full kickstart page.
Not sure on the purpose of this developer tools page, which overlaps a lot with the kickstart page.
=> doc: fix commands on the developer tools page

.circleci/config.yml, docs/Makefile, docs/config/validate-links.json, docs/src/modules/developing/pages/development-process-java.adoc, docs/src/modules/java/pages/index.adoc, docs/src/modules/java/pages/quickstart-java-maven.adoc, docs/src/modules/java/partials/topic-eventing.adoc
The restructure in the main docs broke some links. There's already a `validate-links` target, add this to CI.
For Cloudstate, we found the external link checking to be flaky, so only ran it manually. But the Cloudstate docs also had a different setup which allowed separate modules to use xrefs rather than external links, so these would be validated already, but here we're using external links to the main docs. We can see how it goes with running it regularly, and how often it needs to be rerun.
=> doc: fix links to main docs and validate links in CI

.circleci/config.yml, build.sbt, codegen/scala-gen/src/main/scala/com/akkaserverless/codegen/scalasdk/AkkaserverlessGenerator.scala, codegen/scala-gen/src/main/scala/com/akkaserverless/codegen/scalasdk/AkkaserverlessTestGenerator.scala, codegen/scala-gen/src/main/scala/com/akkaserverless/codegen/scalasdk/DebugPrintlnLog.scala, codegen/scala-gen/src/main/scala/com/akkaserverless/codegen/scalasdk/File.scala, codegen/scala-gen/src/main/scala/com/akkaserverless/codegen/scalasdk/SourceGenerator.scala, codegen/scala-gen/src/main/scala/com/akkaserverless/codegen/scalasdk/gen.scala, codegen/scala-gen/src/main/scala/com/akkaserverless/codegen/scalasdk/genTests.scala, sbt-plugin/src/main/scala/com/akkaserverless/sbt/AkkaserverlessPlugin.scala, sbt-plugin/src/sbt-test/sbt-akkaserverless/basic/test
=> Populate sbt-plugin 'model', split compile/test

docs/src/modules/java/pages/replicated-entity-crdt.adoc
Update the page link (file name) for SEO, which fixes #399. A redirect to the old name has been added
=> chore(docs): update page link for seo

codegen/core/src/main/scala/com/lightbend/akkasls/codegen/Packaging.scala, codegen/java-gen-compilation-tests/src/main/proto/actions/simple_action.proto, codegen/java-gen-compilation-tests/src/main/proto/actions/simple_action_api.proto, codegen/java-gen-compilation-tests/src/main/proto/actions/some_action.proto, codegen/java-gen-compilation-tests/src/main/proto/actions/some_other_action_api.proto, codegen/java-gen-compilation-tests/src/main/proto/actions/yet_another_action.proto, codegen/java-gen-compilation-tests/src/main/proto/event-sourced-entities/some_event_sourced_entity_api.proto, codegen/java-gen-compilation-tests/src/main/proto/event-sourced-entities/some_event_sourced_entity_domain.proto, codegen/java-gen-compilation-tests/src/main/proto/value-entities/some_value_entity_api.proto, codegen/java-gen-compilation-tests/src/main/proto/value-entities/some_value_entity_domain.proto, codegen/java-gen/src/main/scala/com/lightbend/akkasls/codegen/java/EntityServiceSourceGenerator.scala, codegen/java-gen/src/main/scala/com/lightbend/akkasls/codegen/java/EventSourcedEntityTestKitGenerator.scala, codegen/java-gen/src/main/scala/com/lightbend/akkasls/codegen/java/ReplicatedEntitySourceGenerator.scala, codegen/java-gen/src/main/scala/com/lightbend/akkasls/codegen/java/SourceGenerator.scala, codegen/java-gen/src/main/scala/com/lightbend/akkasls/codegen/java/ValueEntitySourceGenerator.scala, codegen/java-gen/src/main/scala/com/lightbend/akkasls/codegen/java/ValueEntityTestKitGenerator.scala
Fixes #239 and follow-up to #396.
Code generation now takes into account what the generated outer class will be, with or without the `java_outer_classname` option, and whether generated classes will be wrapped or not based on `java_multiple_files`. Add some compilation tests — add all variations for actions, and a multiple files + default outer class for event sourced and value entities.
=> fix: codegen for outer class and multiple files variations

build.sbt
The sbt-sublime plugin chokes on this. (I know it is ancient, it's just great for navigating sources quickly)
=> fix: changed names of java example projects.

codegen/core/src/test/scala/com/lightbend/akkasls/codegen/SourceGeneratorUtilsSuite.scala, codegen/scala-gen/src/test/scala/com/akkaserverless/codegen/scalasdk/SourceGeneratorSuite.scala
Follow up on https://github.com/lightbend/akkaserverless-java-sdk/pull/422/files#r711974672
=> chore(scalasdk): move codegen utils test to codegen core

codegen/core/src/main/scala/com/lightbend/akkasls/codegen/Format.scala, codegen/java-gen/src/main/scala/com/lightbend/akkasls/codegen/java/ActionServiceSourceGenerator.scala, codegen/java-gen/src/main/scala/com/lightbend/akkasls/codegen/java/EntityServiceSourceGenerator.scala, codegen/java-gen/src/main/scala/com/lightbend/akkasls/codegen/java/EventSourcedEntityTestKitGenerator.scala, codegen/java-gen/src/main/scala/com/lightbend/akkasls/codegen/java/ReplicatedEntitySourceGenerator.scala, codegen/java-gen/src/main/scala/com/lightbend/akkasls/codegen/java/SourceGenerator.scala, codegen/java-gen/src/main/scala/com/lightbend/akkasls/codegen/java/ValueEntitySourceGenerator.scala, codegen/java-gen/src/main/scala/com/lightbend/akkasls/codegen/java/ValueEntityTestKitGenerator.scala, codegen/java-gen/src/main/scala/com/lightbend/akkasls/codegen/java/ViewServiceSourceGenerator.scala, codegen/java-gen/src/test/scala/com/lightbend/akkasls/codegen/FormatSpec.scala
Syntax was a bad name that I picked back in the time. This PR change it to Format. 
Not urgent. I can rebase later when we finish the round of changes we are doing.
=> fix: syntax renamed to Format

sbt-plugin/src/main/scala/com/akkaserverless/sbt/AkkaserverlessPlugin.scala
I noticed
```
[error] (Compile / generateUnmanaged) java.nio.file.NoSuchFileException: /Users/patrik/dev/akkaserverless-java-sdk/samples/scala-value-entity-customer-registry/target/akkaserverless-unmanaged
```
=> fix(scalasdk): create temporaryUnmanagedDirectory

sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/impl/view/ViewAdapter.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/impl/view/ViewUpdateEffectImpl.scala
Found this minor thing. 
I'm calling it `toJavaSdk` on the Actions PR. Fixing for Views in separate PR though.
=> fix: camelCase toJavaSdk

codegen/core/src/main/scala/com/lightbend/akkasls/codegen/SourceGeneratorUtils.scala, codegen/core/src/test/scala/com/lightbend/akkasls/codegen/TestData.scala, codegen/scala-gen/src/main/scala/com/akkaserverless/codegen/scalasdk/FullyQualifiedNameExtractor.scala, codegen/scala-gen/src/main/scala/com/akkaserverless/codegen/scalasdk/impl/ValueEntitySourceGenerator.scala, codegen/scala-gen/src/test/scala/com/akkaserverless/codegen/scalasdk/ValueEntitySourceGeneratorSuite.scala
To make code nicer to read without introducing naming conflicts for the
common case where domain and API contain the same names.
Adding this structure could hopefully also help with detecting and avoiding
conflicts later (#327).
=> feat(codegen-scala): use package imports

codegen/core/src/main/scala/com/lightbend/akkasls/codegen/ModelBuilder.scala, codegen/core/src/test/scala/com/lightbend/akkasls/codegen/ModelBuilderSuite.scala, codegen/core/src/test/scala/com/lightbend/akkasls/codegen/TestData.scala, codegen/core/src/test/scala/com/lightbend/akkasls/codegen/TestFullyQualifiedNameExtractor.scala, codegen/java-gen/src/main/scala/com/lightbend/akkasls/codegen/java/ActionServiceSourceGenerator.scala, codegen/java-gen/src/main/scala/com/lightbend/akkasls/codegen/java/EntityServiceSourceGenerator.scala, codegen/java-gen/src/main/scala/com/lightbend/akkasls/codegen/java/FullyQualifiedNameExtractor.scala, codegen/java-gen/src/main/scala/com/lightbend/akkasls/codegen/java/ReplicatedEntitySourceGenerator.scala, codegen/java-gen/src/main/scala/com/lightbend/akkasls/codegen/java/ValueEntitySourceGenerator.scala, codegen/java-gen/src/main/scala/com/lightbend/akkasls/codegen/java/ViewServiceSourceGenerator.scala, codegen/java-gen/src/test/scala/com/lightbend/akkasls/codegen/java/EventSourcedEntityTestKitGeneratorSuite.scala, codegen/java-gen/src/test/scala/com/lightbend/akkasls/codegen/java/ValueEntityTestKitGeneratorSuite.scala, codegen/scala-gen/src/main/scala/com/akkaserverless/codegen/scalasdk/FullyQualifiedNameExtractor.scala, codegen/scala-gen/src/main/scala/com/akkaserverless/codegen/scalasdk/impl/ViewServiceSourceGenerator.scala, codegen/scala-gen/src/test/scala/com/akkaserverless/codegen/scalasdk/FullyQualifiedNameExtractorSuite.scala, codegen/scala-gen/src/test/scala/com/akkaserverless/codegen/scalasdk/ValueEntitySourceGeneratorSuite.scala
There is still a problem with the customer-registry sample
where Akka gRPC-generated code refers to AnnotationsProto
in a way that does not currently work, but that's a separate
issue
=> fix(codegen-scala): correctly refer to descriptor object

codegen/core/src/main/scala/com/lightbend/akkasls/codegen/Packaging.scala, codegen/core/src/test/scala/com/lightbend/akkasls/codegen/ModelBuilderSuite.scala, codegen/core/src/test/scala/com/lightbend/akkasls/codegen/TestData.scala, codegen/core/src/test/scala/com/lightbend/akkasls/codegen/TestFullyQualifiedNameExtractor.scala, codegen/java-gen/src/main/scala/com/lightbend/akkasls/codegen/java/FullyQualifiedNameExtractor.scala, codegen/java-gen/src/test/scala/com/lightbend/akkasls/codegen/java/EventSourcedEntityTestKitGeneratorSuite.scala, codegen/java-gen/src/test/scala/com/lightbend/akkasls/codegen/java/ValueEntityTestKitGeneratorSuite.scala, codegen/scala-gen/src/main/scala/com/akkaserverless/codegen/scalasdk/FullyQualifiedNameExtractor.scala, codegen/scala-gen/src/test/scala/com/akkaserverless/codegen/scalasdk/ValueEntitySourceGeneratorSuite.scala
Just clean-up. 
I noticed that we this goPackage, but we clearly don't use it. That probably come from the time that we had plans to have one codegen for all languages.
=> fix: remove unused goPackage

sbt-plugin/src/main/scala/com/akkaserverless/sbt/AkkaserverlessPlugin.scala
This way we don't get the class files from a dependencies, but we get
the proto files and generate the class files ourselves: this way we have
more control over how they are generated.
=> fix(sbt-plugin): make sure akkaserverless classes are generated

codegen/scala-gen/src/main/scala/com/akkaserverless/codegen/scalasdk/impl/ValueEntitySourceGenerator.scala, codegen/scala-gen/src/test/scala/com/akkaserverless/codegen/scalasdk/ValueEntitySourceGeneratorSuite.scala, sdk/java-sdk/src/main/java/com/akkaserverless/javasdk/valueentity/ValueEntityOptions.java, sdk/java-sdk/src/main/scala/com/akkaserverless/javasdk/impl/valueentity/ValueEntityOptionsImpl.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/impl/valueentity/ValueEntityAdapter.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/valueentity/ValueEntityOptions.scala
Let's finish this up after merging #469 so we can actually hook up the handler
=> feat(codegen-scala): value entity provider

build.sbt, project/Dependencies.scala, samples/scala-fibonacci-action/build.sbt, samples/scala-value-entity-customer-registry/build.sbt, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/JsonSupport.scala, sdk/scala-sdk/src/test/scala/com/akkaserverless/scalasdk/JsonSupportSpec.scala
=> feat(scalasdk): Json support 

codegen/scala-gen/src/main/scala/com/akkaserverless/codegen/scalasdk/impl/MainSourceGenerator.scala, codegen/scala-gen/src/main/scala/com/akkaserverless/codegen/scalasdk/impl/ViewServiceSourceGenerator.scala, codegen/scala-gen/src/test/scala/com/akkaserverless/codegen/scalasdk/MainSourceGeneratorSuite.scala, codegen/scala-gen/src/test/scala/com/akkaserverless/codegen/scalasdk/ViewServiceSourceGeneratorSuite.scala
Pure aesthetics. Favor Scala function syntax so when devs navigate to withComponents method they see Scala functions as they are used to.
=> fix: favor scala function syntax

samples/scala-fibonacci-action/build.sbt, samples/scala-value-entity-customer-registry/build.sbt, sbt-plugin/src/main/scala/com/akkaserverless/sbt/AkkaserverlessPlugin.scala, sbt-plugin/src/sbt-test/sbt-akkaserverless/basic/build.sbt, sbt-plugin/src/sbt-test/sbt-akkaserverless/basic/test
There's no happens-before relationship between mentioned tasks in a task
definition, so we need to make sure to include generated files
explicitly.
Fixes #435
=> fix: make sure unmanaged generated files are detected on first compilation attempt

.circleci/config.yml, build.sbt
* similar to codegenJava
* annoying that they have different naming conventions
tab completion:
```
sbt:akkaserverless-java-sdk> codegen
codegenCore/                  codegenJava/                  codegenJavaCompilationTest/   codegenScala/
```
=> chore(scalasdk): codegenScala sbt project

sbt-plugin/src/main/scala/com/akkaserverless/sbt/AkkaserverlessPlugin.scala, sbt-plugin/src/sbt-test/sbt-akkaserverless/basic/test
Don't generate the Akka gRPC server for now, as its handlers clash with Akkaserverless-generated handlers
=> fix(sbt-plugin): rely on Akka gRPC-generated model classes

samples/scala-value-entity-customer-registry/build.sbt, samples/scala-value-entity-customer-registry/project/plugins.sbt
I guess it makes most sense to add this to the sample/template
configuration, not configure it automatically from the Akkaserverless
plugin.
Seems to work
(https://hub.docker.com/repository/docker/raboof/customer-registry),
fails with the known ClassNotFoundError in AnySupport
=> feat(scala-sample): add docker configuration

build.sbt, docs/Makefile, docs/src/modules/java/pages/api.adoc
* and some scaladoc options
References #372
=> docs(scalasdk): Scaladoc in docs Make

.circleci/config.yml
References #486, follow up of #505
=> chore: verify unmanged integration tests sources compile

sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/AkkaServerless.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/impl/view/ViewAdapter.scala
In other PRs we have chosen to not use Scala2Java and Java2Scala in the adapter names. 
PS: I'm on a low-hanging-fruit-aesthetics-coding mode
=> chore: align adapter names

maven-java/akkaserverless-maven-archetype-event-sourced-entity/src/main/resources/archetype-resources/src/main/proto/__packageInPathFormat__/counter_api.proto, maven-java/akkaserverless-maven-archetype-value-entity/src/main/resources/archetype-resources/src/main/proto/__packageInPathFormat__/counter_api.proto
When I was preparing the value entity video, I found myself having to explain the syntax used to point to the component and came to the conclusion that this is an unnecessary complexity / distraction that we are imposing to the users. 
I still think that the annotation as we have today can be simplified to avoid this references, so maybe the change in this PR will become obsolete. Still, I would like to submit it to collect ideas.
=> chore: favor usage of FQN for proto component

docs/src/modules/java/pages/views.adoc, samples/scala-valueentity-customer-registry/src/main/scala/customer/Main.scala
* still rather many things left as TODO because they depend on the event sourced sample
References https://github.com/lightbend/akkaserverless-java-sdk/issues/372
=> docs: Scala in views docs

codegen/java-gen/src/main/scala/com/lightbend/akkasls/codegen/java/ReplicatedEntitySourceGenerator.scala, codegen/java-gen/src/main/scala/com/lightbend/akkasls/codegen/java/ValueEntitySourceGenerator.scala, codegen/java-gen/src/test/scala/com/lightbend/akkasls/codegen/java/ReplicatedEntitySourceGeneratorSuite.scala, codegen/java-gen/src/test/scala/com/lightbend/akkasls/codegen/java/ValueEntitySourceGeneratorSuite.scala, codegen/scala-gen/src/main/scala/com/akkaserverless/codegen/scalasdk/impl/ValueEntitySourceGenerator.scala, codegen/scala-gen/src/test/scala/com/akkaserverless/codegen/scalasdk/ValueEntitySourceGeneratorSuite.scala
Pure aesthetics, but nice to users...
Aligns the command names in the abstract and implementation classes. 
The 'issue' manifests as following: 
The abstract class will have methods defined as: 
`abstract public Effect<Empty> increase(CounterDomain.CounterState currentState, CounterApi.IncreaseValue increaseValue)`
The impl class will have: 
`public Effect<Empty> increase(CounterDomain.CounterState currentState, CounterApi.IncreaseValue command)`
Note the difference in the command name: `increaseValue` vs. `command`.
When we add a new method to proto file, the abstract class will get a new method with an argument with the name of the command. 
In IntelliJ, user gets an error in impl class and let the IDE generate the method for them. The new generated method will have an argument like …
=> chore: align command names

build.sbt
Scala SDK has protobuf generated Java classes, so needs the release 8 option for javac as well.
=> fix(scalasdk): support JDK 8 for generated Java classes

docs/src/modules/java/pages/index.adoc
Very minor fix, the what's next section points to pages in Java and/or Scala, so better to omit 'in Java'.
=> chore: docs section title.

docs/src/modules/java/pages/index.adoc
=> fix(scala-sdk/docs): clarify Scala SDK support tier

maven-java/akkaserverless-maven-archetype-event-sourced-entity/src/main/resources/archetype-resources/README.md, maven-java/akkaserverless-maven-archetype-value-entity/src/main/resources/archetype-resources/README.md, samples/java-customer-registry-quickstart/README.md, samples/java-eventsourced-counter/README.md, samples/java-eventsourced-shopping-cart/README.md, samples/java-fibonacci-action/README.md, samples/java-first-service/README.md, samples/java-replicatedentity-shopping-cart/README.md, samples/java-shopping-cart-quickstart/README.md, samples/java-valueentity-counter/README.md, samples/java-valueentity-shopping-cart/README.md
Follow-up to apply the changes from #506 to the archetypes themselves and all the java samples.
=> chore: update all the deploy instructions for java

docs/Makefile
Refs #523. Following improvements in #537, noticed that the docs build is running each apidocs build separately, and sbt recompiles the SDK sources for each of these builds. Haven't looked at why it hasn't manage to cache the compilation fully, but let's see how it is with these consolidated into one sbt session.
=> chore: consolidate apidocs build

project/Dependencies.scala
We don't expect the vulnerabilities to be exposed, but this should resolves the FOSSA checks in framework.
Refs https://github.com/lightbend/akkaserverless-framework/issues/869
=> bump: update commons-compress (security vulnerabilities)

.circleci/config.yml
I didn't figure out the reason, but something we merged touched the files somewhere between publishing locally and other jobs trying to determine SDK version and picking that up from the circle ci workspace, so that the SDK version published and the one the samples tried to use were not the same.
This change writes the version number, that was published locally, to a file in the workspace and jobs that wants to use the built artifact read that file instead of trying to use sbt to figure out what the current snapshot version is.
=> fix: samples using wrong snapshot version

.circleci/config.yml, codegen/core/src/main/scala/com/lightbend/akkasls/codegen/ModelBuilder.scala, codegen/core/src/main/scala/com/lightbend/akkasls/codegen/SourceGeneratorUtils.scala, codegen/scala-gen/src/main/scala/com/akkaserverless/codegen/scalasdk/impl/EventSourcedEntitySourceGenerator.scala, codegen/scala-gen/src/main/scala/com/akkaserverless/codegen/scalasdk/impl/MainSourceGenerator.scala, codegen/scala-gen/src/main/scala/com/akkaserverless/codegen/scalasdk/impl/SourceGenerator.scala, codegen/scala-gen/src/test/scala/com/akkaserverless/codegen/scalasdk/EventSourcedEntitySourceGeneratorSuite.scala, samples/scala-eventsourced-counter/.scalafmt.conf, samples/scala-eventsourced-counter/README.md, samples/scala-eventsourced-counter/build.sbt, samples/scala-eventsourced-counter/docker-compose.yml, samples/scala-eventsourced-counter/project/build.properties, samples/scala-eventsourced-counter/project/plugins.sbt, samples/scala-eventsourced-counter/src/main/proto/com/example/actions/counter_topic.proto, samples/scala-eventsourced-counter/src/main/proto/com/example/actions/counter_topic_sub.proto, samples/scala-eventsourced-counter/src/main/proto/com/example/counter_api.proto, samples/scala-eventsourced-counter/src/main/proto/com/example/domain/counter_domain.proto, samples/scala-eventsourced-counter/src/main/scala/com/example/Main.scala, samples/scala-eventsourced-counter/src/main/scala/com/example/actions/CounterJournalToTopicAction.scala, samples/scala-eventsourced-counter/src/main/scala/com/example/actions/CounterTopicSubscriptionAction.scala, samples/scala-eventsourced-counter/src/main/scala/com/example/domain/Counter.scala, samples/scala-valueentity-counter/.scalafmt.conf, samples/scala-valueentity-counter/src/main/scala/com/example/Main.scala, samples/scala-valueentity-counter/src/main/scala/com/example/actions/CounterStateSubscriptionAction.scala, samples/scala-valueentity-counter/src/main/scala/com/example/actions/DoubleCounterAction.scala, samples/scala-valueentity-counter/src/main/scala/com/example/domain/Counter.scala, samples/scala-valueentity-counter/src/test/scala/com/example/domain/CounterSpec.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/impl/eventsourcedentity/EventSourcedEntityHandler.scala
=> feat(codegen): Scala EventSourcedEntity.

codegen/core/src/test/scala/com/lightbend/akkasls/codegen/TestData.scala, codegen/scala-gen/src/main/scala/com/akkaserverless/codegen/scalasdk/impl/EventSourcedEntitySourceGenerator.scala, codegen/scala-gen/src/main/scala/com/akkaserverless/codegen/scalasdk/impl/SourceGenerator.scala, codegen/scala-gen/src/main/scala/com/akkaserverless/codegen/scalasdk/impl/ValueEntitySourceGenerator.scala, codegen/scala-gen/src/test/scala/com/akkaserverless/codegen/scalasdk/EventSourcedEntitySourceGeneratorSuite.scala, codegen/scala-gen/src/test/scala/com/akkaserverless/codegen/scalasdk/ValueEntitySourceGeneratorSuite.scala
I had missed adding component access to the Scala entities when I noticed it was needed for the TCK and did the same for the Java side earlier.
=> feat(scalasdk): access to components for Scala entities

samples/scala-eventsourced-customer-registry/build.sbt, samples/scala-valueentity-customer-registry/build.sbt
Refs #682
Two main classes lead to entry points not matching the auto-generated one so it could not actually be deployed.
Also, align the two scala customer registry projects a little bit
=> chore: Fix scala eventsourced customer registry docker build

project/ReflectiveCodeGen.scala, sbt-plugin/src/main/scala/com/akkaserverless/sbt/AkkaserverlessPlugin.scala, sbt-plugin/src/sbt-test/sbt-akkaserverless/compile-only/test
Follow up to #701.
If it worked before then only by chance, because there was a race condition between `user-function.desc` being generated and being copied to the `target/scala_2.13/classes` folder.
=> fix: make sure user-function.desc has actually been copied for Scala SDK projects

sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/impl/eventsourcedentity/EventSourcedEntityEffectImpl.scala
When implementing 
```
class Counter(context: EventSourcedEntityContext) extends AbstractCounter {
override def emptyState: CounterState = CounterState()
override def increaseWithSideEffect(
currentState: CounterState,
increaseValue: example.IncreaseValue): EventSourcedEntity.Effect[Empty] =
if (increaseValue.value < 0) {
effects.error("Value must be a zero or a positive number")
} else {
effects
.emitEvent(ValueIncreased(increaseValue.value))
.thenAddSideEffect(_ => SideEffect(components.counter.increase(example.IncreaseValue(context.entityId,increaseValue.value * 2))))
.thenReply(_ => Empty())
} 
```
it was throwing the following error.
```
[info]   scala.MatchError: CounterState(1,UnknownFieldSet(Map())) (of class com.example.domain.CounterState)
[info]   at …
```
=> fix: avoiding match error

samples/scala-eventsourced-customer-registry/src/main/scala/customer/view/CustomerByNameView.scala
If we get a CustomerCreated and the state is already initialized (non-empty), do not apply twice.
=> Only apply CustomerCreated once, on an empty state

docs/release-issue-template.md
We have no 'Shipped' column anymore, tickets are
moved out of 'To be shipped' after the demo
=> fix: remove board step from release template

samples/java-customer-registry-views-quickstart/src/it/java/customer/view/CustomerByEmailIntegrationTest.java
References #766
Turns out that awaiter library does not quite like Akka testkit await out of the box but will fail on exception unless explicitly asked to ignore exceptions.
=> fix: Failing integration test #766

codegen/core/src/main/scala/com/lightbend/akkasls/codegen/ModelBuilder.scala, codegen/core/src/test/scala/com/lightbend/akkasls/codegen/ModelBuilderSuite.scala, codegen/core/src/test/scala/com/lightbend/akkasls/codegen/TestData.scala, codegen/java-gen/src/test/resources/tests/view-service/named-new-style/generated-managed/org/example/AkkaServerlessFactory.java, codegen/java-gen/src/test/resources/tests/view-service/named-new-style/generated-managed/org/example/Components.java, codegen/java-gen/src/test/resources/tests/view-service/named-new-style/generated-managed/org/example/ComponentsImpl.java, codegen/java-gen/src/test/resources/tests/view-service/named-new-style/generated-managed/org/example/named/view/AbstractMyUserByNameView.java, codegen/java-gen/src/test/resources/tests/view-service/named-new-style/generated-managed/org/example/named/view/MyUserByNameViewProvider.java, codegen/java-gen/src/test/resources/tests/view-service/named-new-style/generated-managed/org/example/named/view/MyUserByNameViewRouter.java, codegen/java-gen/src/test/resources/tests/view-service/named-new-style/generated-unmanaged/org/example/Main.java, codegen/java-gen/src/test/resources/tests/view-service/named-new-style/generated-unmanaged/org/example/named/view/MyUserByNameView.java, codegen/java-gen/src/test/resources/tests/view-service/named-new-style/proto/example-named-views.proto, codegen/java-gen/src/test/resources/tests/view-service/unnamed-new-style/generated-managed/org/example/AkkaServerlessFactory.java, codegen/java-gen/src/test/resources/tests/view-service/unnamed-new-style/generated-managed/org/example/Components.java, codegen/java-gen/src/test/resources/tests/view-service/unnamed-new-style/generated-managed/org/example/ComponentsImpl.java, codegen/java-gen/src/test/resources/tests/view-service/unnamed-new-style/generated-managed/org/example/unnamed/view/AbstractUserByNameView.java, codegen/java-gen/src/test/resources/tests/view-service/unnamed-new-style/generated-managed/org/example/unnamed/view/UserByNameViewProvider.java, codegen/java-gen/src/test/resources/tests/view-service/unnamed-new-style/generated-managed/org/example/unnamed/view/UserByNameViewRouter.java, codegen/java-gen/src/test/resources/tests/view-service/unnamed-new-style/generated-unmanaged/org/example/Main.java, codegen/java-gen/src/test/resources/tests/view-service/unnamed-new-style/generated-unmanaged/org/example/unnamed/view/UserByNameView.java, codegen/java-gen/src/test/resources/tests/view-service/unnamed-new-style/proto/example-unnamed-views.proto, codegen/java-gen/src/test/resources/tests/view-service/view-in-name-new-style/generated-managed/org/example/AkkaServerlessFactory.java, codegen/java-gen/src/test/resources/tests/view-service/view-in-name-new-style/generated-managed/org/example/Components.java, codegen/java-gen/src/test/resources/tests/view-service/view-in-name-new-style/generated-managed/org/example/ComponentsImpl.java, codegen/java-gen/src/test/resources/tests/view-service/view-in-name-new-style/generated-managed/org/example/view/AbstractUserByNameView.java, codegen/java-gen/src/test/resources/tests/view-service/view-in-name-new-style/generated-managed/org/example/view/UserByNameViewProvider.java, codegen/java-gen/src/test/resources/tests/view-service/view-in-name-new-style/generated-managed/org/example/view/UserByNameViewRouter.java, codegen/java-gen/src/test/resources/tests/view-service/view-in-name-new-style/generated-unmanaged/org/example/Main.java, codegen/java-gen/src/test/resources/tests/view-service/view-in-name-new-style/generated-unmanaged/org/example/view/UserByNameViewImpl.java, codegen/java-gen/src/test/resources/tests/view-service/view-in-name-new-style/proto/example-views.proto
I will send separated PRs per component types to avoid sending too large PRs. 
In this PR, I'm only exercising the views using the codegen annotation. 
We test the output for: 
* unnamed views
* unnamed views with 'View' in the name
* named views
Will fix #761
=> chore: ExampleSuite tests for views (new codegen)

maven-java/akkaserverless-maven-archetype-event-sourced-entity/src/main/resources/archetype-resources/pom.xml, maven-java/akkaserverless-maven-archetype-value-entity/src/main/resources/archetype-resources/pom.xml, project/Dependencies.scala, project/plugins.sbt, samples/java-customer-registry-quickstart/pom.xml, samples/java-customer-registry-views-quickstart/pom.xml, samples/java-doc-snippets/pom.xml, samples/java-eventsourced-customer-registry/pom.xml, samples/java-eventsourced-shopping-cart/pom.xml, samples/java-fibonacci-action/pom.xml, samples/java-first-service/pom.xml, samples/java-replicatedentity-examples/pom.xml, samples/java-replicatedentity-shopping-cart/pom.xml, samples/java-shopping-cart-quickstart/pom.xml, samples/java-valueentity-counter/pom.xml, samples/java-valueentity-customer-registry/pom.xml, samples/java-valueentity-shopping-cart/pom.xml, sbt-plugin/src/sbt-test/sbt-akkaserverless/compile-only/project/plugins.sbt, sbt-plugin/src/sbt-test/sbt-akkaserverless/eventsourcedentity/project/plugins.sbt, sbt-plugin/src/sbt-test/sbt-akkaserverless/no-common-pkg-root/project/plugins.sbt
Should make building on Apple m1 work out of the box, even if packaging as docker image is not seamless yet.
References #78
=> chore: upgrade Akka gRPC to 2.1.2

maven-java/akkaserverless-maven-archetype-event-sourced-entity/src/main/resources/archetype-resources/docker-compose.yml, maven-java/akkaserverless-maven-archetype-value-entity/src/main/resources/archetype-resources/docker-compose.yml
This adds commented out placeholders for configuring JWT dev secrets as implemented in https://github.com/lightbend/akkaserverless-framework/pull/1055.
=> feat: placeholder configuration for JWT dev secrets

maven-java/akkaserverless-maven-archetype-event-sourced-entity/src/main/resources/archetype-resources/docker-compose.yml, maven-java/akkaserverless-maven-archetype-value-entity/src/main/resources/archetype-resources/docker-compose.yml
I'm not sure about this `]]#`, but it seems that it's used to escape the `$`. I couldn't find docs about it. 
In any case, I think we should only enclose the lines that seems to need it. Having it in a comment line make it less visible for us when maintaining this code.
=> chore: move closing ']]#'

project/Dependencies.scala, sdk/java-sdk-testkit/src/main/java/com/akkaserverless/javasdk/testkit/ValueEntityResult.java, sdk/java-sdk-testkit/src/main/scala/com/akkaserverless/javasdk/testkit/impl/ActionResultImpl.scala, sdk/java-sdk-testkit/src/main/scala/com/akkaserverless/javasdk/testkit/impl/EventSourcedResultImpl.scala, sdk/java-sdk-testkit/src/main/scala/com/akkaserverless/javasdk/testkit/impl/ValueEntityResultImpl.scala, sdk/java-sdk-testkit/src/test/scala/com/akkaserverless/javasdk/testkit/impl/ActionResultSpec.scala, sdk/java-sdk-testkit/src/test/scala/com/akkaserverless/javasdk/testkit/impl/EventSourcedResultSpec.scala, sdk/java-sdk-testkit/src/test/scala/com/akkaserverless/javasdk/testkit/impl/ValueEntityResultSpec.scala, sdk/java-sdk/src/main/scala/com/akkaserverless/javasdk/impl/action/ActionEffectImpl.scala, sdk/scala-sdk-testkit/src/main/scala/com/akkaserverless/scalasdk/testkit/EventSourcedResult.scala, sdk/scala-sdk-testkit/src/main/scala/com/akkaserverless/scalasdk/testkit/ValueEntityResult.scala, sdk/scala-sdk-testkit/src/main/scala/com/akkaserverless/scalasdk/testkit/impl/ActionResultImpl.scala, sdk/scala-sdk-testkit/src/main/scala/com/akkaserverless/scalasdk/testkit/impl/EffectUtils.scala, sdk/scala-sdk-testkit/src/main/scala/com/akkaserverless/scalasdk/testkit/impl/EventSourcedResultImpl.scala, sdk/scala-sdk-testkit/src/main/scala/com/akkaserverless/scalasdk/testkit/impl/ValueEntityResultImpl.scala, sdk/scala-sdk-testkit/src/test/scala/com/akkaserverless/scalasdk/testkit/impl/ActionResultSpec.scala, sdk/scala-sdk-testkit/src/test/scala/com/akkaserverless/scalasdk/testkit/impl/EventSourcedResultSpec.scala, sdk/scala-sdk-testkit/src/test/scala/com/akkaserverless/scalasdk/testkit/impl/ValueEntityResultSpec.scala
References #322 and #587
With some additional cleanup and deduplication of code in the testkit result classes
=> feat: Support side effects and forward assertion in testkits 

docs/src/modules/java/pages/index.adoc
This got broken after we changed the page in the main docs.
=> chore: fix link to quickstart page

build.sbt
=> chore: disable java formatter in ExampleSuite compilation

tck/java-tck/src/main/proto/akkaserverless/tck/model/view/view.proto
Noticed when improving view validation in https://github.com/lightbend/akkaserverless-framework/pull/1068
=> chore: unrealistic view descriptor in TCK causing validation problems

build.sbt, codegen/core/src/main/scala/com/lightbend/akkasls/codegen/File.scala, codegen/core/src/test/scala/com/lightbend/akkasls/codegen/ExampleSuiteBase.scala, codegen/java-gen/src/test/resources/tests/README.md, codegen/java-gen/src/test/scala/com/lightbend/akkasls/codegen/java/ExampleSuite.scala, codegen/scala-gen/src/test/resources/tests/README.md, codegen/scala-gen/src/test/scala/com/akkaserverless/codegen/scalasdk/ExampleSuite.scala
References #781 
With this PR we may be able to delete the codegen String comparison tests. 
It makes it a little easier to use the ExampleSuite + compilation as the base of our test strategy. 
By passing some flags to sbt we can force the regeneration of some files and then compile them. 
There is a little bit more of gymnastic is required when changing the codegen though. 
The updated README files contain some explanation on how we can use it to have a better dev roundtrip.
=> chore: trigger ExampleSuite regeneration via -D property

docs/src/modules/java/pages/views.adoc
Covers https://github.com/lightbend/akkaserverless-framework/pull/1043 and https://github.com/lightbend/akkaserverless-framework/pull/1049 so no need to merge until those are released and deployed.
I think the query language overview should move in the main docs and not in the SDK since it will be the same across SDKs.
=> docs: Paging with OFFSET and LIMIT

docs/src/modules/java/pages/quickstart/cr-value-entity-java.adoc, docs/src/modules/java/pages/quickstart/cr-value-entity-scala.adoc, docs/src/modules/java/pages/quickstart/cr-value-entity-views-java.adoc, docs/src/modules/java/pages/quickstart/sc-eventsourced-entity-java.adoc
Resolves #769. Use the CLI in quickstart docs for deploying and invoking services, instead of the console UI.
Note that `mvn deploy` automatically publishes the image and then deploys the service using `akkasls`, so steps have been simplified for the Java quickstarts.
Include the proxy command and grpcui option for invoking the service, as recently done for the Scala quickstart.
=> docs: update deploy and invoke service sections in quickstarts

sdk/java-sdk-testkit/src/main/java/com/akkaserverless/javasdk/testkit/ActionResult.java, sdk/java-sdk-testkit/src/main/java/com/akkaserverless/javasdk/testkit/EventSourcedResult.java, sdk/java-sdk-testkit/src/main/java/com/akkaserverless/javasdk/testkit/ValueEntityResult.java, sdk/java-sdk-testkit/src/main/scala/com/akkaserverless/javasdk/testkit/impl/ActionResultImpl.scala, sdk/java-sdk-testkit/src/main/scala/com/akkaserverless/javasdk/testkit/impl/EventSourcedResultImpl.scala, sdk/java-sdk-testkit/src/main/scala/com/akkaserverless/javasdk/testkit/impl/ValueEntityResultImpl.scala, sdk/java-sdk/src/main/java/com/akkaserverless/javasdk/action/Action.java, sdk/java-sdk/src/main/java/com/akkaserverless/javasdk/eventsourcedentity/EventSourcedEntity.java, sdk/java-sdk/src/main/java/com/akkaserverless/javasdk/replicatedentity/ReplicatedEntity.java, sdk/java-sdk/src/main/java/com/akkaserverless/javasdk/valueentity/ValueEntity.java, sdk/java-sdk/src/main/scala/com/akkaserverless/javasdk/impl/action/ActionEffectImpl.scala, sdk/java-sdk/src/main/scala/com/akkaserverless/javasdk/impl/action/ActionsImpl.scala, sdk/java-sdk/src/main/scala/com/akkaserverless/javasdk/impl/effect/SecondaryEffectImpl.scala, sdk/java-sdk/src/main/scala/com/akkaserverless/javasdk/impl/eventsourcedentity/EventSourcedEntityEffectImpl.scala, sdk/java-sdk/src/main/scala/com/akkaserverless/javasdk/impl/replicatedentity/ReplicatedEntityEffectImpl.scala, sdk/java-sdk/src/main/scala/com/akkaserverless/javasdk/impl/valueentity/ValueEntityEffectImpl.scala, sdk/scala-sdk-testkit/src/main/scala/com/akkaserverless/scalasdk/testkit/ActionResult.scala, sdk/scala-sdk-testkit/src/main/scala/com/akkaserverless/scalasdk/testkit/EventSourcedResult.scala, sdk/scala-sdk-testkit/src/main/scala/com/akkaserverless/scalasdk/testkit/ValueEntityResult.scala, sdk/scala-sdk-testkit/src/main/scala/com/akkaserverless/scalasdk/testkit/impl/ActionResultImpl.scala, sdk/scala-sdk-testkit/src/main/scala/com/akkaserverless/scalasdk/testkit/impl/EventSourcedResultImpl.scala, sdk/scala-sdk-testkit/src/main/scala/com/akkaserverless/scalasdk/testkit/impl/ValueEntityResultImpl.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/action/Action.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/eventsourcedentity/EventSourcedEntity.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/impl/action/ActionEffectImpl.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/impl/eventsourcedentity/EventSourcedEntityEffectImpl.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/impl/replicatedentity/ReplicatedEntityEffectImpl.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/impl/valueentity/ValueEntityEffectImpl.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/replicatedentity/ReplicatedEntity.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/valueentity/ValueEntity.scala
Added support for custom status codes to both Java and Scala SDKs.
This is to match feature parity with https://github.com/lightbend/akkaserverless-javascript-sdk/pull/253.
=> feat: custom failure status code support

.circleci/config.yml, .github/workflows/release-drafter.yml
The circleci config will have to be changed again after the branch rename later
=> chore: make sure to run CI tasks against kalix-main

project/Dependencies.scala
* CVE-2020-36518
Note that this PR is to kalix-main branch. If we need to publish it earlier we can backport to main.
=> bump: jackson-databind 2.12.6.1

tck/java-tck/src/main/proto/akkaserverless/tck/model/action/action.proto, tck/java-tck/src/main/proto/akkaserverless/tck/model/eventing/local_persistence_eventing.proto, tck/java-tck/src/main/proto/akkaserverless/tck/model/eventsourcedentity/event_sourced_configured.proto, tck/java-tck/src/main/proto/akkaserverless/tck/model/eventsourcedentity/event_sourced_entity_api.proto, tck/java-tck/src/main/proto/akkaserverless/tck/model/eventsourcedentity/event_sourced_tck_model.proto, tck/java-tck/src/main/proto/akkaserverless/tck/model/eventsourcedentity/event_sourced_two.proto, tck/java-tck/src/main/proto/akkaserverless/tck/model/replicatedentity/replicated_entity.proto, tck/java-tck/src/main/proto/akkaserverless/tck/model/valueentity/value_entity_api.proto, tck/java-tck/src/main/proto/akkaserverless/tck/model/valueentity/value_entity_configured.proto, tck/java-tck/src/main/proto/akkaserverless/tck/model/valueentity/value_entity_tck_model.proto, tck/java-tck/src/main/proto/akkaserverless/tck/model/valueentity/value_entity_two.proto, tck/java-tck/src/main/proto/akkaserverless/tck/model/view/view.proto
Unrelated to renaming, but sending to kalix-main anyway. 
I don't think we need it in the tck files. Probably dates from the time where this and the proxy were one single project?
=> chore: remove go_package

codegen/java-gen/src/main/scala/com/lightbend/akkasls/codegen/java/ActionTestKitGenerator.scala, codegen/java-gen/src/test/resources/tests/action-service/named-new-style/generated-test-managed/org/example/service/MyServiceNamedActionTestKit.java, codegen/java-gen/src/test/resources/tests/action-service/simple-new-style/generated-test-managed/org/example/service/MyServiceActionTestKit.java, codegen/java-gen/src/test/resources/tests/action-service/simple-old-style/generated-test-managed/org/example/service/MyServiceActionTestKit.java, codegen/java-gen/src/test/resources/tests/action-service/with-action-in-name/generated-test-managed/org/example/service/MyServiceActionImplTestKit.java, codegen/scala-gen/src/main/scala/com/akkaserverless/codegen/scalasdk/impl/ActionTestKitGenerator.scala, codegen/scala-gen/src/test/resources/tests/action-service/named-new-style/generated-test-managed/org/example/service/MyServiceNamedActionTestKit.scala, codegen/scala-gen/src/test/resources/tests/action-service/simple-new-style/generated-test-managed/org/example/service/MyServiceActionTestKit.scala, codegen/scala-gen/src/test/resources/tests/action-service/simple-old-style/generated-test-managed/org/example/service/MyServiceActionTestKit.scala, codegen/scala-gen/src/test/resources/tests/action-service/with-action-in-name/generated-test-managed/org/example/service/MyServiceActionImplTestKit.scala, samples/java-eventsourced-counter/src/main/java/com/example/actions/CounterJournalToTopicAction.java, samples/java-eventsourced-counter/src/main/proto/com/example/actions/counter_topic.proto, samples/java-eventsourced-counter/src/test/java/com/example/actions/CounterJournalToTopicActionTest.java, samples/scala-eventsourced-counter/src/main/proto/com/example/actions/counter_topic.proto, samples/scala-eventsourced-counter/src/main/scala/com/example/actions/CounterJournalToTopicAction.scala, samples/scala-eventsourced-counter/src/test/scala/com/example/actions/CounterJournalToTopicActionSpec.scala, sdk/java-sdk-testkit/src/main/scala/com/akkaserverless/javasdk/testkit/impl/TestKitActionContext.scala, sdk/scala-sdk-testkit/src/main/scala/com/akkaserverless/scalasdk/testkit/impl/TestKitActionContext.scala
Aproach passing Metadata to the RPC call methods themselves. One test passing using the TestKit generated by the ActionTestKitGenerator.
References #501
=> Adding Metadata and eventSubject to ActionTestKit

maven-java/kalix-maven-archetype-event-sourced-entity/src/main/resources/archetype-resources/README.md, maven-java/kalix-maven-archetype-value-entity/src/main/resources/archetype-resources/README.md
References https://github.com/lightbend/kalix-docs/issues/1189
=> chore: Update archetype READMEs to CLI centered and fix links

maven-java/kalix-maven-archetype-event-sourced-entity/src/main/resources/archetype-resources/pom.xml, maven-java/kalix-maven-archetype-value-entity/src/main/resources/archetype-resources/pom.xml, samples/java-customer-registry-kafka-quickstart/pom.xml, samples/java-customer-registry-quickstart/pom.xml, samples/java-customer-registry-views-quickstart/pom.xml, samples/java-doc-snippets/pom.xml, samples/java-eventsourced-counter/pom.xml, samples/java-eventsourced-customer-registry/pom.xml, samples/java-eventsourced-shopping-cart/pom.xml, samples/java-fibonacci-action/pom.xml, samples/java-first-service/pom.xml, samples/java-replicatedentity-examples/pom.xml, samples/java-replicatedentity-shopping-cart/pom.xml, samples/java-shopping-cart-quickstart/pom.xml, samples/java-valueentity-counter/pom.xml, samples/java-valueentity-customer-registry/pom.xml, samples/java-valueentity-shopping-cart/pom.xml
References #78 
M1 needs to cross build images for x86_64, this maven plugin setting should do that out of the box.
Manually verified to also work building an image on Linux/x86_64 (I don't think our tests cover building images)
=> feat(java): Support for building Kalix images on Mac m1 #78

docs/src/modules/java/pages/quickstart-template.adoc
Closes https://github.com/lightbend/kalix-docs/issues/1258
=> fix: remove obsolete Java project template video

codegen/java-gen/src/main/scala/kalix/codegen/java/ActionTestKitGenerator.scala, codegen/java-gen/src/main/scala/kalix/codegen/java/EventSourcedEntityTestKitGenerator.scala, codegen/java-gen/src/main/scala/kalix/codegen/java/ValueEntityTestKitGenerator.scala, codegen/java-gen/src/test/resources/tests/action-service/named-new-style/generated-test-unmanaged/org/example/service/MyServiceNamedActionTest.java, codegen/java-gen/src/test/resources/tests/action-service/simple-new-style/generated-test-unmanaged/org/example/service/MyServiceActionTest.java, codegen/java-gen/src/test/resources/tests/action-service/simple-old-style/generated-test-unmanaged/org/example/service/MyServiceActionTest.java, codegen/java-gen/src/test/resources/tests/action-service/with-action-in-name/generated-test-unmanaged/org/example/service/MyServiceActionImplTest.java, codegen/java-gen/src/test/resources/tests/event-sourced-entity/absolute-packages/generated-test-unmanaged/org/example/domain/CounterTest.java, codegen/java-gen/src/test/resources/tests/event-sourced-entity/domain-in-service-package/generated-test-unmanaged/org/example/eventsourcedentity/CounterTest.java, codegen/java-gen/src/test/resources/tests/event-sourced-entity/named-new-style-with-java-package/generated-test-unmanaged/org/example/eventsourcedentity/domain/CounterTest.java, codegen/java-gen/src/test/resources/tests/event-sourced-entity/named-new-style/generated-test-unmanaged/org/example/eventsourcedentity/domain/CounterTest.java, codegen/java-gen/src/test/resources/tests/event-sourced-entity/state-events-in-different-pacakge/generated-test-unmanaged/org/example/eventsourcedentity/domain/CounterTest.java, codegen/java-gen/src/test/resources/tests/event-sourced-entity/unnamed-new-style/generated-test-unmanaged/org/example/eventsourcedentity/CounterServiceEntityTest.java, codegen/java-gen/src/test/resources/tests/value-entity/absolute-packages/generated-test-unmanaged/org/example/domain/CounterTest.java, codegen/java-gen/src/test/resources/tests/value-entity/domain-in-service-package/generated-test-unmanaged/org/example/valueentity/CounterTest.java, codegen/java-gen/src/test/resources/tests/value-entity/named-new-style/generated-test-unmanaged/org/example/valueentity/domain/CounterTest.java, codegen/java-gen/src/test/resources/tests/value-entity/state-events-in-different-pacakge/generated-test-unmanaged/org/example/valueentity/domain/CounterTest.java, codegen/java-gen/src/test/resources/tests/value-entity/unnamed-new-style/generated-test-unmanaged/org/example/valueentity/CounterServiceEntityTest.java
Marks the unimplemented JUnit test methods with `@Ignored` so they get reported as "skipped", instead of as "success".
References https://github.com/lightbend/kalix/issues/6600
=> Codegen: Mark JUnit tests as ignored

codegen/java-gen/src/main/scala/kalix/codegen/java/ActionTestKitGenerator.scala, codegen/java-gen/src/main/scala/kalix/codegen/java/EventSourcedEntityTestKitGenerator.scala, codegen/java-gen/src/main/scala/kalix/codegen/java/ValueEntityTestKitGenerator.scala, codegen/java-gen/src/test/resources/tests/action-service/named-new-style/generated-test-unmanaged/org/example/service/MyServiceNamedActionTest.java, codegen/java-gen/src/test/resources/tests/action-service/simple-new-style/generated-test-unmanaged/org/example/service/MyServiceActionTest.java, codegen/java-gen/src/test/resources/tests/action-service/simple-old-style/generated-test-unmanaged/org/example/service/MyServiceActionTest.java, codegen/java-gen/src/test/resources/tests/action-service/with-action-in-name/generated-test-unmanaged/org/example/service/MyServiceActionImplTest.java, codegen/java-gen/src/test/resources/tests/event-sourced-entity/absolute-packages/generated-test-unmanaged/org/example/domain/CounterTest.java, codegen/java-gen/src/test/resources/tests/event-sourced-entity/domain-in-service-package/generated-test-unmanaged/org/example/eventsourcedentity/CounterTest.java, codegen/java-gen/src/test/resources/tests/event-sourced-entity/named-new-style-with-java-package/generated-test-unmanaged/org/example/eventsourcedentity/domain/CounterTest.java, codegen/java-gen/src/test/resources/tests/event-sourced-entity/named-new-style/generated-test-unmanaged/org/example/eventsourcedentity/domain/CounterTest.java, codegen/java-gen/src/test/resources/tests/event-sourced-entity/state-events-in-different-pacakge/generated-test-unmanaged/org/example/eventsourcedentity/domain/CounterTest.java, codegen/java-gen/src/test/resources/tests/event-sourced-entity/unnamed-new-style/generated-test-unmanaged/org/example/eventsourcedentity/CounterServiceEntityTest.java, codegen/java-gen/src/test/resources/tests/value-entity/absolute-packages/generated-test-unmanaged/org/example/domain/CounterTest.java, codegen/java-gen/src/test/resources/tests/value-entity/domain-in-service-package/generated-test-unmanaged/org/example/valueentity/CounterTest.java, codegen/java-gen/src/test/resources/tests/value-entity/named-new-style/generated-test-unmanaged/org/example/valueentity/domain/CounterTest.java, codegen/java-gen/src/test/resources/tests/value-entity/state-events-in-different-pacakge/generated-test-unmanaged/org/example/valueentity/domain/CounterTest.java, codegen/java-gen/src/test/resources/tests/value-entity/unnamed-new-style/generated-test-unmanaged/org/example/valueentity/CounterServiceEntityTest.java
When working with the Maven archetype, I found the suggested variable names inconsistent with what things are called in other places.
I believe this makes the generated unit test code easier applicable.
=> fix: better names in suggested Java test code

sdk/java-sdk/src/main/java/kalix/javasdk/replicatedentity/ReplicatedEntity.java, sdk/java-sdk/src/main/java/kalix/javasdk/valueentity/ValueEntity.java, sdk/scala-sdk/src/main/scala/kalix/scalasdk/action/Action.scala, sdk/scala-sdk/src/main/scala/kalix/scalasdk/eventsourcedentity/EventSourcedEntity.scala, sdk/scala-sdk/src/main/scala/kalix/scalasdk/replicatedentity/ReplicatedEntity.scala, sdk/scala-sdk/src/main/scala/kalix/scalasdk/valueentity/ValueEntity.scala
Found out some methods that should be marked as final. 
Unfortunately, the `_internalSet*Context` in Java API can't be marked as final as we override them in the Java to Scala adapters.
=> chore: add some missing 'final' modifiers

codegen/java-gen/src/main/scala/kalix/codegen/java/ActionServiceSourceGenerator.scala, codegen/java-gen/src/test/resources/tests/action-service/named-new-style/generated-managed/org/example/service/AbstractMyServiceNamedAction.java, codegen/java-gen/src/test/resources/tests/action-service/simple-new-style/generated-managed/org/example/service/AbstractMyServiceAction.java, codegen/java-gen/src/test/resources/tests/action-service/simple-old-style/generated-managed/org/example/service/AbstractMyServiceAction.java, codegen/java-gen/src/test/resources/tests/action-service/with-action-in-name/generated-managed/org/example/service/AbstractMyServiceAction.java, codegen/scala-gen/src/main/scala/kalix/codegen/scalasdk/impl/ActionServiceSourceGenerator.scala, codegen/scala-gen/src/test/resources/tests/action-service/named-new-style/generated-managed/org/example/service/AbstractMyServiceNamedAction.scala, codegen/scala-gen/src/test/resources/tests/action-service/simple-new-style/generated-managed/org/example/service/AbstractMyServiceAction.scala, codegen/scala-gen/src/test/resources/tests/action-service/simple-old-style/generated-managed/org/example/service/AbstractMyServiceAction.scala, codegen/scala-gen/src/test/resources/tests/action-service/with-action-in-name/generated-managed/org/example/service/AbstractMyServiceAction.scala, sdk/java-sdk/src/main/java/kalix/javasdk/action/Action.java, sdk/scala-sdk/src/main/scala/kalix/scalasdk/action/Action.scala
This came to the surface when working on the Timers API. 
If a user calls `components()` from outside a command handler, they get an exception with message: "ActionContext is only available when handling a message."
Not so helpful since the user don't see they are accessing the `actionContext`. 
(sending in separated PR to not clutter the Timers API PR)
=> chore: more clear error message when accessing 'components'

sdk/scala-sdk/src/main/scala/kalix/scalasdk/action/Action.scala, sdk/scala-sdk/src/main/scala/kalix/scalasdk/eventsourcedentity/EventSourcedEntity.scala, sdk/scala-sdk/src/main/scala/kalix/scalasdk/impl/action/ActionEffectImpl.scala, sdk/scala-sdk/src/main/scala/kalix/scalasdk/impl/eventsourcedentity/EventSourcedEntityEffectImpl.scala, sdk/scala-sdk/src/main/scala/kalix/scalasdk/impl/replicatedentity/ReplicatedEntityEffectImpl.scala, sdk/scala-sdk/src/main/scala/kalix/scalasdk/impl/valueentity/ValueEntityEffectImpl.scala, sdk/scala-sdk/src/main/scala/kalix/scalasdk/replicatedentity/ReplicatedEntity.scala, sdk/scala-sdk/src/main/scala/kalix/scalasdk/valueentity/ValueEntity.scala
The scala API to report errors is not so convenient because it forces the user to always wrap the status code in a Option. 
It was defined as 
```scala
def error[S](description: String, statusCode: Option[Status.Code] = None):
```
Users use it as:
```scala
error("my error message")
```
or 
```scala
error("my error message", Some(statusCode))
```
So, instead, we should have 
```scala
error("my error message")
error("my error message", statusCode) // no wrapping
```
The optional status code was recently introduced and it was released in a M1. So, probably fine to just change the method signature without deprecation cycle.
=> chore: more convenient Effect.error API

maven-java/kalix-maven-archetype-event-sourced-entity/src/main/resources/archetype-resources/pom.xml, maven-java/kalix-maven-archetype-value-entity/src/main/resources/archetype-resources/pom.xml, maven-java/kalix-maven-plugin/pom.xml, samples/java-customer-registry-kafka-quickstart/pom.xml, samples/java-customer-registry-quickstart/pom.xml, samples/java-customer-registry-views-quickstart/pom.xml, samples/java-doc-snippets/pom.xml, samples/java-eventsourced-counter/pom.xml, samples/java-eventsourced-customer-registry/pom.xml, samples/java-eventsourced-shopping-cart/pom.xml, samples/java-fibonacci-action/pom.xml, samples/java-first-service/pom.xml, samples/java-replicatedentity-examples/pom.xml, samples/java-replicatedentity-shopping-cart/pom.xml, samples/java-shopping-cart-quickstart/pom.xml, samples/java-valueentity-counter/pom.xml, samples/java-valueentity-customer-registry/pom.xml, samples/java-valueentity-shopping-cart/pom.xml
No real problem with JUnit 4.13.1, but other poms already used 4.13.2.
=> bump: JUnit 4.13.2 everywhere

maven-java/kalix-maven-archetype-event-sourced-entity/src/main/resources/archetype-resources/pom.xml, maven-java/kalix-maven-archetype-value-entity/src/main/resources/archetype-resources/pom.xml, samples/java-customer-registry-kafka-quickstart/pom.xml, samples/java-customer-registry-quickstart/pom.xml, samples/java-customer-registry-views-quickstart/pom.xml, samples/java-doc-snippets/pom.xml, samples/java-eventsourced-counter/pom.xml, samples/java-eventsourced-customer-registry/pom.xml, samples/java-eventsourced-shopping-cart/pom.xml, samples/java-fibonacci-action/pom.xml, samples/java-first-service/pom.xml, samples/java-replicatedentity-examples/pom.xml, samples/java-replicatedentity-shopping-cart/pom.xml, samples/java-shopping-cart-quickstart/pom.xml, samples/java-valueentity-counter/pom.xml, samples/java-valueentity-customer-registry/pom.xml, samples/java-valueentity-shopping-cart/pom.xml
* so that each deploy will update the service, without having to
change the version in the pom.xml
If we agree this is the right approach I will update all samples and archetypes.
I considered using https://github.com/git-commit-id/git-commit-id-maven-plugin but two concerns with that:
* it requires a git repository, and doesn't have a fallback if not in git
* LGPL license may be scary
For sbt we already use sbt-dynver for the version number.
Fixes #934
=> fix: Include build timestamp in image tag, #934

samples/scala-fibonacci-action/src/main/scala/com/example/fibonacci/FibonacciAction.scala, samples/scala-valueentity-shopping-cart/src/main/scala/com/example/shoppingcart/ShoppingCartActionImpl.scala, sdk/scala-sdk/src/main/scala/kalix/scalasdk/action/Action.scala, tck/scala-tck/src/main/scala/kalix/tck/model/action/ActionTckModelImpl.scala
As discussed in https://github.com/lightbend/kalix-jvm-sdk/pull/921#discussion_r862790158
This makes Akka's default dispatcher implicitly available inside Action. The drawback is that we can only access it when handling message as it depends on `actionContext`.
References #942
=> feat: implicitly available ExecutionContext for Actions in Scala

samples/java-customer-registry-kafka-quickstart/README.md
To make more visible that `kafka` is the folder to run `docker compose up`
=> chore: highlighting kafka as the folder to go to

docs/src/modules/java/pages/index.adoc, samples/scala-customer-registry-quickstart/build.sbt, samples/scala-doc-snippets/build.sbt, samples/scala-eventsourced-counter/build.sbt, samples/scala-eventsourced-customer-registry/build.sbt, samples/scala-eventsourced-shopping-cart/build.sbt, samples/scala-fibonacci-action/build.sbt, samples/scala-first-service/build.sbt, samples/scala-reliable-timers/build.sbt, samples/scala-replicatedentity-examples/build.sbt, samples/scala-replicatedentity-shopping-cart/build.sbt, samples/scala-valueentity-counter/build.sbt, samples/scala-valueentity-customer-registry/build.sbt, samples/scala-valueentity-shopping-cart/build.sbt, sbt-plugin/src/sbt-test/sbt-kalix/compile-only/build.sbt, sbt-plugin/src/sbt-test/sbt-kalix/eventsourcedentity/build.sbt, sbt-plugin/src/sbt-test/sbt-kalix/no-common-pkg-root/build.sbt
we should be recommending current Scala versions just on general principle...
...but one specific reason to merge this is that 2.13.8 is more JDK 17 friendly
=> use Scala 2.13.8 in examples and tests (was 2.13.6)

docs/src/modules/java/pages/quickstart/cr-value-entity-java.adoc, docs/src/modules/java/pages/quickstart/cr-value-entity-scala.adoc, samples/scala-eventsourced-counter/src/test/scala/com/example/actions/CounterJournalToTopicActionSpec.scala
* add command line styling to more commands in the Quickstart docs for Java and Scala
* align the Java and Scala pages more
* fix an `akkaserverless` leftover
=> quickstart docs: improve styling

docs/src/modules/java/pages/quickstart/cr-value-entity-java.adoc, docs/src/modules/java/pages/quickstart/cr-value-entity-scala.adoc, samples/java-customer-registry-quickstart/src/main/java/customer/domain/Customer.java, samples/scala-customer-registry-quickstart/src/main/scala/customer/domain/Customer.scala
Cover adding the `emptyState` implementation in the Customer Registry quickstart instructions for Java and Scala.
=> quickstart: add emptyState in instructions

maven-java/kalix-maven-archetype-event-sourced-entity/src/main/resources/archetype-resources/src/main/proto/__packageInPathFormat__/counter_api.proto, maven-java/kalix-maven-archetype-event-sourced-entity/src/main/resources/archetype-resources/src/main/proto/__packageInPathFormat__/kalix_policy.proto, maven-java/kalix-maven-archetype-value-entity/src/main/resources/archetype-resources/src/main/proto/__packageInPathFormat__/counter_api.proto, maven-java/kalix-maven-archetype-value-entity/src/main/resources/archetype-resources/src/main/proto/__packageInPathFormat__/kalix_policy.proto, samples/java-customer-registry-kafka-quickstart/src/main/proto/customer/api/customer_api.proto, samples/java-customer-registry-kafka-quickstart/src/main/proto/customer/kalix_policy.proto, samples/java-customer-registry-quickstart/src/main/proto/customer/api/customer_api.proto, samples/java-customer-registry-quickstart/src/main/proto/customer/kalix_policy.proto, samples/java-customer-registry-views-quickstart/src/main/proto/customer/api/customer_api.proto, samples/java-customer-registry-views-quickstart/src/main/proto/customer/kalix_policy.proto, samples/java-customer-registry-views-quickstart/src/main/proto/customer/view/customer_view.proto, samples/java-doc-snippets/src/main/proto/com/example/kalix_policy.proto, samples/java-shopping-cart-quickstart/src/main/proto/shopping/cart/api/shopping_cart_api.proto, samples/java-shopping-cart-quickstart/src/main/proto/shopping/cart/kalix_policy.proto, samples/scala-customer-registry-quickstart/src/main/proto/customer/api/customer_api.proto, samples/scala-customer-registry-quickstart/src/main/proto/customer/kalix_policy.proto, samples/scala-customer-registry-quickstart/src/main/proto/customer/view/customer_view.proto, samples/scala-doc-snippets/src/main/proto/com/example/kalix_policy.proto
Docs already claim this but it wasn't completely added to all archetypes and quickstarts
This puts a default ACL allowing cross-service calls but not access from the outside, and then specifically opens up individual gRPC services to public access
References https://github.com/lightbend/kalix/issues/6808
=> fix: More restrictive ACLs by default in quickstarts

samples/scala-customer-registry-quickstart/build.sbt, samples/scala-doc-snippets/build.sbt, samples/scala-eventsourced-counter/build.sbt, samples/scala-eventsourced-customer-registry/build.sbt, samples/scala-eventsourced-shopping-cart/build.sbt, samples/scala-fibonacci-action/build.sbt, samples/scala-reliable-timers/build.sbt, samples/scala-replicatedentity-examples/build.sbt, samples/scala-replicatedentity-shopping-cart/build.sbt, samples/scala-valueentity-counter/build.sbt, samples/scala-valueentity-customer-registry/build.sbt, samples/scala-valueentity-shopping-cart/build.sbt
`sbt run` returns immediately, since sbt 1.6 — https://github.com/sbt/sbt/issues/6767
Fork the runs to fix this for now.
=> build: fix sbt run for scala samples by forking

.circleci/config.yml, samples/java-eventsourced-counter/src/main/proto/com/example/actions/counter_topic.proto, samples/scala-eventsourced-counter/src/main/proto/com/example/actions/counter_topic.proto
The `scala-eventsourced-counter` sample was reported as not working (in a slack discussion).
A couple of samples have jobs that are not included in the CI workflow. There's a verification that each sample has a CI job, but not whether these are in the workflow and actually run. May need a little more trickery for that verification.
Adding the missing samples, one of which should fail.
=> ci: add untested samples to workflow

docs/release-issue-template.md
Just noticed the release issue template stills points to the old forum.. I guess we can update that.
=> chore: update link to kalix forum in release issue template

samples/java-valueentity-counter/src/it/java/com/example/CounterIntegrationTest.java, samples/java-valueentity-counter/src/main/java/com/example/domain/Counter.java, samples/scala-valueentity-counter/src/main/scala/com/example/domain/Counter.scala, samples/scala-valueentity-counter/src/test/scala/com/example/CounterServiceIntegrationSpec.scala, sdk/java-sdk/src/main/scala/kalix/javasdk/impl/effect/SecondaryEffectImpl.scala, sdk/java-sdk/src/test/java/kalix/javasdk/eventsourcedentity/CartEntity.java, sdk/java-sdk/src/test/java/kalix/javasdk/replicatedentity/CartEntity.java, sdk/java-sdk/src/test/java/kalix/javasdk/valueentity/CartEntity.java, sdk/java-sdk/src/test/scala/kalix/javasdk/impl/eventsourcedentity/EventSourcedEntitiesImplSpec.scala, sdk/java-sdk/src/test/scala/kalix/javasdk/impl/replicatedentity/ReplicatedEntitiesImplSpec.scala, sdk/java-sdk/src/test/scala/kalix/javasdk/impl/valueentity/ValueEntitiesImplSpec.scala, sdk/java-sdk/src/test/scala/kalix/testkit/entity/EntityMessages.scala, sdk/java-sdk/src/test/scala/kalix/testkit/eventsourcedentity/EventSourcedMessages.scala, sdk/java-sdk/src/test/scala/kalix/testkit/replicatedentity/ReplicatedEntityMessages.scala, sdk/java-sdk/src/test/scala/kalix/testkit/valueentity/ValueEntityMessages.scala
References #955 
This was working correctly but only for actions, not for entities.
=> fix: propagate GRPC status code to response for entities

project/Dependencies.scala
The goal is to allow external config of the proxy version dependency. One example would be when trying to run the integration tests of an app using the SDK but against a specific proxy version.
=> chore: allow override of proxy version by config

sdk/java-sdk/src/main/java/kalix/javasdk/eventsourcedentity/EventSourcedEntity.java, sdk/java-sdk/src/main/java/kalix/javasdk/valueentity/ValueEntity.java, sdk/java-sdk/src/main/java/kalix/javasdk/view/View.java
Defaults the `emptyState` to `null` for the Java API. This is most probably what a Java developer will expect. 
This change only affects `ValueEntity`, `EventSourcedEntity` and `View`. `ReplicatedEntity` is left as is because the `emptyData` cannot be `null`. 
This idea came out while implementing Views in the Spring SDK. Actually, it doesn't make much sense to have an empty state for views. Either we have a row in the index or we have nothing.
=> feat: emptyState defaults to 'null' in java sdk

sdk/java-sdk-testkit/src/main/java/kalix/javasdk/testkit/KalixTestKit.java, sdk/java-sdk/src/main/scala/kalix/javasdk/impl/DiscoveryImpl.scala, sdk/java-sdk/src/main/scala/kalix/javasdk/impl/GrpcClients.scala
This is the first attempt to avoid calling the proxy through DNS. 
Maybe the better way to do this is to change https://github.com/lightbend/kalix-proxy/blob/9215b87b92eb46f6fae443c3ef99468130af360c/proxy/core/src/main/resources/reference.conf#L5-L6
and add only one param which is the port kind of 
```
proxy-port = 9000
proxy-port = ${?KALIX_PROXY_PORT}
```
and then consume that from this SDK here https://github.com/lightbend/kalix-jvm-sdk/blob/1a00df65e569679804502124a67fdab2988b876d/sdk/java-sdk/src/main/scala/kalix/javasdk/impl/GrpcClients.scala#L109
For that I would need to deal with the deployment yaml files which so far I don't know how to test. 
Do you think this could be the first part of a two-step solution?
References https://github.com/lightbend/kalix-proxy/issues/1469
=> chore: avoiding calling through the mesh to the proxy

maven-java/kalix-maven-archetype-event-sourced-entity/src/main/resources/archetype-resources/docker-compose.yml, maven-java/kalix-maven-archetype-value-entity/src/main/resources/archetype-resources/docker-compose.yml, project/Dependencies.scala, samples/java-customer-registry-kafka-quickstart/docker-compose.yml, samples/java-customer-registry-kafka-quickstart/kafka/docker-compose.yml, samples/java-customer-registry-quickstart/docker-compose.yml, samples/java-customer-registry-views-quickstart/docker-compose.yml, samples/java-eventsourced-counter/docker-compose.yml, samples/java-eventsourced-shopping-cart/docker-compose.yml, samples/java-fibonacci-action/docker-compose.yml, samples/java-first-service/docker-compose.yml, samples/java-reliable-timers/docker-compose.yml, samples/java-replicatedentity-examples/docker-compose.yml, samples/java-replicatedentity-shopping-cart/docker-compose.yml, samples/java-shopping-cart-quickstart/docker-compose.yml, samples/java-valueentity-counter/docker-compose.yml, samples/java-valueentity-customer-registry/docker-compose.yml, samples/java-valueentity-shopping-cart/docker-compose.yml, samples/scala-customer-registry-quickstart/docker-compose.yml, samples/scala-eventsourced-counter/docker-compose.yml, samples/scala-eventsourced-customer-registry/docker-compose.yml, samples/scala-eventsourced-shopping-cart/docker-compose.yml, samples/scala-fibonacci-action/docker-compose.yml, samples/scala-first-service/docker-compose.yml, samples/scala-reliable-timers/docker-compose.yml, samples/scala-replicatedentity-examples/docker-compose.yml, samples/scala-replicatedentity-shopping-cart/docker-compose.yml, samples/scala-valueentity-counter/docker-compose.yml, samples/scala-valueentity-customer-registry/docker-compose.yml, samples/scala-valueentity-shopping-cart/docker-compose.yml
References [Release Proxy 1.0.16](https://github.com/lightbend/kalix-proxy/issues/1611)
=> chore: bump proxy version to 1.0.16

docs/src/modules/java/pages/quickstart/cr-value-entity-java.adoc, docs/src/modules/java/pages/quickstart/cr-value-entity-scala.adoc
I am following the scala/java quickguide to learn more about Kalix.
There is already an example on how to expose a service on a public address but no example on how to call it.
When I copied the grpcurl example from how to call the service via the local proxy I made a simple mistake by not removing the --plaintext argument and also add :443. This combined with that go client produce an error like Failed to dial target host "xxx-xxx.kalix.app": context deadline exceeded and Error invoking method "customer-registry/GetCustomer": target server does not expose service "customer-registry" got me lost.
I manage to add an example and build the docs locally. Please let me know if I need to do something more or/and if you don't think that this is a good idea.
=> Example on how to call exposed service

sdk/java-sdk/src/main/scala/kalix/javasdk/impl/action/ActionsImpl.scala, sdk/java-sdk/src/main/scala/kalix/javasdk/impl/eventsourcedentity/EventSourcedEntitiesImpl.scala, sdk/java-sdk/src/main/scala/kalix/javasdk/impl/replicatedentity/ReplicatedEntitiesImpl.scala, sdk/java-sdk/src/main/scala/kalix/javasdk/impl/valueentity/ValueEntitiesImpl.scala, sdk/java-sdk/src/main/scala/kalix/javasdk/impl/view/ViewsImpl.scala
Refs #1078
Calls to stream out methods from the same client are sequential with Akka HTTP/gRPC
by default, this adds an async boundary to allow them to run in parallel.
=> fix: Ensure streaming calls from proxy are parallel 

sdk/java-sdk/src/main/java/kalix/javasdk/valueentity/ValueEntity.java
In #1052, we make it possible to have an emptyState set to `null`. That's convenient and even expected for java developers. 
However, on first command, one may want to check if the state was already created with `if (currentState() == null)`. 
Because we were using `Optional.ofNullable(state)`, we still have an empty Optional that will later fail with "Current state is only available when handling a command."
I'm opting to have a `Optional(null)` here because we then preserve the behavior that `currentState()` can only be called inside the command handler.
=> chore: emptyState can be null - Optional(null)

maven-java/kalix-spring-boot-archetype/src/main/resources/archetype-resources/pom.xml
We need the arg `-parameters` to make it more convenient to use the `@JsonProperty`. With this arg, we don't need to name the properties.
=> fix: add -parameters to compiler config

.circleci/config.yml
This is to fix the pipeline failing after the merge of `spring-sdk`into `main`
=> chore: restoring parent branch in circleci

docs/release-issue-template.md
No issue.. just noted a broken link in the release issue.
(we still have a operations dashboard but I think this one is more high-level so seems more suited to check the versions)
=> chore: fix release issue link

sdk/java-sdk/src/main/java/kalix/javasdk/eventsourcedentity/EventSourcedEntity.java, sdk/java-sdk/src/main/java/kalix/javasdk/valueentity/ValueEntity.java
Those methods were added to support the Spring SDK. At some point in the future, we may need or prefer to have them moved to Spring SDK specific component classes. 
I had previously a PR on this: https://github.com/lightbend/kalix-jvm-sdk/pull/1018, but closed because I was not so happy with the directly. 
I would like to add this annotation just for good measure and give us the option to move then later.
=> chore: ApiMayChange for currentState() methods

.circleci/config.yml
Follow up of https://github.com/lightbend/kalix-jvm-sdk/pull/1113
Just noticed that the sample was not being run. Also, since we have the IT tests for spring-sdk I think it makes sense to only run the samples after the IT tests pass. Thoughts?
=> chore(ci): add missing sample and run samples after it tests

maven-java/kalix-spring-boot-archetype/src/main/resources/archetype-resources/src/main/resources/application.properties, project/Dependencies.scala, samples/spring-customer-registry-views-quickstart/src/main/resources/application.properties, samples/spring-eventsourced-counter/src/main/resources/application.properties, samples/spring-fibonacci-action/src/main/resources/application.properties
References https://github.com/lightbend/kalix/issues/7515
This is a temporary solution. We need an extra piece of configuration to tell Spring to not start the embedded server. 
A Kalix Spring application using the webflux starter. We need to keep it for now because of the reactive webclient it brings in. 
However, we may want to provide our own starter, see: https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.developing-auto-configuration
=> fix: configure spring apps to not start embedded webserver

docs/Makefile
Now that the spring sdk was released, we can add this file.
Refs https://github.com/lightbend/kalix/issues/6859
=> chore: add latest version config for spring sdk

.github/labeler.yml
When releasing, some changes we did in `samples` ended up on the Java SDK section of the Release Notes. I think it would make more sense to label those as documentation automatically.
=> chore: label changes on samples as Documentation

codegen/java-gen/src/main/scala/kalix/codegen/java/ValueEntityTestKitGenerator.scala, codegen/java-gen/src/test/resources/tests/value-entity/absolute-packages/generated-test-managed/org/example/domain/CounterTestKit.java, codegen/java-gen/src/test/resources/tests/value-entity/domain-in-service-package/generated-test-managed/org/example/valueentity/CounterTestKit.java, codegen/java-gen/src/test/resources/tests/value-entity/named-new-style/generated-test-managed/org/example/valueentity/domain/CounterTestKit.java, codegen/java-gen/src/test/resources/tests/value-entity/state-events-in-different-pacakge/generated-test-managed/org/example/valueentity/domain/CounterTestKit.java, codegen/java-gen/src/test/resources/tests/value-entity/unnamed-new-style/generated-test-managed/org/example/valueentity/CounterServiceEntityTestKit.java
Discovered that while working on #1135
We have introduced the `currentState` for the value entities, but if a user uses it and then write a test using the testkit, they will get an error because the testkit was not setting the state.
For EventSourced entities, it's already covered in #1135. This is done in the `EventSourcedEntityEffectsRunner`
=> chore: set current state in ValueEntity testkit

project/Dependencies.scala
Seems that I forgot to update it in https://github.com/lightbend/kalix-jvm-sdk/pull/1121
=> chore: bump kalix proxy version to 1.0.20

sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/KalixServer.scala
Found this while working on the ACL and thought it was better to send as an independent PR first
=> chore: disable descriptor source loading for SpringSDK

project/Dependencies.scala
Fixes https://nvd.nist.gov/vuln/detail/CVE-2022-42003 (even if we were not really affected out of the box).
=> chore: Bump jackson databind

maven-java/kalix-spring-boot-archetype/src/main/resources/archetype-resources/pom.xml, samples/spring-customer-registry-views-quickstart/pom.xml, samples/spring-eventsourced-counter/pom.xml, samples/spring-eventsourced-customer-registry/pom.xml, samples/spring-fibonacci-action/pom.xml
This was reported by @aklikic. 
IntelliJ may fail to import project do to missing plugin version.
The plugin documentation page itself doesn't indicate a version. And projects created using start.spring.io have a spring starter as parent pom. The parent pom probably includes a bom file that specifies the version. 
We probably copy it over and it worked most of the time, but it seems that it may fail in some environments.
We do plan to have our own starter project later, so we can also take the same path. For now, better to just fix the version for the plugin to avoid surprises.
=> chore: fix spring-boot-maven-plugin version

.github/labeler.yml
In hindsight, I don't think #1132 was a good idea because almost everything ends up on that section which kind of defeats the purpose, see [last release](https://github.com/lightbend/kalix-jvm-sdk/releases/tag/v1.0.9) below. So I think a better option is to label each kind of sample under the respective sdk. Doc labels stays for changes in `docs`.
=> chore: improve labeling of samples

project/DockerImage.scala
This version bump got in with https://github.com/lightbend/kalix-jvm-sdk/pull/1178 [here](https://github.com/lightbend/kalix-jvm-sdk/pull/1178/files#diff-853c9692471808e8bbfa5f1075c005cb2ff22e8b7e6e39d22b4a0bf3df8a74c1) but is causing the 1.0.10 release to [fail](https://app.circleci.com/pipelines/github/lightbend/kalix-jvm-sdk/4429/workflows/8cb3fdba-2b21-4148-a3e9-4454c381f4f7/jobs/68489) with `[error] manifest for adoptopenjdk/openjdk11:jre-11.0.9_10-ubi not found: manifest unknown: manifest unknown`.
So I suppose downgrade is an option, let me know if there's a better one.
Refs https://github.com/lightbend/kalix-jvm-sdk/issues/1186
=> chore: reverting docker plugin base img bump

sdk/spring-sdk/src/main/java/kalix/springsdk/annotations/Acl.java, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/AclDescriptorFactory.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/ActionDescriptorFactory.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/ComponentDescriptor.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/ComponentDescriptorFactory.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/EntityDescriptorFactory.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/ViewDescriptorFactory.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/reflection/KalixMethod.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/reflection/RestServiceIntrospector.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/reflection/ServiceIntrospectionException.scala, sdk/spring-sdk/src/test/java/kalix/springsdk/testmodels/eventsourcedentity/EventSourcedEntitiesTestModels.java, sdk/spring-sdk/src/test/java/kalix/springsdk/testmodels/subscriptions/PubSubTestModels.java, sdk/spring-sdk/src/test/java/kalix/springsdk/testmodels/valueentity/ValueEntitiesTestModels.java, sdk/spring-sdk/src/test/java/kalix/springsdk/testmodels/view/ViewTestModels.java, sdk/spring-sdk/src/test/scala/kalix/springsdk/impl/AclDescriptorFactorySpec.scala, sdk/spring-sdk/src/test/scala/kalix/springsdk/impl/ActionDescriptorFactorySpec.scala, sdk/spring-sdk/src/test/scala/kalix/springsdk/impl/ComponentDescriptorSuite.scala, sdk/spring-sdk/src/test/scala/kalix/springsdk/impl/EventSourcedEntityDescriptorFactorySpec.scala, sdk/spring-sdk/src/test/scala/kalix/springsdk/impl/ValueEntityDescriptorFactorySpec.scala, sdk/spring-sdk/src/test/scala/kalix/springsdk/impl/ViewDescriptorFactorySpec.scala
Adds support for ACL annotations on type level (service) and method level.
Also block the mix of `@Acl` annotations with `@Subscription`
Resolves https://github.com/lightbend/kalix/issues/7368
=> feat: support for service and method level ACL

.circleci/config.yml, samples/spring-eventsourced-shopping-cart/README.md, samples/spring-eventsourced-shopping-cart/docker-compose.yml, samples/spring-eventsourced-shopping-cart/pom.xml, samples/spring-eventsourced-shopping-cart/src/it/java/com/example/IntegrationTest.java, samples/spring-eventsourced-shopping-cart/src/main/java/com/example/shoppingcart/Main.java, samples/spring-eventsourced-shopping-cart/src/main/java/com/example/shoppingcart/ShoppingCartService.java, samples/spring-eventsourced-shopping-cart/src/main/java/com/example/shoppingcart/domain/LineItem.java, samples/spring-eventsourced-shopping-cart/src/main/java/com/example/shoppingcart/domain/ShoppingCart.java, samples/spring-eventsourced-shopping-cart/src/main/java/com/example/shoppingcart/domain/ShoppingCartEvent.java, samples/spring-eventsourced-shopping-cart/src/main/resources/application.properties, samples/spring-eventsourced-shopping-cart/src/main/resources/logback.xml, samples/spring-eventsourced-shopping-cart/src/test/java/com/example/shoppingcart/domain/ShoppingCartTest.java
References https://github.com/lightbend/kalix/issues/7715
We agreed on using similar samples from the ones being used on the java/scala counterpart, so we were missing a shoppingcart ES sample to use in docs. Adding it here.
Have a look at the approach of Service vs Entity, trying to model things closer to what a Spring dev would expect.
~I might add the ES docs here as well or we can merge this independently. Will see.~ I will do that on a separate PR.
=> chore: adding spring event-sourced shopping cart sample

docs/src/modules/java/pages/quickstart-template.adoc
Rendering mistake in java/scala page.
=> chore: fix display for group-scala in quickstart template page

maven-java/kalix-spring-boot-archetype/src/main/resources/archetype-resources/pom.xml
Fixes https://github.com/lightbend/kalix-jvm-sdk/issues/1209
=> fix: remove '{D}' from spring archetype pom

README-vale.md
Just noticed the readme pointing at the wrong folder for adding accepted words in Vale.
=> chore: fix links in Vale readme for accepted words

build.sbt
Because I'm too lazy to type `scalafmtAll;javafmtAll` over and over again.
=> chore: formatAll commands alias

samples/spring-reliable-timers/docker-compose.yml, samples/spring-reliable-timers/src/main/java/com/example/actions/OrderAction.java, samples/spring-reliable-timers/src/main/java/com/example/domain/OrderEntity.java, sdk/spring-sdk/src/it/java/com/example/wiring/XComponentCallsIntegrationTest.java, sdk/spring-sdk/src/it/java/com/example/wiring/valueentities/user/UserEntity.java, sdk/spring-sdk/src/it/java/com/example/wiring/valueentities/user/ValidateUserAction.java, sdk/spring-sdk/src/main/scala/kalix/springsdk/KalixClient.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/RestKalixClientImpl.scala
References https://github.com/lightbend/kalix/issues/7628
This:
- adds support for `PUT`, `PATCH` and `DELETE`
Still confirming if/how to support custom HTTP methods.
=> feat(spring-sdk): support more HTTP methods in KalixClient

docs/src/modules/spring/pages/development-process-spring.adoc
@efgpinto, I forgot to include this on my previous PR. 
I simply pick something from the glossary we have in the main docs repo. However, we can try to extract a common definitions and add to a partial. We can do that when we work on the Views page.
=> docs: add paragraph about views on dev process page

docs/Makefile, docs/bin/deploy.sh
Fix #1250
Follow-up of https://github.com/lightbend/kalix-jvm-sdk/pull/1199
=> fix: fail to publish docs on release

sdk/java-sdk/src/main/resources/reference.conf, sdk/java-sdk/src/main/scala/kalix/javasdk/impl/GrpcClients.scala
Refs https://github.com/lightbend/kalix-proxy/issues/1604 and https://github.com/lightbend/kalix-proxy/issues/1466
=> fix: Allow 12M incoming, s2s client to allow 12M replies in cross service calls.

docs/src/modules/spring/nav.adoc
Fix https://github.com/lightbend/kalix-jvm-sdk/issues/1276
I don't think it's worth removing the link to "Calling others services" since that one is also about to be merged (failing on CI ATM).
I ended up not removing the file itself, only the link to it..
=> docs(spring-sdk): remove page for replicated entities

sdk/java-sdk-testkit/src/main/java/kalix/javasdk/testkit/KalixTestKit.java, sdk/java-sdk/src/main/scala/kalix/javasdk/impl/ProxyInfoHolder.scala
=> fix: Use the testcontainer host name for cross component calls

.circleci/config.yml, docs/release-issue-template.md
This actually reverts something I did some months ago I think.
Current CI pipeline takes about ~11mins which I think is a bit too much. Making `tests` and `IT tests` run in parallel  should reduce that to about ~8mins.
=> chore: decrease CI pipeline run time

docs/src/modules/java/pages/event-sourced-entities.adoc
References https://github.com/lightbend/kalix-jvm-sdk/issues/1314
Fixed the broken link. I checked for more of this kind and there weren't any.
=> bug: mixing javadocs and scaladocs #1314

sdk/java-sdk-testkit/src/main/java/kalix/javasdk/testkit/KalixProxyContainer.java
Integration TestKit now looks for env variable `KALIX_TESTKIT_PROXY_IMAGE` on startup and if defined it is parsed as a docker image name and used for running the tests.
References #1047
=> feat: Run testkit against arbitrary kalix proxy image #1047

docs/src/modules/spring/partials/entity-keys.adoc
Notice a small espacing mistake on the entity keys doc
=> chore: fix escaping in composite keys documentation

updateProxyVersions.sh
I hope to use this eventually from a bot, to automate this process a bit more. Used it manually to open [this](https://github.com/lightbend/kalix-jvm-sdk/pull/1366).
References https://github.com/lightbend/kalix-proxy/issues/967
=> ci: add script to bump proxy version

samples/scala-customer-registry-quickstart/build.sbt, samples/scala-doc-snippets/build.sbt, samples/scala-eventsourced-counter/build.sbt, samples/scala-eventsourced-customer-registry-subscriber/build.sbt, samples/scala-eventsourced-customer-registry/build.sbt, samples/scala-eventsourced-shopping-cart/build.sbt, samples/scala-fibonacci-action/build.sbt, samples/scala-first-service/build.sbt, samples/scala-reliable-timers/build.sbt, samples/scala-replicatedentity-examples/build.sbt, samples/scala-replicatedentity-shopping-cart/build.sbt, samples/scala-valueentity-counter/build.sbt, samples/scala-valueentity-customer-registry/build.sbt, samples/scala-valueentity-shopping-cart/build.sbt, samples/scala-view-store/build.sbt
MacOS intel CPU (sometimes?) reports arch as x86_64 and not amd64 so check for both and cross build only if neither matches.
=> fix: CPU arch detection for docker build fix

codegen/java-gen/src/main/scala/kalix/codegen/java/ViewServiceSourceGenerator.scala, codegen/java-gen/src/test/resources/tests/view-service/view-multiple-tables/generated-managed/org/example/KalixFactory.java, codegen/java-gen/src/test/resources/tests/view-service/view-multiple-tables/generated-managed/org/example/view/AbstractAnotherCustomerOrdersView.java, codegen/java-gen/src/test/resources/tests/view-service/view-multiple-tables/generated-managed/org/example/view/AnotherCustomerOrdersViewProvider.java, codegen/java-gen/src/test/resources/tests/view-service/view-multiple-tables/generated-managed/org/example/view/AnotherCustomerOrdersViewRouter.java, codegen/java-gen/src/test/resources/tests/view-service/view-multiple-tables/generated-unmanaged/org/example/Main.java, codegen/java-gen/src/test/resources/tests/view-service/view-multiple-tables/generated-unmanaged/org/example/view/AnotherCustomerOrdersViewImpl.java, codegen/java-gen/src/test/resources/tests/view-service/view-multiple-tables/proto/customer_orders.proto, codegen/scala-gen/src/main/scala/kalix/codegen/scalasdk/impl/ViewServiceSourceGenerator.scala, codegen/scala-gen/src/test/resources/tests/view-service/view-multiple-tables/generated-managed/org/example/KalixFactory.scala, codegen/scala-gen/src/test/resources/tests/view-service/view-multiple-tables/generated-managed/org/example/view/AbstractAnotherCustomerOrdersView.scala, codegen/scala-gen/src/test/resources/tests/view-service/view-multiple-tables/generated-managed/org/example/view/AnotherCustomerOrdersViewProvider.scala, codegen/scala-gen/src/test/resources/tests/view-service/view-multiple-tables/generated-managed/org/example/view/AnotherCustomerOrdersViewRouter.scala, codegen/scala-gen/src/test/resources/tests/view-service/view-multiple-tables/generated-unmanaged/org/example/Main.scala, codegen/scala-gen/src/test/resources/tests/view-service/view-multiple-tables/generated-unmanaged/org/example/view/AnotherCustomerOrdersViewImpl.scala, codegen/scala-gen/src/test/resources/tests/view-service/view-multiple-tables/proto/customer_orders.proto
Resolves #1397
Use the correct name for the abstract view class, and add codegen tests for this.
=> fix: codegen for multi-table views with `View` in their name

sdk/java-sdk/src/main/scala/kalix/javasdk/impl/AnySupport.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/SpringSdkMessageCodec.scala, sdk/spring-sdk/src/test/scala/kalix/springsdk/impl/SpringSdkMessageCodecSpec.scala
For spring-sdk, when a `null` is returned as reply from user function, we log this:
```
2023-01-19 15:16:16,564 ERROR customer.api.CustomerEntity - Terminating entity due to unexpected failure
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "value" is null
at kalix.springsdk.impl.SpringSdkMessageCodec.lookupTypeHint(SpringSdkMessageCodec.scala:42)
```
This MR replaces the above by:
```
2023-01-19 22:15:58,056 ERROR customer.api.CustomerEntity - Terminating entity due to unexpected failure
kalix.javasdk.impl.SerializationException: Don't know how to serialize object of type null.
at kalix.springsdk.impl.SpringSdkMessageCodec.encodeJava(SpringSdkMessageCodec.scala:43)
(..)
```
Same message as used currently for java/scala sdks.
=> chore(spring-sdk): improve msg for null serialization error

.circleci/config.yml
Follow-up to #1407 where the `-p` flag was missing on the newly introduced commands.
=> ci(fossa): add project flag

samples/java-valueentity-counter-spring-client/pom.xml
Make fossa happy.. bump to 3.0.2 is not straight forward so hopefully this suffices for now.
=> bump: spring boot in java spring client sample to 2.7.8

docs/src/modules/java/partials/query-syntax-paging.adoc
Quick fix for a fragment that was using `string` instead of `String`. 
I think this page may need some extra love. For instance, that same message has field name `next_page_token` instead of camelCase `nextPageToken`. 
This page is sharing some examples with the gRPC SDK hence the usage of snake_case.
=> chore: fix java snipped for paging in query

.circleci/config.yml
* otherwise publishM2 fails
* the maven pom has <maven.compiler.release>8 so it should still build for 8
Follow up of https://github.com/lightbend/kalix-jvm-sdk/pull/1430
=> chore: use JDK 17 for releasing maven plugin

docs/src/modules/java/partials/query-syntax-reference.adoc, sdk/spring-sdk-testkit/src/main/java/kalix/springsdk/testkit/KalixConfigurationTest.java, sdk/spring-sdk/src/it/java/com/example/wiring/SpringSdkIntegrationTest.java, sdk/spring-sdk/src/it/java/com/example/wiring/valueentities/customer/CustomerEntity.java, sdk/spring-sdk/src/it/java/com/example/wiring/views/CustomerByCreationTime.java, sdk/spring-sdk/src/it/java/kalix/springsdk/KalixConfigurationTest.java, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/ProtoDescriptorGenerator.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/ProtoMessageDescriptors.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/ViewDescriptorFactory.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/WebClientProviderHolder.scala, sdk/spring-sdk/src/test/java/kalix/springsdk/testmodels/InstantEntryForArray.java, sdk/spring-sdk/src/test/java/kalix/springsdk/testmodels/InstantEntryForList.java, sdk/spring-sdk/src/test/java/kalix/springsdk/testmodels/InstantWrapper.java, sdk/spring-sdk/src/test/java/kalix/springsdk/testmodels/SimpleMessage.java, sdk/spring-sdk/src/test/java/kalix/springsdk/testmodels/valueentity/TimeTrackerEntity.java, sdk/spring-sdk/src/test/java/kalix/springsdk/testmodels/view/ViewTestModels.java, sdk/spring-sdk/src/test/scala/kalix/springsdk/impl/MessageDescriptorGeneratorSpec.scala, sdk/spring-sdk/src/test/scala/kalix/springsdk/impl/ViewDescriptorFactorySpec.scala
Quite hacky solution for issue with views for types containing `Instant`. I still need to confirm that this will work. The current tests is only patching the proto message to use proto Timestamp instead. 
References #1391
=> fix: convert Java Instant fields to proto Timestamp

sdk/spring-sdk/src/it/java/com/example/wiring/EventSourcedEntityIntegrationTest.java
References https://github.com/lightbend/kalix-jvm-sdk/issues/1439
=> fix: use await after restarting an entity

maven-java/pom.xml
I was able to reproduce the "Unable to make field private final..." error locally. Seems fixed in later nexus-staging-maven-plugin version.
Fixes #1435
=> chore: Update nexus-staging-maven-plugin for JDK 17, #1435

.circleci/config.yml, docs/bin/deploy.sh
Closes #1447 
After much digging, ended up refreshing a specific SSH key.. tried it by connecting with ssh and it gets rid of the permission denied but I think it needs the new fingerprint to test all the way.
Added a check so it fails when failing to checkout.
=> ci: fix publish docs on release

sdk/spring-sdk/src/it/java/com/example/wiring/SpringSdkIntegrationTest.java
For now, we should truncate the Instant to lower the precision. Seems to be an issue in H2 and in Postgres.
=> fix: Instant test - use lower precision

samples/java-reliable-timers/src/it/java/com/example/OrderIntegrationTest.java, samples/java-reliable-timers/src/main/java/com/example/actions/OrderAction.java
Noticed this while working on the error codes. The exception in java comes wrapped in a `CompletionException`.
=> chore: fix java timers sample

sdk/spring-sdk/src/main/scala/kalix/spring/boot/KalixReactiveWebServerFactory.scala
We were waiting for the start, but the returned Future only completes when the application terminates or when if fails to bind.
We should review this more carefully. The right thing to do is to return a Future that completes when it starts, not when it terminates.
=> fix: KalixReactiveWebServer.start

sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/KalixSpringApplication.scala
with this change we can disable components with existing Spring annotation:
```@ConditionalOnProperty```
=> fix: use the same spring context environment for KalixComponentProvider

.github/labeler.yml
Update the labeler after the modules moving. Might need to be updated again somewhat soon.
=> chore: update labeler for new modules

docs/src/modules/java/pages/views.adoc
Refs https://github.com/lightbend/kalix-proxy/issues/1207
Add details for dropping obsolete view data under the how to modify a view section.
=> docs: drop obsolete view data

docs/Makefile
Close https://github.com/lightbend/kalix-proxy/issues/1964
This hack could potentally be done on the proxy side but I think we can do it here for now. And re-evaluate when doing [this](https://github.com/lightbend/kalix-proxy/issues/1968)
=> chore: fix version checker for java-spring

docs/src/modules/java/pages/access-control.adoc, docs/src/modules/java/pages/actions-as-controller.adoc, docs/src/modules/java/pages/actions-publishing-subscribing.adoc, docs/src/modules/java/pages/actions.adoc, docs/src/modules/java/pages/call-another-service.adoc, docs/src/modules/java/pages/development-process.adoc, docs/src/modules/java/pages/event-sourced-entities.adoc, docs/src/modules/java/pages/failures-and-errors.adoc, docs/src/modules/java/pages/getting-started.adoc, docs/src/modules/java/pages/index.adoc, docs/src/modules/java/pages/quickstart/cr-value-entity-spring.adoc, docs/src/modules/java/pages/serialization.adoc, docs/src/modules/java/pages/service-to-service.adoc, docs/src/modules/java/pages/side-effects.adoc, docs/src/modules/java/pages/spring-boot-integration.adoc, docs/src/modules/java/pages/timers.adoc, docs/src/modules/java/pages/using-jwts.adoc, docs/src/modules/java/pages/value-entity.adoc, docs/src/modules/java/pages/views.adoc, docs/src/modules/java/pages/workflow-entities.adoc
Closes https://github.com/lightbend/kalix-proxy/issues/1980
Any page that was previously under `spring/` will now be under `java/`.
=> chore: add redirects from spring to java

docs/migration-guides.md, styles/Vocab/Base/accept.txt
References https://github.com/lightbend/kalix-proxy/issues/1936
This will be mainly for internal consumption because the major changes are for Spring SDK so I'm adding a `.md` file instead of creating a new page in docs. In any case, should be easy to convert to antora page anyway, if we prefer that.
=> docs: add migration guide from 1.1.x to 1.2.x

.circleci/config.yml
Avoid changes in docs sneaking into prod inadvertly.
=> ci: not publish docs on milestone releases

.github/labeler.yml
I had only one job... Follow up of https://github.com/lightbend/kalix-jvm-sdk/pull/1504
=> ci: fix labeler tag names

docs/Makefile, samples/java-spring-customer-registry-views-quickstart/.bundleignore
References https://github.com/lightbend/kalix-jvm-sdk/issues/1343
This only creates the zip so we can download it using `kalix quickstart`. We will need to add a page for it and update https://docs.kalix.io/quickstart/index.html
=> chore: zip customer-registry-views quickstart

maven-java/kalix-spring-boot-archetype/src/main/resources/archetype-resources/README.md, maven-java/kalix-spring-boot-kotlin-archetype/src/main/resources/archetype-resources/README.md
`mvn exec:exec` will also work, but our docs and readmes refer to the `spring-boot:run` and that's part of the spring boot plugin.
=> chore: template mentioning spring-boot plugin

maven-java/kalix-spring-boot-archetype/src/main/resources/archetype-resources/pom.xml, maven-java/kalix-spring-boot-kotlin-archetype/src/main/resources/archetype-resources/pom.xml, project/Dependencies.scala, samples/java-spring-customer-registry-quickstart/pom.xml, samples/java-spring-customer-registry-views-quickstart/pom.xml, samples/java-spring-doc-snippets/pom.xml, samples/java-spring-eventsourced-counter/pom.xml, samples/java-spring-eventsourced-customer-registry-subscriber/pom.xml, samples/java-spring-eventsourced-customer-registry/pom.xml, samples/java-spring-eventsourced-shopping-cart/pom.xml, samples/java-spring-fibonacci-action/pom.xml, samples/java-spring-reliable-timers/pom.xml, samples/java-spring-shopping-cart-quickstart/pom.xml, samples/java-spring-transfer-workflow/pom.xml, samples/java-spring-valueentity-counter/pom.xml, samples/java-spring-valueentity-customer-registry/pom.xml, samples/java-spring-valueentity-shopping-cart/pom.xml, samples/java-spring-view-store/pom.xml
This fix the uberjar layout. Alan hit that bug today and reported to me during a call.
It turns out that since we moved to the spring-boot-starter, the application won't start correctly when run directly from the java command, eg: `java -jar ...`. Which is how the docker image will bootstrap the application. 
The best solution I found is to rely on `spring-boot-starter-parent`. This dependency includes a few configurations to the build. Also, a shading config that builds a uberjar in the way the `starter` expects it to be.
=> fix: fix uberjar - use spring-boot-starter-parent

maven-java/kalix-spring-boot-archetype/src/main/resources/archetype-resources/pom.xml, maven-java/kalix-spring-boot-kotlin-archetype/src/main/resources/archetype-resources/pom.xml, samples/java-spring-customer-registry-quickstart/pom.xml, samples/java-spring-customer-registry-views-quickstart/pom.xml, samples/java-spring-doc-snippets/pom.xml, samples/java-spring-eventsourced-counter/pom.xml, samples/java-spring-eventsourced-customer-registry-subscriber/pom.xml, samples/java-spring-eventsourced-customer-registry/pom.xml, samples/java-spring-eventsourced-shopping-cart/pom.xml, samples/java-spring-fibonacci-action/pom.xml, samples/java-spring-reliable-timers/pom.xml, samples/java-spring-shopping-cart-quickstart/pom.xml, samples/java-spring-transfer-workflow/pom.xml, samples/java-spring-valueentity-counter/pom.xml, samples/java-spring-valueentity-customer-registry/pom.xml, samples/java-spring-valueentity-shopping-cart/pom.xml, samples/java-spring-view-store/pom.xml
The spring-boot parent brings in another version of junit5 and the mixing versions is causing 
```java
java.lang.NoClassDefFoundError: org/junit/jupiter/api/io/CleanupMode
at org.junit.jupiter.engine.JupiterTestEngine.discover(JupiterTestEngine.java:66)
at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:168)
at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:155)
at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:150)
at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:124)
at …
```
=> fix: junit5 dependency

maven-java/kalix-spring-boot-archetype/src/main/resources/archetype-resources/pom.xml, maven-java/kalix-spring-boot-kotlin-archetype/src/main/resources/archetype-resources/pom.xml, samples/java-spring-customer-registry-quickstart/pom.xml, samples/java-spring-customer-registry-views-quickstart/pom.xml, samples/java-spring-doc-snippets/pom.xml, samples/java-spring-eventsourced-counter/pom.xml, samples/java-spring-eventsourced-customer-registry-subscriber/pom.xml, samples/java-spring-eventsourced-customer-registry/pom.xml, samples/java-spring-eventsourced-shopping-cart/pom.xml, samples/java-spring-fibonacci-action/pom.xml, samples/java-spring-reliable-timers/pom.xml, samples/java-spring-shopping-cart-quickstart/pom.xml, samples/java-spring-transfer-workflow/pom.xml, samples/java-spring-valueentity-counter/pom.xml, samples/java-spring-valueentity-customer-registry/pom.xml, samples/java-spring-valueentity-shopping-cart/pom.xml, samples/java-spring-view-store/pom.xml
As reported in https://github.com/lightbend/kalix-jvm-sdk/pull/1541#issuecomment-1478157152, we were creating a hyper-fat-jar with double the size it should have. 
This PR will fix it. 
It turns out that we had a config for maven-shade-plugin coming from spring-boot-parent and our own config. Instead, we should have only one and merge them.
=> fix: remove double shading

docs/release-issue-template.md
Release issue had a link to an artifact id that we won't be releasing anymore.
=> fix: link to maven central

.github/release-drafter.yml
Same change as in JS SDK https://github.com/lightbend/kalix-javascript-sdk/pull/472
I think it's more useful to show the latest version right on the main page (same we have for akka).
VS
=> chore: use version as release name

docs/src/modules/java/pages/event-sourced-entities.adoc, sdk/java-sdk-spring/src/main/scala/kalix/javasdk/impl/JsonMessageCodec.scala, sdk/java-sdk-spring/src/main/scala/kalix/spring/impl/KalixSpringApplication.scala, sdk/java-sdk-spring/src/test/scala/kalix/javasdk/impl/JsonMessageCodecSpec.scala
References https://github.com/lightbend/kalix-jvm-sdk/issues/1556
This MR:
- changes the default back to FQCN when no TypeName is provided (which also decreases chances of collision within the same service)
- this is a breaking change for Java SDK (code-first)
- update docs to advise that TypeName should ideally be unique.
=> feat!: default to FQCN when typename is not present

.github/workflows/samples.yml, samples/java-spring-eventsourced-customer-registry-subscriber/pom.xml, samples/java-spring-eventsourced-customer-registry-subscriber/src/it/java/customer/api/CustomerIntegrationTest.java, samples/java-spring-eventsourced-customer-registry-subscriber/src/it/java/customer/api/TestkitConfig.java, samples/java-spring-eventsourced-customer-registry-subscriber/src/it/resources/logback-test.xml, samples/java-spring-eventsourced-customer-registry-subscriber/src/main/java/customer/views/CustomersByNameView.java, samples/java-spring-eventsourced-customer-registry/src/main/java/customer/api/CustomerEntity.java, sdk/java-sdk-protobuf-testkit/src/main/java/kalix/javasdk/testkit/KalixTestKit.java
This PR:
- adds an example for an integration test with s2s eventing for future reference
- this was mainly an exercise for me to understand what was possible at the moment and how
- Logs from the testcontainer proxy will now come formatted in plain text and not JSON
~I think it's useful to run in CI anyway because it also validates the s2s logic.~ Commented out this part because I don't want to spend much more time on this and it needs more work. Might revisit later.
=> docs(sample): add integration test example for s2s eventing

devtools/src/main/scala/kalix/devtools/impl/KalixProxyContainer.scala, maven-java/kalix-maven-plugin/src/main/scala/kalix/RunMojo.scala
This is still not perfect, but good enough for now.
Removal of container takes too long. I think we should look for a better solution. Like tiny http proxy running on port 9000 and forwarding traffic to kalix-proxy running on random port. Then when restarting, the proxy running on 9000 will free the port immediately while testcontainers would start a new kalix-proxy on another port.
=> fix: retry container port until is available

maven-java/kalix-maven-plugin/src/main/scala/kalix/RunMojo.scala
No need to add more information to the pom.xml about logConfig. 
New projects already have a logback-dev-mode.xml file. We can default to it. Users can always use another file if they prefer.
=> chore: make logConfig optional

maven-java/kalix-spring-boot-archetype/src/main/resources/archetype-resources/src/it/java/__packageInPathFormat__/IntegrationTest.java, samples/java-protobuf-valueentity-counter-spring-client/src/test/java/com/example/client/spring/rest/CounterControllerTest.java, samples/java-spring-customer-registry-quickstart/src/it/java/customer/api/CustomerIntegrationTest.java, samples/java-spring-customer-registry-views-quickstart/src/it/java/customer/api/CustomerIntegrationTest.java, samples/java-spring-eventsourced-counter/src/it/java/com/example/CounterIntegrationTest.java, samples/java-spring-eventsourced-customer-registry-subscriber/src/it/java/customer/api/CustomerIntegrationTest.java, samples/java-spring-eventsourced-customer-registry/src/it/java/customer/api/CustomerIntegrationTest.java, samples/java-spring-eventsourced-shopping-cart/src/it/java/com/example/IntegrationTest.java, samples/java-spring-fibonacci-action/src/it/java/com/example/fibonacci/FibonacciActionIntegrationTest.java, samples/java-spring-reliable-timers/src/it/java/com/example/OrderActionIntegrationTest.java, samples/java-spring-shopping-cart-quickstart/src/it/java/shoppingcart/cart/IntegrationTest.java, samples/java-spring-transfer-workflow-compensation/src/it/java/com/example/transfer/TransferWorkflowIntegrationTest.java, samples/java-spring-transfer-workflow/src/it/java/com/example/transfer/TransferWorkflowIntegrationTest.java, samples/java-spring-valueentity-counter/src/it/java/com/example/CounterIntegrationTest.java, samples/java-spring-valueentity-customer-registry/src/it/java/customer/CustomerIntegrationTest.java, samples/java-spring-valueentity-shopping-cart/src/it/java/com/example/IntegrationTest.java, samples/java-spring-view-store/src/it/java/store/view/StoreViewIntegrationTest.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/EventSourcedEntityIntegrationTest.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/SpringSdkIntegrationTest.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/ValueEntityIntegrationTest.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/XComponentCallsIntegrationTest.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/workflowentities/SpringWorkflowIntegrationTest.java
from spring docs:
```
If you are using JUnit 4, do not forget to also add @RunWith(SpringRunner.class) to your test, otherwise the annotations will be ignored. If you are using JUnit 5, there is no need to add the equivalent @ExtendWith(SpringExtension.class) as @SpringBootTest and the other @…​Test annotations are already annotated with it.
```
=> chore: replacing junit 4 @RunWith annotation with junit 5 @ExtendWith

sdk/java-sdk-protobuf-testkit/src/main/java/kalix/javasdk/testkit/KalixProxyContainer.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/workflowentities/SpringWorkflowIntegrationTest.java
This change was introduced in https://github.com/lightbend/kalix-jvm-sdk/pull/1516/files#diff-1cb4454ce26068222dcb8b5e3041baf55d5b3e4c9c68349c953dd4268e464922R44
But I'm not sure what it's meant to do, feels weird. Also, it's breaking ubi tests in proxy.
We could work around it if there's a good reason for it to stay though.
=> fix(testkit): remove modification of proxy name

maven-java/kalix-maven-plugin/src/main/scala/kalix/RunMojo.scala
By default we will pass `src/main/resources/logback-dev-mode.xml` to the application, but we need to check if the file really exists. 
Old projects won't have `logback-dev-mode.xml` file and will get an error message from logback.
=> fix: check if file exists before using it

devtools/src/main/scala/kalix/devtools/impl/KalixProxyContainer.scala, sdk/java-sdk-protobuf/src/main/scala/kalix/javasdk/impl/HostAndPort.scala, sdk/java-sdk-protobuf/src/test/scala/kalix/javasdk/impl/HostAndPortSpec.scala
Ensure that `host.docker.internal` is used to resolve host in container
=> fix: always use host.docker.internal in container

.circleci/config.yml, .github/workflows/fossa.yml
This runs the same scanning as a GH workflow instead of CircleCI. Once a week instead of every day should be enough.
We need to review if the target names for Fossa still make sense after the Java/Spring SDK renaming, but can do so in another step.
=> chore: migrate Dependency scanning to GH workflows

.github/workflows/fossa.yml
Selecting specific targets for the Fossa scanning is a little cumbersome and wasn't updated after the SDK renaming.
References
- #1589
=> chore: review Fossa targets after SDK renaming

project/Dependencies.scala
Explicitly bumping due to CVE-2022-3510, CVE-2022-3509, and CVE-2022-3171.
Still conservative, version 3.22.3 is the current version.
=> bump: protobuf-java 3.20.3 (was 3.20.1)

.circleci/config.yml, .github/workflows/scripted-tests.yml
I'm a bit surprised Circle used the JDK11 image.
=> chore: run Scripted Tests as GH workflow

devtools/src/main/scala/kalix/devtools/impl/KalixProxyContainer.scala, sdk/java-sdk-protobuf-testkit/src/main/java/kalix/javasdk/testkit/KalixTestKit.java, sdk/scala-sdk-protobuf-testkit/src/main/scala/kalix/scalasdk/testkit/KalixTestKit.scala
This is needed to make the ubiquitous shopping cart work. This app will listen to itself through s2s and therefore we should be able to configure the proxy correctly from inside the KalixTestKit.
=> feat: pass service port mappings to KalixTestKit

.github/workflows/samples.yml
I don't really see what goes wrong in #1599 which ends up determining an invalid version number.
If this works, it supersedes #1599.
=> chore(ci): more cache and smaller upload (2)

sdk/java-sdk-spring/src/main/resources/reference.conf, sdk/java-sdk-spring/src/main/scala/kalix/spring/impl/KalixSpringApplication.scala
This was already done inside the KalixSpringApplication, but it makes not sense to do it programmatically. Better to simply use the reference.conf. 
And it was also not working when running integration tests. We still could see a warning in the logs.
```java
2023-05-05 18:19:32,952 WARN  kalix.javasdk.impl.DiscoveryImpl - Source info descriptor [/protobuf/descriptor-sets/user-function.desc] not found on classpath. Reporting descriptor errors against source locations will be disabled. To fix this, ensure that the following configuration applied to the protobuf maven plugin:
<writeDescriptorSet>true</writeDescriptorSet>
<includeSourceInfoInDescriptorSet>true</includeSourceInfoInDescriptorSet>
<descriptorSetFileName>user-function.desc</descriptorSetFileName>
and also that the generated …
```
=> chore: reference.conf - disable descriptor source

docs/dev/antora.yml
Partially reverting #1625. 
These settings are used when building the docs locally in dev mode. Something else is enabling this in prod.
=> fix: enable todos in dev

samples/java-protobuf-eventsourced-customer-registry-subscriber/docker-compose-integration.yml, samples/java-spring-eventsourced-customer-registry-subscriber/docker-compose-integration.yml, samples/scala-protobuf-eventsourced-customer-registry-subscriber/docker-compose-integration.yml, sdk/java-sdk-spring/docker-compose-integration.yml
New docker-compose-integration.yml were left out from bot PR
=> chore: update proxy version to 1.1.12

samples/java-spring-valueentity-counter/src/main/java/com/example/action/DoubleCounterAction.java
This action was not working (found an error on the logs when running the IT test) because it didn't match the Entity state nor the endpoint it exposes.
=> chore: fix double counter action in sample

samples/java-spring-eventsourced-counter/src/it/java/com/example/CounterIntegrationTest.java, samples/java-spring-eventsourced-counter/src/it/resources/logback-test.xml, samples/java-spring-eventsourced-counter/src/main/java/com/example/actions/CounterCommandFromTopicAction.java, samples/java-spring-eventsourced-counter/src/test/resources/logback-test.xml, sdk/java-sdk-protobuf-testkit/src/main/java/kalix/javasdk/testkit/EventingTestKit.java, sdk/java-sdk-protobuf-testkit/src/main/scala/kalix/javasdk/testkit/impl/EventingTestKitImpl.scala, sdk/java-sdk-protobuf-testkit/src/test/scala/kalix/javasdk/testkit/impl/TopicImplSpec.scala
Opened this draft PR on the side to track the discussion on what would mean to have no upper type on the `expect` methods.
This would mean that both users from protocol-first or code-first would use the same API. I think this could work but opening for discussion.
~This is draft only, so might be missing some edge cases.~
=> feat: eventing teskit for java sdk

docs/src/modules/java-protobuf/pages/actions-publishing-subscribing.adoc, docs/src/modules/java/pages/actions-publishing-subscribing.adoc, docs/src/modules/java/partials/eventing-testkit-intro.adoc, samples/java-protobuf-eventsourced-counter/src/it/java/com/example/CounterTopicIntegrationTest.java, samples/java-spring-eventsourced-counter/src/it/java/com/example/CounterIntegrationTest.java, samples/java-spring-eventsourced-counter/src/main/java/com/example/actions/CounterCommandFromTopicAction.java, samples/scala-protobuf-eventsourced-counter/src/test/scala/com/example/CounterServiceIntegrationSpec.scala
References https://github.com/lightbend/kalix/issues/7883
Depends on https://github.com/lightbend/kalix-jvm-sdk/pull/1688 to pass CI, so opening against it.
This PR:
- adds eventing teskit docs for java sdk
=> docs: eventing testkit for java sdk

docs/src/modules/java/pages/event-sourced-entities.adoc, docs/src/modules/java/pages/quickstart/cr-value-entity-java.adoc, docs/src/modules/java/pages/quickstart/sc-eventsourced-entity-java.adoc, docs/src/modules/java/pages/spring-boot-integration.adoc, docs/src/modules/java/pages/value-entity.adoc, docs/src/modules/java/partials/entity-ids.adoc, samples/java-spring-eventsourced-shopping-cart/src/main/java/com/example/shoppingcart/ShoppingCartEntity.java, samples/java-spring-valueentity-counter/src/main/java/com/example/CounterEntity.java, sdk/java-sdk-spring/src/test/java/kalix/spring/testmodels/eventsourcedentity/EventSourcedEntitiesTestModels.java, sdk/java-sdk-spring/src/test/java/kalix/spring/testmodels/valueentity/ValueEntitiesTestModels.java, sdk/java-sdk-spring/src/test/java/kalix/spring/testmodels/workflow/WorkflowTestModels.java, sdk/java-sdk-spring/src/test/scala/kalix/javasdk/impl/EventSourcedEntityDescriptorFactorySpec.scala, sdk/java-sdk-spring/src/test/scala/kalix/javasdk/impl/ValueEntityDescriptorFactorySpec.scala, sdk/java-sdk-spring/src/test/scala/kalix/javasdk/impl/WorkflowEntityDescriptorFactorySpec.scala
I spotted a few more usages of 'key'.
We still mention it in the protobuf docs and glossary, we will be able to change it once in have the new annotations in the proxy protocol.
=> docs: use entity id instead of key

docs/src/modules/java/pages/actions.adoc, docs/src/modules/java/pages/timers.adoc, samples/java-spring-eventsourced-counter/src/main/java/com/example/actions/CounterCommandFromTopicAction.java, samples/java-spring-fibonacci-action/src/it/java/com/example/fibonacci/FibonacciActionIntegrationTest.java, samples/java-spring-fibonacci-action/src/main/java/com/example/fibonacci/FibonacciAction.java, samples/java-spring-fibonacci-action/src/main/java/com/example/fibonacci/LimitedFibonacciAction.java, samples/java-spring-fibonacci-action/src/test/java/com/example/fibonacci/FibonacciActionTest.java, samples/java-spring-reliable-timers/src/it/resources/logback-test.xml, samples/java-spring-reliable-timers/src/main/java/com/example/actions/OrderAction.java, samples/java-spring-reliable-timers/src/main/java/com/example/domain/OrderEntity.java, samples/java-spring-transfer-workflow-compensation/src/main/java/com/example/transfer/TransferWorkflow.java, samples/java-spring-transfer-workflow-compensation/src/main/java/com/example/wallet/WalletEntity.java, samples/java-spring-transfer-workflow/src/main/java/com/example/transfer/TransferWorkflow.java, samples/java-spring-valueentity-counter/src/main/java/com/example/action/DoubleCounterAction.java, samples/java-spring-valueentity-shopping-cart/src/main/java/com/example/api/ShoppingCartController.java, samples/java-spring-valueentity-shopping-cart/src/main/java/com/example/api/ShoppingCartEntity.java
=> feat: component client samples update

docs/src/modules/java/partials/eventing-testkit-intro.adoc
There should be an image [here](https://docs.kalix.dev/java/actions-publishing-subscribing.html#_testkit_mocked_topic), but there is not.
All because of a missing `\n`...
=> docs: fix missing image in eventing testkit

.github/workflows/ci.yml, docs/src/modules/java-protobuf/pages/actions-publishing-subscribing.adoc, docs/src/modules/java/pages/access-control.adoc, docs/src/modules/java/pages/actions-publishing-subscribing.adoc, samples/java-protobuf-customer-registry-kafka-quickstart/src/it/java/customer/api/CustomerActionIntegrationTest.java, samples/java-spring-eventsourced-counter/README.md, samples/java-spring-eventsourced-counter/pom.xml, samples/java-spring-eventsourced-counter/src/it/java/com/example/CounterIntegrationWithRealPubSubTest.java, samples/java-spring-eventsourced-counter/src/it/java/com/example/TestkitConfig.java, sdk/java-sdk-protobuf-testkit/src/main/java/kalix/javasdk/testkit/KalixTestKit.java, sdk/scala-sdk-protobuf-testkit/src/main/scala/kalix/scalasdk/testkit/KalixTestKit.scala
Close #1694 
While adding docs on how to configure an integration test to run against a real pubsub instance, I noticed that the enum value we provide on the settings is wrong (we've called it `GOOGLE_PUBSUB_EMULATOR` instead of `GOOGLE_PUBSUB`).. Using "emulator" suffix does not make much sense because in theory you could also run against a real gpubsub instance.
So along with docs, I'm changing the enum as well.
This is a breaking change but.. this option/enum was something recently introduced in 1.3.0, was not documented properly and is only for testkits, so I believe it's not a big deal to change it. But let me know your thoughts.
=> fix!: update enum for gpubsub and add docs

samples/java-spring-transfer-workflow-compensation/src/it/java/com/example/transfer/TransferWorkflowIntegrationTest.java, samples/java-spring-transfer-workflow-compensation/src/main/java/com/example/wallet/WalletEntity.java, samples/java-spring-transfer-workflow/src/it/java/com/example/transfer/TransferWorkflowIntegrationTest.java, samples/java-spring-transfer-workflow/src/main/java/com/example/wallet/WalletEntity.java
=> chore: simplifying workflow samples

samples/java-spring-eventsourced-customer-registry/src/it/java/customer/api/CustomerIntegrationTest.java, sdk/java-sdk-spring-testkit/src/main/java/kalix/spring/testkit/KalixIntegrationTestKitSupport.java, sdk/spring-boot-starter-test/src/main/scala/kalix/spring/boot/KalixConfigurationTest.scala
=> fix: enable component client for integration tests

sdk/java-sdk-protobuf-testkit/src/main/scala/kalix/javasdk/testkit/impl/EventingTestKitImpl.scala
=> fix: unwrap json on expectType for eventing testkit

docs/src/modules/java/nav.adoc, docs/src/modules/java/pages/actions.adoc, docs/src/modules/java/pages/component-and-service-calls.adoc, docs/src/modules/java/pages/event-sourced-entities.adoc, docs/src/modules/java/pages/running-locally.adoc, docs/src/modules/java/pages/value-entity.adoc, samples/java-spring-fibonacci-action/src/it/java/com/example/fibonacci/FibonacciActionComponentClientIntegrationTest.java, samples/java-spring-fibonacci-action/src/it/java/com/example/fibonacci/FibonacciActionIntegrationTest.java, samples/java-spring-fibonacci-action/src/main/java/com/example/fibonacci/FibonacciAction.java, samples/java-spring-fibonacci-action/src/main/java/com/example/fibonacci/LimitedFibonacciAction.java
=> docs: documenting ComponentClient

sdk/java-sdk-protobuf/src/main/scala/kalix/javasdk/impl/logging/KalixJoranConfigurator.scala
Fix #1758 
I have confirmed both locally and when deploying to Kalix cloud. The current jvm sdk v1.3.2 causes the logs of deployed services to be in DEBUG and formatted in plaintext instead of JSON.
=> fix: logback config not working when packaged

sdk/java-sdk-protobuf/src/main/scala/kalix/javasdk/impl/workflow/WorkflowImpl.scala, sdk/java-sdk-spring/src/it/java/com/example/wiring/workflowentities/SpringWorkflowIntegrationTest.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/workflowentities/WorkflowWithoutInitialState.java
=> fix: workflows, exception when running a step with a null workflow state

samples/java-protobuf-web-resources/src/main/java/com/example/FileServiceAction.java
Before this change,  running `mvn verify` in this sample failed with an npe.
=> fix: catch npe when trying to load file that does not exist

docs/src/modules/java-protobuf/pages/actions-publishing-subscribing.adoc, samples/java-protobuf-eventsourced-counter/src/it/java/com/example/CounterTopicIntegrationTest.java, samples/java-spring-eventsourced-counter/src/it/java/com/example/CounterIntegrationTest.java, sdk/java-sdk-protobuf-testkit/src/main/java/kalix/javasdk/testkit/EventingTestKit.java, sdk/java-sdk-protobuf-testkit/src/main/java/kalix/javasdk/testkit/KalixTestKit.java, sdk/java-sdk-protobuf-testkit/src/main/java/kalix/javasdk/testkit/junit/KalixTestKitResource.java, sdk/java-sdk-protobuf-testkit/src/main/scala/kalix/javasdk/testkit/impl/EventingTestKitImpl.scala, sdk/java-sdk-protobuf/src/main/scala/kalix/javasdk/impl/AnySupport.scala, sdk/java-sdk-spring/src/it/java/com/example/wiring/eventsourcedentities/counter/IncreaseAction.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/eventsourcedentities/counter/IncreaseActionWithIgnore.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/pubsub/EventingTestkitIntegrationTest.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/pubsub/SubscribeToCounterEventsTopic.java, sdk/java-sdk-spring/src/it/java/kalix/spring/KalixConfigurationTest.java, sdk/java-sdk-spring/src/main/scala/kalix/javasdk/impl/JsonMessageCodec.scala, sdk/scala-sdk-protobuf-testkit/src/main/scala/kalix/scalasdk/testkit/KalixTestKit.scala, sdk/scala-sdk-protobuf/src/main/scala/kalix/scalasdk/Kalix.scala, sdk/spring-boot-starter-test/src/main/scala/kalix/spring/boot/KalixConfigurationTest.scala
=> fix: respecting TypeName annotations when using eventing testkit

docs/src/modules/java/pages/workflows.adoc
Fixes
- https://github.com/lightbend/kalix-docs/issues/1891
=> fix: package name missing in API docs link

docs/src/modules/java/pages/component-and-service-calls.adoc
Follow-up fix from https://github.com/lightbend/kalix-jvm-sdk/pull/1751/files
The aliases were changed inadvertly and missed the old name.
=> docs(java): fix missing redirect to component calls page

samples/java-protobuf-doc-snippets/src/it/java/com/example/JwtIntegrationTest.java, samples/java-spring-doc-snippets/src/it/java/com/example/jwt/JwtIntegrationTest.java
Tiny follow-up of https://github.com/lightbend/kalix-jvm-sdk/pull/1787
=> chore: use java block for sample json

project/Dependencies.scala
Trying to get rid of some CVEs that are reported against even older protobuf-java versions.
As it turns out, Akka gRPC 2.1.6 pulls protobuf-java 3.21.1 as the 3.20.1 version is consistently evicted.
References
- https://github.com/lightbend/kalix/issues/9434
- https://github.com/lightbend/kalix/issues/9429
=> bump: protobuf-java 3.21.12 (was 3.21.1)

maven-java/kalix-maven-archetype-event-sourced-entity/src/main/resources/archetype-resources/pom.xml, maven-java/kalix-maven-archetype-value-entity/src/main/resources/archetype-resources/pom.xml, maven-java/kalix-maven-plugin/pom.xml, maven-java/kalix-spring-boot-kotlin-archetype/src/main/resources/archetype-resources/pom.xml, maven-java/pom.xml
This makes our Maven plugin and our own build require Maven 3.5.0 as minimum version.
https://maven.apache.org/docs/history.html
Bumps the plugins to current versions as detected by `mvn versions:display-plugin-updates`.
Set Java source, target and release to Java 11. I played with making Java 17 the requirement but something did not like that.
Our build requires to be on Java 17, see `maven-enforcer-plugin`.
=> bump: require Maven 3.5.0; plugin bumps

maven-java/kalix-maven-plugin/pom.xml, maven-java/pom.xml
Our docs demand Maven 3.6.0 already. Let the Kalix Maven plugin do that, as well.
References 
- https://docs.kalix.io/java/getting-started.html#_prerequisites
- #1805
=> bump: require Maven 3.6.0 (align with docs)

docs/src/modules/java-protobuf/pages/spring-client.adoc, maven-java/kalix-maven-archetype-event-sourced-entity/src/main/resources/archetype-resources/pom.xml, maven-java/kalix-maven-archetype-value-entity/src/main/resources/archetype-resources/pom.xml, project/Dependencies.scala, samples/java-protobuf-customer-registry-kafka-quickstart/pom.xml, samples/java-protobuf-customer-registry-quickstart/pom.xml, samples/java-protobuf-customer-registry-views-quickstart/pom.xml, samples/java-protobuf-doc-snippets/pom.xml, samples/java-protobuf-eventsourced-counter/pom.xml, samples/java-protobuf-eventsourced-customer-registry-subscriber/pom.xml, samples/java-protobuf-eventsourced-customer-registry/pom.xml, samples/java-protobuf-eventsourced-shopping-cart/pom.xml, samples/java-protobuf-fibonacci-action/pom.xml, samples/java-protobuf-first-service/pom.xml, samples/java-protobuf-replicatedentity-examples/pom.xml, samples/java-protobuf-replicatedentity-shopping-cart/pom.xml, samples/java-protobuf-shopping-cart-quickstart/pom.xml, samples/java-protobuf-valueentity-counter-spring-client/pom.xml, samples/java-protobuf-valueentity-counter/pom.xml, samples/java-protobuf-valueentity-customer-registry/pom.xml, samples/java-protobuf-valueentity-shopping-cart/pom.xml, samples/java-protobuf-view-store/pom.xml, samples/java-protobuf-web-resources/pom.xml
Akka 2.6.21 is the last build of the 2.6 line.
https://github.com/lightbend/kalix-jvm-sdk/blob/ba0c30d1c5efe35df3a3f840ebfcd683299732c8/project/plugins.sbt#L3-L4
Fixes 
- #1709
=> bump: align Akka gRPC version in Maven with sbt

samples/java-protobuf-eventsourced-counter/src/it/java/com/example/CounterTopicIntegrationTest.java, sdk/java-sdk-protobuf-testkit/src/main/scala/kalix/javasdk/testkit/impl/EventingTestKitImpl.scala, sdk/java-sdk-spring/src/it/java/com/example/wiring/SpringSdkIntegrationTest.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/pubsub/DockerIntegrationTest.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/tracing/TracingIntegratonTest.java
Updating the timing for some tests that failed in #1810, with the switch to H2 and some longer delays for projections. There may be others that need adjusting. Separate from the bump PR, but will also test there.
=> test: update some test timing for projections

sdk/java-sdk-protobuf/src/main/scala/kalix/javasdk/impl/workflow/WorkflowRouter.scala
Fixes https://github.com/lightbend/kalix-proxy/issues/2135
=> fix: workflow input decoding

sdk/java-sdk-spring/src/main/scala/kalix/spring/impl/KalixSpringApplication.scala, sdk/java-sdk-spring/src/test/java/kalix/spring/badwiring/workflow/IllDefinedWorkflow.java, sdk/java-sdk-spring/src/test/java/kalix/spring/badwiring/workflow/Main.java
=> fix: remove thread local based wiring

docs/src/modules/java-protobuf/pages/value-entity.adoc, docs/src/modules/java/pages/value-entity.adoc
People with a DDD background get confused by the term Value Entity. Until we have a better solution I suggest adding this note to the docs.
Refs
- https://github.com/lightbend/kalix-docs/issues/1926
=> docs: add note to Value Entities not being Value Objects

sdk/java-sdk-spring/src/main/scala/kalix/javasdk/impl/Validations.scala, sdk/java-sdk-spring/src/test/java/kalix/spring/testmodels/eventsourcedentity/EventSourcedEntitiesTestModels.java, sdk/java-sdk-spring/src/test/java/kalix/spring/testmodels/valueentity/ValueEntitiesTestModels.java, sdk/java-sdk-spring/src/test/scala/kalix/javasdk/impl/EventSourcedEntityDescriptorFactorySpec.scala, sdk/java-sdk-spring/src/test/scala/kalix/javasdk/impl/ValueEntityDescriptorFactorySpec.scala
=> fix: validate compound ids order in the path

docs/src/modules/java-protobuf/pages/actions-publishing-subscribing.adoc, docs/src/modules/java/pages/access-control.adoc, docs/src/modules/java/pages/actions-publishing-subscribing.adoc, samples/java-protobuf-customer-registry-kafka-quickstart/src/it/java/customer/api/CustomerActionWithKafkaIntegrationTest.java, samples/java-protobuf-eventsourced-counter/src/it/java/com/example/CounterTopicIntegrationTest.java, samples/java-spring-eventsourced-counter/src/it/java/com/example/CounterIntegrationTest.java, samples/java-spring-eventsourced-counter/src/it/java/com/example/CounterIntegrationWithRealPubSubTest.java, samples/java-spring-eventsourced-counter/src/it/java/com/example/TestKitConfig.java, samples/scala-protobuf-eventsourced-counter/src/test/scala/com/example/CounterServiceIntegrationSpec.scala, sdk/java-sdk-spring/src/it/java/com/example/wiring/valueentities/user/CompoundIdCounterEntity.java
=> docs: improving eventing testkit configuration documentation

docs/src/modules/java/pages/access-control.adoc, docs/src/modules/java/pages/actions-publishing-subscribing.adoc, samples/java-spring-eventsourced-counter/src/it/java/com/example/CounterIntegrationTest.java, samples/java-spring-eventsourced-counter/src/it/java/com/example/CounterIntegrationWithRealPubSubTest.java, samples/java-spring-eventsourced-counter/src/it/java/com/example/TestKitConfiguration.java
changing the name from `TestkitConfig.java` to `TestKitConfig.java` results in:
```
Unresolved include directive in modules/java/pages/actions-publishing-subscribing.adoc - include::example$java-spring-eventsourced-counter/src/it/java/com/example/TestKitConfig.java[]
```
this could be related to the file system and how it manages the case changes in file names. I renamed the file to `TestkitConfiguration.java`
=> docs: changing the file name

samples/scala-protobuf-customer-registry-quickstart/src/main/scala/customer/domain/Customer.scala
If you follow the quickstart tutorial and [run it](https://docs.kalix.io/java-protobuf/quickstart/cr-value-entity-scala.html#_invoke_your_service), by issuing `grpcurl` commands, `Address` will always come back as `null`, even when setting it, which may be perceived as a bug by the user experimenting with this.
References
- [docs](https://docs.kalix.io/java-protobuf/quickstart/cr-value-entity-scala.html)
=> Correct GetCustomer to return non-null Address.

docs/src/modules/java-protobuf/pages/views.adoc, docs/src/modules/java/pages/views.adoc, samples/java-protobuf-valueentity-customer-registry/src/it/java/customer/view/CustomersResponseByCityViewIntegrationTest.java, samples/java-protobuf-valueentity-customer-registry/src/main/java/customer/Main.java, samples/java-protobuf-valueentity-customer-registry/src/main/java/customer/view/CustomersResponseByCityView.java, samples/java-protobuf-valueentity-customer-registry/src/main/proto/customer/api/customer_api.proto, samples/java-protobuf-valueentity-customer-registry/src/main/proto/customer/view/customer_view.proto, samples/java-spring-eventsourced-customer-registry-subscriber/src/it/java/customer/api/CustomersByNameViewIntegrationTest.java, samples/java-spring-eventsourced-customer-registry-subscriber/src/main/java/customer/views/CustomersByNameView.java, samples/java-spring-valueentity-customer-registry/src/it/java/customer/CustomerIntegrationTest.java, samples/java-spring-valueentity-customer-registry/src/it/java/customer/view/CustomersResponseByCityIntegrationTest.java, samples/java-spring-valueentity-customer-registry/src/it/resources/logback-test.xml, samples/java-spring-valueentity-customer-registry/src/main/java/customer/view/CustomersResponseByCity.java, samples/scala-protobuf-valueentity-customer-registry/src/main/proto/customer/api/customer_api.proto, samples/scala-protobuf-valueentity-customer-registry/src/main/proto/customer/view/customer_view.proto, samples/scala-protobuf-valueentity-customer-registry/src/main/scala/customer/Main.scala, samples/scala-protobuf-valueentity-customer-registry/src/main/scala/customer/view/CustomersResponseByCityView.scala, samples/scala-protobuf-valueentity-customer-registry/src/test/scala/customer/view/CustomersResponseByCityViewIntegrationSpec.scala
=> docs: views integration tests

samples/java-protobuf-customer-registry-kafka-quickstart/src/it/java/customer/api/CustomerActionIntegrationTest.java
=> test: increase flaky test timeout

maven-java/kalix-maven-archetype-event-sourced-entity/src/main/resources/archetype-resources/docker-compose.yml, maven-java/kalix-maven-archetype-value-entity/src/main/resources/archetype-resources/docker-compose.yml, maven-java/kalix-spring-boot-archetype/src/main/resources/archetype-resources/docker-compose.yml, maven-java/kalix-spring-boot-kotlin-archetype/src/main/resources/archetype-resources/docker-compose.yml
Follow-up of https://github.com/lightbend/kalix-jvm-sdk/pull/1859/files#r1394273904
Changing the escaping so it does not conflict with the Auto PR bot.
=> chore: refactor escaping of artifactId on templates

project/Dependencies.scala
Current TestContainers dependencies in the `kalix-java-sdk-protobuf-testkit`:
```
[info]   +-org.testcontainers:testcontainers:1.17.6
[info]     +-com.github.docker-java:docker-java-api:3.2.13
[info]     | +-com.fasterxml.jackson.core:jackson-annotations:2.10.3 (evicted by: 2.1..
[info]     | +-com.fasterxml.jackson.core:jackson-annotations:2.14.3
[info]     | +-org.slf4j:slf4j-api:1.7.30 (evicted by: 2.0.9)
[info]     | +-org.slf4j:slf4j-api:2.0.9
[info]     |
[info]     +-com.github.docker-java:docker-java-transport-zerodep:3.2.13
[info]     | +-com.github.docker-java:docker-java-transport:3.2.13
[info]     | +-net.java.dev.jna:jna:5.8.0
[info]     | +-org.slf4j:slf4j-api:1.7.25 (evicted by: 2.0.9)
[info]     | +-org.slf4j:slf4j-api:2.0.9
[info]     |
[info]     +-junit:junit:4.13.2 …
```
=> bump: remove direct dependency on commons-compress

docs/src/modules/java-protobuf/pages/views.adoc
No issue, just something small I noticed.
=> docs: code highlight missing in views page

project/Dependencies.scala, samples/scala-protobuf-eventsourced-counter/docker-compose.yml, sdk/java-sdk-protobuf-testkit/src/main/java/kalix/javasdk/testkit/KalixTestKit.java, sdk/java-sdk-protobuf/src/main/scala/kalix/javasdk/impl/ProxyInfoHolder.scala, sdk/java-sdk-protobuf/src/main/scala/kalix/javasdk/impl/action/ActionsImpl.scala, sdk/java-sdk-protobuf/src/main/scala/kalix/javasdk/impl/eventsourcedentity/EventSourcedEntitiesImpl.scala, sdk/java-sdk-protobuf/src/main/scala/kalix/javasdk/impl/telemetry/Telemetry.scala, sdk/java-sdk-protobuf/src/main/scala/kalix/javasdk/impl/valueentity/ValueEntitiesImpl.scala, sdk/java-sdk-protobuf/src/test/scala/kalix/javasdk/impl/action/ActionHandlerSpec.scala, sdk/java-sdk-protobuf/src/test/scala/kalix/javasdk/impl/eventsourcedentity/TestEventSourced.scala, sdk/java-sdk-protobuf/src/test/scala/kalix/javasdk/impl/valueentity/TestValueEntity.scala, sdk/java-sdk-spring/docker-compose-integration.yml, sdk/java-sdk-spring/src/it/java/com/example/wiring/pubsub/PubSubIntegrationTest.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/tracing/TracingIntegrationTest.java, sdk/java-sdk-spring/src/test/scala/kalix/javasdk/impl/ActionsImplSpec.scala
Using the proxy info to set the tracing endpoint collector. See https://github.com/lightbend/kalix-runtime/pull/2196
=> feat: reading the collector endpoint from the ProxyInfo

maven-java/kalix-maven-plugin/pom.xml, project/Dependencies.scala
I've noticed the issue when using `./publishLocally.sh`:
```
[info] scalafmt: Formatting 5 Scala sources (/Users/andrzej/projects/kalix/kalix-jvm-sdk/codegen/core)...
[info] scalafmt: Formatting 8 Scala sources (/Users/andrzej/projects/kalix/kalix-jvm-sdk/codegen/core)...
[info] Compiling 14 protobuf files to /Users/andrzej/projects/kalix/kalix-jvm-sdk/codegen/core/target/scala-2.12/akka-grpc/main
[info] Main Scala API documentation to /Users/andrzej/projects/kalix/kalix-jvm-sdk/codegen/core/target/scala-2.12/api...
[info] Non-compiled module 'compiler-bridge_2.12' for Scala 2.12.15. Compiling...
error:
bad constant pool index: 0 at pos: 48445ate 2s
while compiling: <no file>
during phase: globalPhase=<no phase>, enteringPhase=<some phase>
library version: version 2.12.15
compiler …
```
=> chore: bump scala tooling version 2.12.15 -> 2.12.18

maven-java/kalix-spring-boot-archetype/src/main/resources/archetype-resources/pom.xml, maven-java/kalix-spring-boot-kotlin-archetype/src/main/resources/archetype-resources/pom.xml
Reported in by Alan in [slack](https://typesafe.slack.com/archives/CQUASEUDV/p1702500199536679)
=> fix: maven archetype kcr vars

updateProxyVersions.sh
Follow up https://github.com/lightbend/kalix-jvm-sdk/pull/1929
This alias file is soon to be removed, but I will keep for now until we have a new proxy release that actually uses the other one.
=> ci: fix recursive script

sdk/java-sdk-protobuf/src/main/java/kalix/javasdk/action/Action.java, sdk/java-sdk-protobuf/src/main/scala/kalix/javasdk/impl/action/ActionEffectImpl.scala, sdk/java-sdk-spring/src/it/java/com/example/wiring/SpringSdkIntegrationTest.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/actions/echo/ActionWithMetadata.java, sdk/scala-sdk-protobuf/src/main/scala/kalix/scalasdk/action/Action.scala, sdk/scala-sdk-protobuf/src/main/scala/kalix/scalasdk/impl/action/ActionEffectImpl.scala
Close #1935 
I'm a bit surprised we haven't heard complains about this before.. Am I missing something?
=> feat: allow metadata in asyncReply

maven-java/kalix-maven-plugin/src/main/java/kalix/DeployMojo.java
Changing like configuration, `kalixContext`, `kalixProject` causing:
```
[ERROR] Failed to execute goal io.kalix:kalix-maven-plugin:1.3.7:deploy (default-cli) on project cfp-notifier: Execution default-cli of goal io.kalix:kalix-maven-plugin:1.3.7:deploy failed.: UnsupportedOperationException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.kalix:kalix-maven-plugin:1.3.7:deploy (default-cli) on project cfp-notifier: Execution default-cli of goal io.kalix:kalix-maven-plugin:1.3.7:deploy failed.
at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:375)
at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute …
```
=> fix: kalix maven plugin with mutable list for configuration params

sdk/java-sdk-spring/src/main/scala/kalix/javasdk/impl/Validations.scala, sdk/java-sdk-spring/src/test/java/kalix/javasdk/impl/NotPublicComponents.java, sdk/java-sdk-spring/src/test/scala/kalix/javasdk/impl/ActionDescriptorFactorySpec.scala, sdk/java-sdk-spring/src/test/scala/kalix/javasdk/impl/EventSourcedEntityDescriptorFactorySpec.scala, sdk/java-sdk-spring/src/test/scala/kalix/javasdk/impl/ValueEntityDescriptorFactorySpec.scala, sdk/java-sdk-spring/src/test/scala/kalix/javasdk/impl/ViewDescriptorFactorySpec.scala, sdk/java-sdk-spring/src/test/scala/kalix/javasdk/impl/WorkflowEntityDescriptorFactorySpec.scala
=> chore: validate components are public

sdk/java-sdk-protobuf-testkit/src/main/scala/kalix/javasdk/testkit/impl/EventingTestKitImpl.scala, sdk/scala-sdk-protobuf-testkit/src/main/scala/kalix/scalasdk/testkit/impl/EventingTestKitImpl.scala
Close https://github.com/lightbend/kalix-jvm-sdk/issues/1874
And some clean-up.
=> chore: improve error msg in EventingTestKit

sdk/java-sdk-protobuf-testkit/src/main/java/kalix/javasdk/testkit/KalixTestKit.java, sdk/java-sdk-protobuf-testkit/src/main/java/kalix/javasdk/testkit/impl/KalixRuntimeContainer.java
Build on top of https://github.com/lightbend/kalix-jvm-sdk/pull/1933
This is a little more complicated. We have a KalixProxyContainer class that is public, but should have been in impl package. 
It is instantiated inside the testkit and kept private. So, from that perspective it is effectively private.
Leaving it as draft until we merge #1933 and decide what to do with this class. From my part, we can simply move it to the impl package and consider it private.
=> chore: move container class to impl package

docs/src/modules/java/pages/component-and-service-calls.adoc, samples/java-spring-fibonacci-action/src/main/java/com/example/fibonacci/LimitedFibonacciAction.java
=> docs: how to inject component client

docs/src/modules/java/pages/using-jwts.adoc, project/Dependencies.scala, sdk/java-sdk-spring/src/main/java/kalix/javasdk/annotations/JWT.java, sdk/java-sdk-spring/src/main/scala/kalix/javasdk/impl/JwtDescriptorFactory.scala, sdk/java-sdk-spring/src/test/java/kalix/spring/testmodels/action/ActionsTestModels.java, sdk/java-sdk-spring/src/test/scala/kalix/javasdk/impl/ActionDescriptorFactorySpec.scala, sdk/java-sdk-spring/src/test/scala/kalix/javasdk/impl/EventSourcedEntityDescriptorFactorySpec.scala, sdk/java-sdk-spring/src/test/scala/kalix/javasdk/impl/ValueEntityDescriptorFactorySpec.scala, sdk/java-sdk-spring/src/test/scala/kalix/javasdk/impl/ViewDescriptorFactorySpec.scala, sdk/java-sdk-spring/src/test/scala/kalix/javasdk/impl/WorkflowEntityDescriptorFactorySpec.scala
Refs https://github.com/lightbend/kalix-runtime/issues/2193
Review for review but needs to wait for next runtime release thus marking as draft.
=> feat(javasdk): support multiple values in a static claim

docs/src/modules/java/pages/using-jwts.adoc, sdk/java-sdk-spring/src/main/java/kalix/javasdk/annotations/JWT.java, sdk/java-sdk-spring/src/main/scala/kalix/javasdk/impl/JwtDescriptorFactory.scala, sdk/java-sdk-spring/src/test/java/kalix/spring/testmodels/action/ActionsTestModels.java, sdk/java-sdk-spring/src/test/scala/kalix/javasdk/impl/ActionDescriptorFactorySpec.scala
Refs https://github.com/lightbend/kalix-runtime/issues/2192
This is open against the previous PT for multiple values since it changes the same files.. will rebase once former is merged.
This also depends on Runtime release but ready for review otherwise.
=> feat(java-sdk): support for pattern in jwt static claim

.github/workflows/documentation.yml
Failures in CI due to non-backwards compatible change in `3.0.0` and us using latest by default.
=> ci: pin version of vale to 2.30.0

sdk/java-sdk-spring-testkit/src/main/java/kalix/javasdk/testkit/EventSourcedTestKit.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/eventsourcedentities/counter/Counter.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/eventsourcedentities/counter/CounterEntity.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/eventsourcedentities/counter/CounterEvent.java, sdk/java-sdk-spring/src/main/java/kalix/javasdk/eventsourced/ReflectiveEventSourcedEntityProvider.java, sdk/java-sdk-spring/src/main/scala/kalix/javasdk/impl/Validations.scala, sdk/java-sdk-spring/src/main/scala/kalix/javasdk/impl/eventsourcedentity/EventSourcedHandlersExtractor.scala, sdk/java-sdk-spring/src/test/java/kalix/spring/testmodels/eventsourcedentity/EventSourcedEntitiesTestModels.java, sdk/java-sdk-spring/src/test/scala/kalix/javasdk/impl/ActionDescriptorFactorySpec.scala, sdk/java-sdk-spring/src/test/scala/kalix/javasdk/impl/EventSourcedEntityDescriptorFactorySpec.scala, sdk/java-sdk-spring/src/test/scala/kalix/javasdk/impl/ViewDescriptorFactorySpec.scala, sdk/java-sdk-spring/src/test/scala/kalix/javasdk/impl/eventsourceentity/EventSourcedHandlersExtractorSpec.scala
My main motivation is that we want to migrate java sdk sample to Java 21, where we can fully embrace a sealed interface pattern-matching. Although is only about ES entity event handlers, we should promote this approach not only for ES but also for Views or any subscription that consumes all events because then the compiler will check if all cases are handled.
=> feat: single event handler for sealed interface

.github/labeler.yml
Our automatic release notes are a bit confusing at the moment (see below)... mostly, I think this is due to the fact that all changes to samples go under a specific sdk section. I think marking sample changes as documentation changes will help in this regard. (maybe it was like this previously actually)
=> ci: mark changes to samples as docs

sdk/java-sdk-protobuf/src/main/java/kalix/javasdk/Metadata.java, sdk/java-sdk-protobuf/src/main/java/kalix/javasdk/StatusCode.java, sdk/java-sdk-protobuf/src/main/scala/kalix/javasdk/impl/MetadataImpl.scala, sdk/java-sdk-protobuf/src/test/scala/kalix/javasdk/impl/MetadataImplSpec.scala, sdk/java-sdk-spring/src/it/java/com/example/wiring/SpringSdkIntegrationTest.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/ValueEntityIntegrationTest.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/actions/echo/EchoAction.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/valueentities/customer/CustomerEntity.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/valueentities/user/UserEntity.java, sdk/scala-sdk-protobuf/src/main/scala/kalix/scalasdk/Metadata.scala, sdk/scala-sdk-protobuf/src/main/scala/kalix/scalasdk/StatusCode.scala, sdk/scala-sdk-protobuf/src/main/scala/kalix/scalasdk/impl/MetadataImpl.scala
Refs https://github.com/lightbend/kalix-jvm-sdk/issues/1851
This is still very early draft version. I still have some questions to revisit:
- Should this go directly into Metadata or into something like ResponseCode (similar to CloudEvents and JwtClaims)?
- It could also go directly on the `reply` method (similar to the `error` that receives an error code), but maybe this way is better
- scala API
=> feat: provide http status code API

docs/src/modules/java-protobuf/pages/publishing-subscribing.adoc, docs/src/modules/java/pages/publishing-subscribing.adoc, sdk/java-sdk-protobuf/src/main/scala/kalix/javasdk/impl/DiscoveryImpl.scala, sdk/java-sdk-protobuf/src/main/scala/kalix/javasdk/impl/DocLinks.scala, sdk/java-sdk-protobuf/src/test/scala/kalix/javasdk/impl/DocLinksSpec.scala
Close https://github.com/lightbend/kalix-jvm-sdk/issues/1907
Close https://github.com/lightbend/kalix-jvm-sdk/issues/1313
This PR:
- updates lists for error code and categories with updated doc links
- introduces different URLs depending on which sdk is in use
=> chore: update docs links on errors

sdk/java-sdk-spring/src/it/java/com/example/wiring/SpringSdkIntegrationTest.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/actions/echo/EchoAction.java, sdk/java-sdk-spring/src/main/scala/kalix/javasdk/impl/ComponentDescriptor.scala
Fix https://github.com/lightbend/kalix-runtime/issues/1848
With this PR:
- Instead of this (timeout + 500):
```shell
➜ curl -i -XGET -H "Content-Type: application/json" localhost:9000/cart/
HTTP/1.1 500 Internal Server Error
Access-Control-Allow-Origin: *
Server: akka-http/10.6.0
Date: Tue, 16 Jan 2024 16:29:27 GMT
Content-Length: 0
```
- We get:
```shell
➜ curl -i -XGET -H "Content-Type: application/json" localhost:9000/cart/
HTTP/1.1 400 Bad Request
Access-Control-Allow-Origin: *
Server: akka-http/10.6.0
Date: Tue, 16 Jan 2024 16:28:37 GMT
Content-Type: text/plain; charset=UTF-8
Content-Length: 69
INVALID_ARGUMENT: Entity key field(s) List(cartId) must not be empty.% 
```
Note that, this does NOT change current behavior where for non-entity id fields, one is able to do calls without …
=> fix(java-sdk): enforce entity id presence on http calls

sdk/java-sdk-protobuf/src/main/java/kalix/javasdk/HttpResponse.java, sdk/java-sdk-protobuf/src/main/java/kalix/javasdk/JsonSupport.java, sdk/java-sdk-protobuf/src/main/java/kalix/javasdk/StatusCode.java, sdk/java-sdk-protobuf/src/main/scala/kalix/javasdk/impl/action/ActionEffectImpl.scala, sdk/java-sdk-protobuf/src/main/scala/kalix/javasdk/impl/workflow/WorkflowRouter.scala, sdk/java-sdk-spring/src/it/java/com/example/wiring/SpringSdkIntegrationTest.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/XComponentCallsIntegrationTest.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/actions/echo/ActionWithHttpResponse.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/actions/echo/EchoAction.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/actions/echo/Message.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/actions/echo/ShortenedEchoAction.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/workflowentities/SpringWorkflowIntegrationTest.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/workflowentities/TransferWorkflow.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/workflowentities/TransferWorkflowWithFraudDetection.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/workflowentities/TransferWorkflowWithoutInputs.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/workflowentities/WalletEntity.java, sdk/java-sdk-spring/src/main/scala/kalix/javasdk/impl/ComponentDescriptor.scala, sdk/java-sdk-spring/src/main/scala/kalix/javasdk/impl/JsonMessageCodec.scala, sdk/java-sdk-spring/src/main/scala/kalix/javasdk/impl/ProtoDescriptorGenerator.scala, sdk/java-sdk-spring/src/main/scala/kalix/spring/impl/RestKalixClientImpl.scala, sdk/java-sdk-spring/src/test/java/kalix/spring/testmodels/action/ActionsTestModels.java, sdk/java-sdk-spring/src/test/scala/kalix/javasdk/impl/ActionDescriptorFactorySpec.scala
=> feat: http response as endpoint return type

docs/src/modules/java/pages/publishing-subscribing.adoc, docs/src/modules/java/partials/pubsub-note.adoc
Adds note on how to configure brokers. 
This was missing only on the code-first SDK. Protobuf SDKs (jvm and js) have a similar note.
=> docs: add note on how to configure brokers

maven-java/kalix-maven-archetype-event-sourced-entity/src/main/resources/archetype-resources/pom.xml, maven-java/kalix-maven-archetype-value-entity/src/main/resources/archetype-resources/pom.xml
Alleging version with samples, otherwise, integration tests are failing.
=> fix: reverting maven-surefire-plugin and maven-failsafe-plugin versions bump

docs/config/validate-links.json
https://typesafe.slack.com/archives/CQUASEUDV/p1707820966805069
CI PRs are failing because site.mockito is down.
=> chore: avoiding validation site.mockito while is down

samples/java-spring-transfer-workflow-compensation/pom.xml, samples/java-spring-transfer-workflow/pom.xml
Accidentally broken in https://github.com/lightbend/kalix-jvm-sdk/pull/1428
Probably some copy from other samples.
=> fix: wrong FQCN in workflow samples

.github/release.yml
With this we should be able to remove the release-drafter workflow and still get the structured release notes.
=> chore: GH built-in release notes formatting

sdk/java-sdk-spring/src/main/java/kalix/javasdk/annotations/TypeName.java
Leftover from https://github.com/lightbend/kalix-jvm-sdk/pull/1562
We moved back to full-qualified class name but didn't change the javadoc for the TypeName annotation.
Also removed the word 'persisted' from the first line. It's not only about persisted events, but also events coming from a topic.
=> chore: update javadoc to reflect implementation

.github/publish-maven.sh
=> Publishing to Maven (Take 2)

.github/workflows/publish.yml
Docs publishing is about pushing docs to the `docs/kalix-current` branch.
https://github.com/lightbend/kalix-jvm-sdk/tree/docs/kalix-current
=> Token to use git commands for docs publishing

.github/publish-maven.sh
I'm not convinced this is the right path, but the profile name and the repository IDs were the same before. Also, this enables the `ossrh` profile as default additionally to `release`, enabled from the command line.
=> Maven publishing (Take 7)

.circleci/config.yml, .github/determine-sdk-version.sh, .github/publish-maven.sh, .github/workflows/publish.yml, .github/workflows/update-sdk-version.yml
- Add an empty CircleCI workflow (until this becomes part of `main`)
- Yet another take on SDK version extraction (Maven publish still failed with an invisible escape character)
=> Extracting the SDK version

.github/workflows/publish-docs.yml, .github/workflows/publish.yml
Docs are published on tag by pushing to the `docs/kalix-current` branch.
This requires `contents: write` permissions.
=> Docs publishing (on tag)

maven-java/pom.xml, publishLocally.sh
Release didn't work because we were adding the plugin twice and the second addition was overwriting the settings we needed.
=> fix: remove bogus plugin re-declaration

.github/workflows/ci.yml
Use a Node 20-based version.
References
- https://github.com/actions/setup-java/releases
=> bump: setup-java action 4.2.1

sbt-plugin/src/main/scala/kalix/sbt/KalixPlugin.scala
The Akka version should not be a exposed as a setting but just be a boring value.
References
- #2125
=> feat: expose underlying Akka version correctly

maven-java/kalix-java-protobuf-parent/pom.xml, maven-java/kalix-spring-boot-parent/pom.xml
On top of #2122 
Make it easy to build arm64 images. 
This will become more common when using multi-service tests with user service containers. 
Not yet documenting it, because my main goal for now is to have it in place to ease my own debugging.
=> feat: ease build for multi-platform images

maven-java/kalix-spring-boot-parent/pom.xml
To have the spring infra correctly packaged, we need the to correctly configure the spring-boot plugin.
This was previously done by the spring-parent pom. We need to do the same in our new parent pom.
=> fix: correctly configure spring-boot plugin

.github/workflows/ci.yml, samples/java-spring-tracing/.env, samples/java-spring-tracing/README.md, samples/java-spring-tracing/docker-compose.yml, samples/java-spring-tracing/pom.xml, samples/java-spring-tracing/src/it/java/com/example/IntegrationTest.java, samples/java-spring-tracing/src/it/resources/logback-test.xml, samples/java-spring-tracing/src/main/java/com/example/tracing/Main.java, samples/java-spring-tracing/src/main/java/com/example/tracing/api/GetRandomNameAction.java, samples/java-spring-tracing/src/main/java/com/example/tracing/api/GetRandomPhotoAction.java, samples/java-spring-tracing/src/main/java/com/example/tracing/api/RandomUserApi.java, samples/java-spring-tracing/src/main/java/com/example/tracing/api/UserEntity.java, samples/java-spring-tracing/src/main/java/com/example/tracing/domain/User.java, samples/java-spring-tracing/src/main/java/com/example/tracing/domain/UserEvent.java, samples/java-spring-tracing/src/main/resources/application.conf, samples/java-spring-tracing/src/main/resources/logback-dev-mode.xml, samples/java-spring-tracing/src/main/resources/logback.xml, samples/java-spring-tracing/src/test/resources/logback-test.xml, sdk/java-sdk-spring/src/main/java/kalix/javasdk/client/ActionCallBuilder.java, sdk/java-sdk-spring/src/main/java/kalix/javasdk/client/EventSourcedEntityCallBuilder.java, sdk/java-sdk-spring/src/main/java/kalix/javasdk/client/ValueEntityCallBuilder.java, sdk/java-sdk-spring/src/main/java/kalix/javasdk/client/ViewCallBuilder.java, sdk/java-sdk-spring/src/main/java/kalix/javasdk/client/WorkflowCallBuilder.java, sdk/java-sdk-spring/src/main/scala/kalix/javasdk/client/ComponentCall.scala, sdk/java-sdk-spring/src/main/scala/kalix/javasdk/impl/action/ReflectiveActionRouter.scala
Refs https://github.com/lightbend/kalix/issues/9415
This PR:
- ~adds a new `TraceContext` type that can be derived from the metadata (similar to `JwtClaims`)~
- ~adds support for automatic injection of an opentelemetry `Tracer` (similar to the injection of the `ComponentClient`) for easier custom child spans (i.e. tracking an external call or a specific local computation)~
- adds a new tracing sample with java sdk for exemplifying all things related with tracing in Kalix
- the sample uses a ESE for User management. A User is created with an email and then 2 actions generate a name and a photo respectively using an external API. 
- the idea would be for this sample to show the different bits of tracing, events, component calls, external calls, etc.
=> docs: add tracing sample for java sdk

maven-java/kalix-java-protobuf-parent/pom.xml, maven-java/kalix-spring-boot-parent/pom.xml
These should have been dropped when all Akka 24.05 releases were final.
=> fix: remove Akka snapshot repos

.github/workflows/samples-repo-sync.yml
As it turns out, we mirrored to totally wrong quickstart into the kalix-io org. 🤦 
References
- #1985 
- https://github.com/kalix-io/user-registry-choreography-saga/pull/6
- https://github.com/lightbend/kalix-jvm-sdk/tree/main/samples/java-spring-choreography-saga-quickstart
=> fix: mirror the correct example

.github/workflows/samples-repo-sync.yml
The new `.env` file need to be explicitly added to the PR.
Also bumps the pull request action to the current version.
References
- https://github.com/peter-evans/create-pull-request/releases
=> fix: keep .env during repo sync

.github/workflows/samples-repo-sync.yml
Explicitly copy `.env`.
References
- #2156
- #2157
=> fix: keep .env during repo sync 3

docs/release-issue-template.md
Redirect to the release notes after they where moved.
=> fix: redirect to the right file

maven-java/pom.xml
Kalix Runtime libraries are now being published to the akka-repository.
Refs
- https://github.com/lightbend/kalix-jvm-sdk/pull/2173
=> Add akka-repository for Maven dependencies and plugins

sdk/java-sdk-protobuf-testkit/src/test/scala/kalix/javasdk/testkit/impl/ActionResultSpec.scala, sdk/java-sdk-protobuf/src/main/java/kalix/javasdk/action/Action.java, sdk/java-sdk-protobuf/src/main/scala/kalix/javasdk/impl/action/ActionEffectImpl.scala, sdk/java-sdk-protobuf/src/main/scala/kalix/javasdk/impl/action/ActionsImpl.scala, sdk/java-sdk-spring/src/main/scala/kalix/javasdk/impl/action/ReflectiveActionRouter.scala
feat to automatially passing the traceparent in the metadata on 'reply' or 'asyncReply'
In the java-spring-eventsourced-counter (slightly modified, see modification* below) we were getting this if we didn't pass explicitly the metadata 
instead of the expected
*the `modification` involved to make the action`CounterCommandFromTopicAction` consume from the same topic that `CounterJournalToTopicAction` was publishing to, such when consuming events that would reply to the ESE that originated the event `CounterJournalToTopicAction` was consuming in the first place. There's no circularity here because the ESE was initially called with `increase` while the second call to the ESE was `multiply`.
=> feat: passing through metadata traceparent

.github/workflows/update-sdk-version.yml
This jobs haven't work for a while. See https://github.com/lightbend/kalix-jvm-sdk/actions/workflows/update-sdk-version.yml
For now I'd like to allow manual triggering and I added some debug logging for the next trigger from `Publish` event. 
Manual trigger was there before but it gets `skipped` each time I trigger it. Hence this PR.
=> fix: updating sdk version

docs/bin/deploy.sh
Attempt to fail the bash script if `git push` fails if no permissions.
=> fix(docs): fail deploy.sh on error in script

sdk/scala-sdk-protobuf/src/main/scala/kalix/scalasdk/impl/action/ActionAdapters.scala
https://github.com/lightbend/kalix-runtime/issues/2708
=> fix: getClientGrpc, back to originally leveraging `javaSdkContext`

sdk/java-sdk-protobuf/src/main/scala/kalix/javasdk/impl/DiscoveryImpl.scala
This reverts commit 119e48553aa309e25ea3073a9acf6912a85da48d.
The problem was probably that json log format wasn't used, and this is anyway not a complete solution for replacing newlines. For local development we want these messages to be readable.
=> Revert "fix: change format for logMessage mkString (#2219)"

codegen/core/src/main/scala/kalix/codegen/ModelBuilder.scala, docs/config/validate-links.json
To avoid `[WARNING] Using 'entity_type: "counter"' is deprecated, replace it with 'type_id: "counter"` on `mvn compile`
on the following .proto without `entity_type` defined.
```
service CounterService {
option (kalix.codegen) = {
value_entity: {
name: "com.westpac.domain.Counter"
type_id: "counter"
state: "com.westpac.domain.CounterState"
}
};
option (kalix.service).acl.allow = { principal: ALL };
rpc Increase(IncreaseValue) returns (google.protobuf.Empty);
rpc Decrease(DecreaseValue) returns (google.protobuf.Empty);
rpc Reset(ResetValue) returns (google.protobuf.Empty);
rpc GetCurrentCounter(GetCounter) returns (CurrentCounter);
}
```
=> chore: avoid wrong deprecation message

.github/workflows/fakepublish.yml, .github/workflows/update-sdk-version.yml
References
- https://typesafe.slack.com/archives/C02A6LVUZ/p1744209477985919
I would need this in main to be able to trigger `SDK version update` workflow in a branch. Since what we have in  this workflow  
``` 
workflow_run:
workflows: ["Publish"]
```
only would be triggered if `Publish` it's found in the default branch. Hence the `FakePublish`.
=> chore: first step to fix PR creation trigger

sdk/java-sdk-protobuf/src/main/resources/reference.conf
Not using virtual threads by default until jdk 25 is out, which fixes [this issue](https://openjdk.org/jeps/491).
Refs https://github.com/lightbend/kalix/issues/13949
=> chore: disable virtual threads by default

docs/Makefile
Checking other things I notices this refers to an old version of the docbuilder image.
=> chore: docbuiler image version
