lightbend/kalix-jvm-sdk

.circleci/config.yml, .circleci/google-pubsub-emulator-docker-compose.yml, RELEASING.md
Add the CI build. CircleCI should be all set up for testing this repo, and publishing/deploying on tags.
=> ci: add CircleCI configuration

samples/java-customer-registry/pom.xml, samples/java-eventing-shopping-cart/pom.xml, samples/java-pingpong/pom.xml, samples/java-valueentity-shopping-cart/pom.xml
updating pom to the latest and greatest
=> Maven: integration test config, and new repositories for akkasls

samples/java-valueentity-shopping-cart/pom.xml
Aligns with the new Counter sample.
=> fix: use com.example as groupId

.circleci/config.yml
On top of #12 to avoid merge merge conflict.
=> fix: include Counter sample to CI build

docs/Makefile
Already executed to be able to merge https://github.com/lightbend/akkaserverless-docs/pull/614
﻿
=> feature: add valueentity-counter to become available for docs

samples/java-eventsourced-shopping-cart/RELEASING.md, samples/java-eventsourced-shopping-cart/pom.xml, samples/java-valueentity-shopping-cart/RELEASING.md, samples/java-valueentity-shopping-cart/pom.xml
Explain how to build and publish the sample images.
Related to #17. We still need to decide if we will publish images on release and which version number the should have.
=> fix: adds instruction on how to publish the sample images

samples/valueentity-counter/src/test/java/com/example/domain/CounterTest.java
=> add tags to show in docs

samples/java-customer-registry/pom.xml, samples/java-eventing-shopping-cart/pom.xml, samples/java-eventsourced-shopping-cart/pom.xml, samples/java-valueentity-shopping-cart/pom.xml, samples/valueentity-counter/pom.xml
Try the latest Akka Serverless Maven plugin.﻿
=> update: Maven tooling 0.31.0

project/Dependencies.scala, sdk/src/main/scala/com/akkaserverless/javasdk/AkkaServerlessRunner.scala, sdk/src/main/scala/com/akkaserverless/javasdk/impl/DiscoveryImpl.scala
Ready for review, but keeping as draft until we have released protocol addition.
=> fix: Delay shutdown until proxy has terminated

.circleci/config.yml
References https://github.com/lightbend/akkaserverless-java-sdk/issues/9
=> build: cache .m2 repository

samples/java-valueentity-shopping-cart/src/main/proto/shoppingcart/shoppingcart_api.proto, samples/java-valueentity-shopping-cart/src/main/proto/shoppingcart/shoppingcart_domain.proto
Add Antora tags to source snippets for https://developer.lightbend.com/docs/akka-serverless/java/proto.html from validated Java SDK sources.
=> docs: tags for reference in proto.adoc

samples/java-valueentity-shopping-cart/src/main/proto/shoppingcart/shoppingcart_domain.proto
=> fix: correct end tag

build.sbt
=> Remove pingpong subproject from sbt

build.sbt, project/Common.scala, project/Dependencies.scala, project/plugins.sbt, sdk/src/main/resources/reference.conf
We can probably wait with merging until we have released a milestone proper for akka-grpc but let's see what PR validation has to say.
=> Update to latest akka-http / akka-grpc snapshots

.circleci/config.yml, samples/java-customer-registry/pom.xml, samples/java-eventing-shopping-cart/pom.xml, samples/java-eventsourced-shopping-cart/pom.xml, samples/java-valueentity-shopping-cart/pom.xml, samples/replicatedentity-counter/pom.xml, samples/valueentity-counter/pom.xml
Assuming this fixes #93 (though it's not entirely obvious
where that dependency is coming from)
=> ci: use maven plugin from build

samples/java-customer-registry/src/main/java/customer/CustomerValueEntity.java
Making the diff to
https://github.com/lightbend/akkaserverless-java-sdk/pull/73 smaller
=> Start updating CustomerValueEntity towards new API

codegen/java-gen/src/main/scala/com/lightbend/akkasls/codegen/java/ActionServiceSourceGenerator.scala, codegen/java-gen/src/main/scala/com/lightbend/akkasls/codegen/java/EntityServiceSourceGenerator.scala, codegen/java-gen/src/main/scala/com/lightbend/akkasls/codegen/java/SourceGenerator.scala, codegen/java-gen/src/main/scala/com/lightbend/akkasls/codegen/java/ViewServiceSourceGenerator.scala, codegen/java-gen/src/test/scala/com/lightbend/akkasls/codegen/java/ActionServiceSourceGeneratorSuite.scala, codegen/java-gen/src/test/scala/com/lightbend/akkasls/codegen/java/EntityServiceSourceGeneratorSuite.scala, codegen/java-gen/src/test/scala/com/lightbend/akkasls/codegen/java/SourceGeneratorSuite.scala, docs/src/modules/java/examples/archetype/first-service/src/main/java/com/example/domain/CounterImpl.java, docs/src/modules/java/examples/archetype/first-service/src/test/java/com/example/domain/CounterTest.java, docs/src/modules/java/pages/kickstart.adoc, docs/src/modules/java/pages/value-entity.adoc, maven-java/akkaserverless-maven-plugin/src/test/java/com/akkaserverless/GenerateMojoTest.java, samples/java-eventsourced-shopping-cart/src/main/java/com/example/shoppingcart/domain/ShoppingCart.java, samples/java-valueentity-shopping-cart/src/main/java/com/example/shoppingcart/domain/ShoppingCart.java, samples/replicatedentity-counter/src/main/java/com/example/MainComponentRegistrations2.java, samples/replicatedentity-counter/src/main/java/com/example/domain/Counter.java, samples/valueentity-counter/src/main/java/com/example/domain/Counter.java, samples/valueentity-counter/src/test/java/com/example/domain/CounterTest.java
From codegen and docs
also https://github.com/lightbend/akkaserverless-java-sdk/issues/42
=> Removing "Impl" Postfix to codegen classes

sdk/src/main/java/com/akkaserverless/javasdk/ComponentOptions.java, sdk/src/main/java/com/akkaserverless/javasdk/EntityOptions.java, sdk/src/main/java/com/akkaserverless/javasdk/replicatedentity/ReplicatedEntityOptions.java, sdk/src/main/java/com/akkaserverless/javasdk/valueentity/ValueEntityOptions.java, sdk/src/main/scala/com/akkaserverless/javasdk/AkkaServerlessRunner.scala, sdk/src/main/scala/com/akkaserverless/javasdk/impl/ComponentOptionsImpl.scala, sdk/src/main/scala/com/akkaserverless/javasdk/impl/DiscoveryImpl.scala, sdk/src/main/scala/com/akkaserverless/javasdk/impl/eventsourcedentity/EventSourcedEntitiesImpl.scala, sdk/src/main/scala/com/akkaserverless/javasdk/impl/eventsourcedentity/EventSourcedEntityOptionsImpl.scala, sdk/src/main/scala/com/akkaserverless/javasdk/impl/replicatedentity/ReplicatedEntityImpl.scala, sdk/src/main/scala/com/akkaserverless/javasdk/impl/replicatedentity/ReplicatedEntityOptionsImpl.scala, sdk/src/main/scala/com/akkaserverless/javasdk/impl/valueentity/ValueEntitiesImpl.scala, sdk/src/main/scala/com/akkaserverless/javasdk/impl/valueentity/ValueEntityOptionsImpl.scala
Depends on lightbend/akkaserverless-framework#727
=> fix: Per service header forward request 

publishLocalM2.sh
=> Add script to publish codegen and maven plugins locally

.circleci/config.yml, docs/src/modules/java/pages/eventsourced.adoc, docs/src/modules/java/partials/running-service-locally.adoc, maven-java/akkaserverless-maven-archetype-event-sourced-entity/pom.xml, maven-java/akkaserverless-maven-archetype-value-entity/pom.xml, maven-java/akkaserverless-maven-plugin/pom.xml, maven-java/pom.xml, samples/java-customer-registry/pom.xml, samples/java-eventing-shopping-cart/pom.xml, samples/java-eventsourced-shopping-cart/pom.xml, samples/java-valueentity-shopping-cart/pom.xml, samples/replicatedentity-counter/pom.xml, samples/valueentity-counter/pom.xml, updatePomVersions.sh
@raboof, this is another `main` merge so we get into the sdk branch the latest changes in `updatePomVersions` and CI config.
=> docs: removed hard-coded title - unneedd for this link

maven-java/pom.xml
=> Add maven metadata required by sonatype

docs/src/modules/java/pages/views.adoc, samples/java-customer-registry/src/main/proto/customer/customer_domain.proto, samples/java-customer-registry/src/main/proto/customer/customer_view.proto
Fixes #113. Submitting as a draft because I can't build and test this locally.
=> Full proto 113

samples/java-customer-registry/README.md, samples/java-customer-registry/pom.xml, samples/java-customer-registry/src/main/java/customer/CustomerEventSourcedEntity.java, samples/java-customer-registry/src/main/java/customer/CustomerValueEntity.java, samples/java-customer-registry/src/main/java/customer/CustomerView.java, samples/java-customer-registry/src/main/proto/customer/customer_api.proto, samples/java-customer-registry/src/main/proto/customer/customer_domain.proto, samples/java-customer-registry/src/main/proto/customer/customer_view.proto
Refs #125 and #189. Update the customer registry sample used for views with a change address command and address changed event, which is ignored by the views.
=> doc: update customer registry sample with ignored event for views

docs/src/modules/java/pages/index.adoc
Fixes #193 Related to feature: lightbend/akkaserverless-docs#813
=> feature: add link to support policy

CONTRIBUTING.md, README.md, maven-java/README.md, maven-java/akkaserverless-maven-archetype-event-sourced-entity/README.md, maven-java/akkaserverless-maven-archetype-value-entity/README.md, maven-java/akkaserverless-maven-plugin/README.md
Update readmes with more current information.﻿
=> chore: fixes and additions to readmes

RELEASING.md, docs/src/modules/java/examples/archetype/first-service/docker-compose.yml, docs/src/modules/java/examples/archetype/first-service/pom.xml, maven-java/akkaserverless-maven-archetype-event-sourced-entity/pom.xml, maven-java/akkaserverless-maven-archetype-event-sourced-entity/src/main/resources/archetype-resources/docker-compose.yml, maven-java/akkaserverless-maven-archetype-value-entity/pom.xml, maven-java/akkaserverless-maven-archetype-value-entity/src/main/resources/archetype-resources/docker-compose.yml, maven-java/akkaserverless-maven-plugin/pom.xml, maven-java/pom.xml, project/Dependencies.scala, samples/java-eventsourced-shopping-cart/docker-compose.yml, samples/java-valueentity-shopping-cart/docker-compose.yml, samples/replicatedentity-counter/docker-compose.yml, samples/valueentity-counter/docker-compose.yml, tck/src/test/java/com/akkaserverless/javasdk/tck/RunTck.java
Also update occurances to akkaserverless-jdk 0.7.0-beta.15 to 0.7.0-beta.18
to avoid confusion later.
=> Update proxy to 0.7.0-beta.15

codegen/core/src/main/scala/com/lightbend/akkasls/codegen/ModelBuilder.scala, codegen/core/src/main/scala/com/lightbend/akkasls/codegen/Packaging.scala, codegen/core/src/test/scala/com/lightbend/akkasls/codegen/ModelBuilderSuite.scala, codegen/java-gen/src/main/scala/com/lightbend/akkasls/codegen/java/SourceGenerator.scala, codegen/java-gen/src/test/scala/com/lightbend/akkasls/codegen/java/SourceGeneratorSuite.scala, codegen/java-gen/src/test/scala/com/lightbend/akkasls/codegen/java/TestData.scala, codegen/java-gen/src/test/scala/com/lightbend/akkasls/codegen/java/ViewServiceSourceGeneratorSuite.scala, docs/src/modules/java/pages/views.adoc, samples/java-customer-registry/src/main/java/customer/Main.java, samples/java-customer-registry/src/main/java/customer/view/CustomerByNameViewImpl.java
=> Avoid name clash between View and Akka gRPC interface

codegen/java-gen/src/main/scala/com/lightbend/akkasls/codegen/java/EntityServiceSourceGenerator.scala, codegen/java-gen/src/main/scala/com/lightbend/akkasls/codegen/java/SourceGenerator.scala, codegen/java-gen/src/main/scala/com/lightbend/akkasls/codegen/java/ValueEntitySourceGenerator.scala, codegen/java-gen/src/test/scala/com/lightbend/akkasls/codegen/java/EntityServiceSourceGeneratorSuite.scala, codegen/java-gen/src/test/scala/com/lightbend/akkasls/codegen/java/SourceGeneratorSuite.scala, codegen/java-gen/src/test/scala/com/lightbend/akkasls/codegen/java/ValueEntitySourceGeneratorSuite.scala, docs/src/modules/java/pages/value-entity.adoc, samples/java-customer-registry/src/main/java/customer/CustomerValueEntity.java, samples/java-customer-registry/src/main/java/customer/CustomerValueEntityProvider.java, samples/java-customer-registry/src/main/java/customer/Main.java, sdk/src/main/java/com/akkaserverless/javasdk/AkkaServerless.java, sdk/src/main/java/com/akkaserverless/javasdk/valueentity/ValueEntityProvider.java
@raboof, this another PR on top of #188 
It adds codegen using interpolation for the main class and the `MainComponentRegistrations` and it uses the Provider like in #180
The are many things to get fixed on this PR, but I won't have time to finalize it. So please, feel free to take it over.
=> feat: value entity registration with provider

CONTRIBUTING.md
To make the version kick in correctly.﻿
=> chore: correct property name in contributing instructions

samples/customer-registry-quickstart/src/main/proto/customer/customer_api.proto, samples/customer-registry-quickstart/src/main/proto/customer/customer_domain.proto, samples/customer-registry-quickstart/src/main/proto/customer/customer_view.proto
This allows us to include the proto files by section in the quickstart.
=> feature: add tags to proto files for quickstart

codegen/java-gen-compilation-tests/src/main/proto/views/user_view.proto, codegen/java-gen/src/main/scala/com/lightbend/akkasls/codegen/java/SourceGenerator.scala
This include a view file in `codegen/java-gen-compilation-tests`.
For the record, the `codegen/java-gen-compilation-tests` module runs the codegen against proto files, generate code and verify that it can be compiled.
=> include views to java-gen-compilation-tests

sdk/src/main/java/com/akkaserverless/javasdk/action/Action.java, sdk/src/main/java/com/akkaserverless/javasdk/eventsourcedentity/EventSourcedEntity.java, sdk/src/main/java/com/akkaserverless/javasdk/valueentity/ValueEntity.java, sdk/src/main/scala/com/akkaserverless/javasdk/impl/action/ActionHandler.scala, sdk/src/main/scala/com/akkaserverless/javasdk/impl/eventsourcedentity/EventSourcedEntitiesImpl.scala, sdk/src/main/scala/com/akkaserverless/javasdk/impl/eventsourcedentity/EventSourcedEntityHandler.scala, sdk/src/main/scala/com/akkaserverless/javasdk/impl/valueentity/ValueEntitiesImpl.scala, sdk/src/main/scala/com/akkaserverless/javasdk/impl/valueentity/ValueEntityEffectImpl.scala, sdk/src/main/scala/com/akkaserverless/javasdk/impl/valueentity/ValueEntityHandler.scala
* aligned with EventSourcedEntityHandler
* also Rename some public but internal methods in handler
=> Move state to ValueEntityHandler, needed for testkit

sdk/src/main/java/com/akkaserverless/javasdk/eventsourcedentity/EventSourcedEntity.java, sdk/src/main/scala/com/akkaserverless/javasdk/impl/eventsourcedentity/EventSourcedEntityEffectImpl.scala, sdk/src/main/scala/com/akkaserverless/javasdk/impl/eventsourcedentity/EventSourcedEntityHandler.scala, sdk/src/test/java/com/akkaserverless/javasdk/eventsourcedentity/AbstractCartEntity.java, sdk/src/test/java/com/akkaserverless/javasdk/eventsourcedentity/CartEntity.java, sdk/src/test/java/com/akkaserverless/javasdk/eventsourcedentity/CartEntityHandler.java, sdk/src/test/proto/eventsourcedentity/shoppingcart/shoppingcart_api.proto, sdk/src/test/scala/com/akkaserverless/javasdk/impl/AnySupportSpec.scala, sdk/src/test/scala/com/akkaserverless/javasdk/impl/eventsourcedentity/EventSourcedEntitiesImplSpec.scala
It was already implemented, but I added a test.
Fixes #116
=> Test emit of several events, #116

sdk/src/main/scala/com/akkaserverless/javasdk/impl/eventsourcedentity/EventSourcedEntityHandler.scala, sdk/src/main/scala/com/akkaserverless/javasdk/impl/valueentity/ValueEntityHandler.scala, sdk/src/main/scala/com/akkaserverless/javasdk/impl/view/ViewsImpl.scala
* not allowed to updateState to null in ValueEntity and View
* not allowed to return null from event handler in EventSourcedEntity
=> allow null as emptyState

samples/customer-registry-quickstart/src/main/resources/application.conf, samples/java-customer-registry/src/main/resources/application.conf, samples/java-eventing-shopping-cart/src/main/resources/application.conf, samples/java-eventsourced-customer-registry/src/main/resources/application.conf, samples/java-eventsourced-shopping-cart/src/main/resources/application.conf
* it is already the default from reference.conf
Fixes #210
=> remove log config from application.conf

maven-java/akkaserverless-maven-archetype-event-sourced-entity/src/main/resources/archetype-resources/pom.xml, maven-java/akkaserverless-maven-archetype-value-entity/src/main/resources/archetype-resources/pom.xml, project/Dependencies.scala, project/plugins.sbt
=> bump: akka-grpc 2.1.0

CONTRIBUTING.md, samples/java-valueentity-shopping-cart/README.md
=> Fix java value entity example.

maven-java/akkaserverless-maven-plugin/src/main/java/com/akkaserverless/GenerateMojo.java, samples/java-eventsourced-shopping-cart/README.md
=> Minor fix in README of java eventsourced shoppingcart example.

samples/java-eventsourced-customer-registry/src/main/java/customer/view/CustomerByNameView.java, samples/java-eventsourced-customer-registry/src/main/proto/customer/customer_view.proto
Refs #278 
- Added processing of address changes. Sample worked as expected otherwise.
=> Update java eventsourced customer registry

docs/README.md
Refs https://github.com/lightbend/akkaserverless-java-sdk/issues/279
=> Quick make docs

docs/src/modules/java/pages/value-entity.adoc, samples/valueentity-counter/pom.xml, samples/valueentity-counter/src/main/java/com/example/domain/Counter.java, sdk/src/main/java/com/akkaserverless/javasdk/valueentity/ValueEntity.java
=> Update value-entity.adoc and valueentity-counter sample, #222

docs/Makefile, docs/src/modules/java/pages/eventsourced.adoc, docs/src/modules/java/pages/value-entity.adoc, samples/java-eventsourced-shopping-cart/src/main/java/com/example/shoppingcart/domain/ShoppingCart.java, samples/java-eventsourced-shopping-cart/src/main/proto/shoppingcart/shoppingcart_api.proto, samples/java-eventsourced-shopping-cart/src/main/proto/shoppingcart/shoppingcart_domain.proto, samples/java-eventsourced-shopping-cart/src/main/resources/application.conf, samples/valueentity-counter/src/main/java/com/example/domain/Counter.java, samples/valueentity-counter/src/main/proto/value-entities/counter_api.proto
* align with value-entity.adoc
* switch to using the java-eventsourced-shopping-cart
instead of the java-eventing-shopping-cart
Refs #222
=> update eventsourced.adoc to new API and codgen, #222

docs/src/modules/java/examples/archetype/first-service/src/it/java/com/example/domain/CounterIntegrationTest.java, docs/src/modules/java/examples/archetype/first-service/src/main/java/com/example/Main.java, docs/src/modules/java/examples/archetype/first-service/src/main/java/com/example/domain/Counter.java, docs/src/modules/java/pages/kickstart.adoc, maven-java/akkaserverless-maven-archetype-event-sourced-entity/src/main/resources/archetype-resources/pom.xml, maven-java/akkaserverless-maven-archetype-value-entity/src/main/resources/archetype-resources/pom.xml, samples/customer-registry-quickstart/pom.xml, samples/java-eventing-shopping-cart/pom.xml, samples/java-eventsourced-customer-registry/pom.xml, samples/java-valueentity-customer-registry/pom.xml, samples/java-valueentity-shopping-cart/pom.xml, samples/replicatedentity-counter/pom.xml, samples/valueentity-counter/pom.xml
=> Update kickstart.adoc and pom files

docs/src/modules/java/pages/api.adoc
=> Update api.adoc, #222

docs/src/modules/developing/pages/development-process-java.adoc
=> Update development-process-java.adoc, #222

docs/src/modules/java/pages/views.adoc, samples/java-eventsourced-customer-registry/src/main/java/customer/Main.java, samples/java-eventsourced-customer-registry/src/main/java/customer/view/CustomerByNameView.java, samples/java-valueentity-customer-registry/src/main/java/customer/Main.java
=> Update views.adoc, #222

codegen/java-gen/src/main/scala/com/lightbend/akkasls/codegen/java/ActionServiceSourceGenerator.scala, codegen/java-gen/src/test/scala/com/lightbend/akkasls/codegen/java/ActionServiceSourceGeneratorSuite.scala
Noticed that Actions have unused imports. Some imports are only need if the proto has a stream method
=> conditionally include NotUsed and Source imports

samples/doc-snippets/src/main/java/com/example/json/JsonKeyValueMessage.java, sdk/src/main/java/com/akkaserverless/javasdk/JsonSupport.java, sdk/src/main/scala/com/akkaserverless/javasdk/impl/AnySupport.scala
Refs #324 
Need to verify with actual pub/sub, but pretty sure this is at least a part of the problem.
=> Fix for incorrect json encoding

docs/src/modules/java/pages/actions.adoc, docs/src/modules/java/pages/eventsourced.adoc, docs/src/modules/java/pages/value-entity.adoc
Follow up to review https://github.com/lightbend/akkaserverless-java-sdk/pull/318#discussion_r705224691 for the other components
=> docs: avoid double implement*, use handled

codegen/java-gen/src/main/scala/com/lightbend/akkasls/codegen/java/ActionServiceSourceGenerator.scala, codegen/java-gen/src/main/scala/com/lightbend/akkasls/codegen/java/ViewServiceSourceGenerator.scala, codegen/java-gen/src/test/scala/com/lightbend/akkasls/codegen/java/ActionServiceSourceGeneratorSuite.scala, codegen/java-gen/src/test/scala/com/lightbend/akkasls/codegen/java/ViewServiceSourceGeneratorSuite.scala, samples/valueentity-counter-generated/src/main/java/com/example/actions/DoubleCounterActionProvider.java, sdk/src/main/java/com/akkaserverless/javasdk/action/ActionProvider.java, sdk/src/main/java/com/akkaserverless/javasdk/view/ViewProvider.java, tck/src/main/java/com/akkaserverless/javasdk/tck/model/action/ActionTckModelBehaviorProvider.java, tck/src/main/java/com/akkaserverless/javasdk/tck/model/action/ActionTwoBehaviorProvider.java, tck/src/main/java/com/akkaserverless/javasdk/tck/model/localpersistenceeventing/LocalPersistenceSubscriberProvider.java, tck/src/main/java/com/akkaserverless/javasdk/tck/model/view/ViewTckModelBehaviorProvider.java
Add type params to ViewProvider and ActionProvider, same as other providers.
=> Add type params to ViewProvider and ActionProvider

docs/src/modules/java/examples/archetype/first-service/src/main/resources/logback.xml, docs/src/modules/java/pages/index.adoc, maven-java/akkaserverless-maven-archetype-event-sourced-entity/src/main/resources/archetype-resources/src/main/resources/logback.xml, maven-java/akkaserverless-maven-archetype-value-entity/src/main/resources/archetype-resources/src/main/resources/logback.xml, samples/customer-registry-quickstart/src/main/resources/logback.xml, samples/fibonacci-action/src/main/resources/logback.xml, samples/java-eventsourced-customer-registry/src/main/resources/logback.xml, samples/java-valueentity-customer-registry/src/main/resources/logback.xml, samples/replicatedentity-counter/src/main/resources/logback.xml, samples/valueentity-counter/src/main/resources/logback.xml
=> Cleanup json logging docs and don't prettyPrint, #307

docs/src/modules/java/pages/views.adoc, samples/java-eventsourced-customer-registry/src/main/java/customer/view/CustomerByNameView.java, samples/java-eventsourced-customer-registry/src/main/proto/customer/customer_api.proto, samples/java-eventsourced-customer-registry/src/main/proto/customer/customer_view.proto
Also a short note in the docs for where we use the same state type.
Refs #317
=> Avoid using the domain state type for the view in sample 

sdk/src/main/java/com/akkaserverless/javasdk/action/Action.java, sdk/src/main/scala/com/akkaserverless/javasdk/impl/action/ActionHandler.scala, tck/src/main/java/com/akkaserverless/javasdk/tck/model/action/ActionTckModelBehavior.java
=> Keep ActionContext in place to be accessed from other threads 

docs/Makefile, docs/src/modules/java/examples/testkit/java-eventsourced-shopping-cart/intarget/generated-test-sources/akkaserverless/com/example/shoppingcart/domain/ShoppingCartTestKit.java, docs/src/modules/java/pages/eventsourced.adoc, samples/java-eventsourced-shopping-cart/src/test/java/com/example/shoppingcart/domain/ShoppingCartTest.java
Some adjustments to https://github.com/lightbend/akkaserverless-java-sdk/pull/334 so that we can merge it.
=> Codegen testkit docs

docs/src/modules/java/pages/serialization.adoc
=> doc: fix link to JsonSupport javadoc

maven-java/akkaserverless-maven-archetype-event-sourced-entity/src/main/resources/archetype-resources/pom.xml, maven-java/akkaserverless-maven-archetype-value-entity/src/main/resources/archetype-resources/pom.xml, samples/customer-registry-quickstart/pom.xml, samples/doc-snippets/pom.xml, samples/fibonacci-action/pom.xml, samples/first-service/pom.xml, samples/java-eventing-shopping-cart/pom.xml, samples/java-eventsourced-customer-registry/pom.xml, samples/java-eventsourced-shopping-cart/pom.xml, samples/java-replicatedentity-shopping-cart/pom.xml, samples/java-valueentity-customer-registry/pom.xml, samples/java-valueentity-shopping-cart/pom.xml, samples/replicatedentity-counter/pom.xml, samples/replicatedentity-examples/pom.xml, samples/valueentity-counter/pom.xml
* in samples and archetype pom.xml
* the sdk library dependency was already on 2.1.0
=> bump: update akka-grpc to 2.1.0

tck/README.md
Refs https://github.com/lightbend/akkaserverless-framework/issues/688. Add a simple note on how to run the TCK, like for JavaScript SDK.
=> chore: add README for TCK implementation

RELEASING.md
https://github.com/lightbend/akkaserverless-java-sdk/pull/375#issuecomment-918825970
=> chore: add notes for releasing documentation hotfixes

project/Dependencies.scala, sdk/java-sdk/src/main/java/com/akkaserverless/javasdk/JsonSupport.java
* same defaults as in Akka Jackson serialization
* access to ObjectMapper for custom setup
Fixes #283
=> feat: setup good defaults for Jackson ObjectMapper, #283

docs/bin/bundle.sh
=> docs: remove base directory from quickstart bundles

codegen/java-gen/src/main/scala/com/lightbend/akkasls/codegen/java/ActionServiceSourceGenerator.scala, codegen/java-gen/src/test/scala/com/lightbend/akkasls/codegen/java/ActionServiceSourceGeneratorSuite.scala, sdk/java-sdk/src/main/java/com/akkaserverless/javasdk/action/ActionOptions.java, sdk/java-sdk/src/main/scala/com/akkaserverless/javasdk/impl/action/ActionOptionsImpl.scala, tck/src/main/java/com/akkaserverless/javasdk/tck/model/action/ActionTckModelBehaviorProvider.java, tck/src/main/java/com/akkaserverless/javasdk/tck/model/action/ActionTwoBehaviorProvider.java, tck/src/main/java/com/akkaserverless/javasdk/tck/model/localpersistenceeventing/LocalPersistenceSubscriberProvider.java
=> options for actions 

.circleci/config.yml, build.sbt, codegen/core/src/main/scala/com/lightbend/akkasls/codegen/Packaging.scala, codegen/core/src/test/scala/com/lightbend/akkasls/codegen/PackagingSuite.scala, codegen/scala-gen/src/main/scala/com/akkaserverless/codegen/scalasdk/AkkaserverlessGenerator.scala, codegen/scala-gen/src/main/scala/com/akkaserverless/codegen/scalasdk/AkkaserverlessTestGenerator.scala, codegen/scala-gen/src/main/scala/com/akkaserverless/codegen/scalasdk/AkkaserverlessUnmanagedGenerator.scala, codegen/scala-gen/src/main/scala/com/akkaserverless/codegen/scalasdk/impl/SourceGenerator.scala, codegen/scala-gen/src/main/scala/com/akkaserverless/codegen/scalasdk/impl/ValueEntitySourceGenerator.scala, codegen/scala-gen/src/test/scala/com/akkaserverless/codegen/scalasdk/SourceGeneratorSuite.scala, codegen/scala-gen/src/test/scala/com/akkaserverless/codegen/scalasdk/ValueEntitySourceGeneratorSuite.scala, sbt-plugin/src/main/scala/com/akkaserverless/sbt/AkkaserverlessPlugin.scala, sbt-plugin/src/sbt-test/sbt-akkaserverless/basic/build.sbt, sbt-plugin/src/sbt-test/sbt-akkaserverless/basic/src/main/protobuf/shoppingcart/shoppingcart_domain.proto, sbt-plugin/src/sbt-test/sbt-akkaserverless/basic/test
This is very incomplete (actually referring to the ScalaPB-generated types
or to the SDK is not there yet), but I thought it might be good to PR 
already to avoid double work or conflicts on the lower-level changes.
=> feat(codegen-scala): Scaffold empty ValueEntity implementation

sdk/java-sdk/src/main/java/com/akkaserverless/javasdk/impl/ViewFactory.java, sdk/java-sdk/src/main/java/com/akkaserverless/javasdk/view/View.java, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/AkkaServerless.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/MetadataContext.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/impl/view/ViewAdapter.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/impl/view/ViewHandler.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/impl/view/ViewUpdateEffectImpl.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/view/UpdateContext.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/view/View.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/view/ViewContext.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/view/ViewCreationContext.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/view/ViewProvider.scala, sdk/scala-sdk/src/test/proto/shoppingcart/shopping_cart_domain.proto, sdk/scala-sdk/src/test/proto/shoppingcart/shopping_cart_view_model.proto, sdk/scala-sdk/src/test/scala/com/akkaserverless/scalasdk/view/ShoppingCartViewServiceHandler.scala, sdk/scala-sdk/src/test/scala/com/akkaserverless/scalasdk/view/ShoppingCartViewServiceImpl.scala, sdk/scala-sdk/src/test/scala/com/akkaserverless/scalasdk/view/ShoppingCartViewServiceProvider.scala
* also an attempt of using adapters to/from javasdk
Refs #381
=> feat(scalasdk): Public API for Views, #381

sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/SideEffect.scala
not full impl, just so we can use this type when defining the new components Effects
=> feat: add SideEffect type placeholder for scalasdk

sdk/java-sdk/src/main/java/com/akkaserverless/javasdk/valueentity/ValueEntity.java, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/AkkaServerless.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/Context.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/EntityContext.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/EntityOptions.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/PassivationStrategy.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/ServiceCall.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/ServiceCallRef.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/SideEffect.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/impl/JavaServiceCallAdapter.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/impl/valueentity/ValueEntityAdapter.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/impl/valueentity/ValueEntityEffectImpl.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/impl/valueentity/ValueEntityHandler.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/valueentity/CommandContext.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/valueentity/ValueEntity.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/valueentity/ValueEntityContext.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/valueentity/ValueEntityOptions.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/valueentity/ValueEntityProvider.scala
First cut of Public API for Value Entities, lot's of wrapping and unwrapping.
=> feat!(scalasdk): Public API for Value Entities.

codegen/core/src/main/scala/com/lightbend/akkasls/codegen/ModelBuilder.scala, codegen/core/src/test/scala/com/lightbend/akkasls/codegen/ModelBuilderSuite.scala, codegen/core/src/test/scala/com/lightbend/akkasls/codegen/TestData.scala, codegen/core/src/test/scala/com/lightbend/akkasls/codegen/TestFullyQualifiedNameExtractor.scala, codegen/java-gen/src/main/scala/com/lightbend/akkasls/codegen/java/EntityServiceSourceGenerator.scala, codegen/java-gen/src/main/scala/com/lightbend/akkasls/codegen/java/FullyQualifiedNameExtractor.scala, codegen/java-gen/src/test/scala/com/lightbend/akkasls/codegen/java/ValueEntityTestKitGeneratorSuite.scala, codegen/scala-gen/src/main/scala/com/akkaserverless/codegen/scalasdk/FullyQualifiedNameExtractor.scala, codegen/scala-gen/src/main/scala/com/akkaserverless/codegen/scalasdk/impl/ValueEntitySourceGenerator.scala, codegen/scala-gen/src/test/scala/com/akkaserverless/codegen/scalasdk/FullyQualifiedNameExtractorSuite.scala, codegen/scala-gen/src/test/scala/com/akkaserverless/codegen/scalasdk/ValueEntitySourceGeneratorSuite.scala
The same probably needs to be applied to some of the other
components, and there's #437
=> feat(codegen-scala): correctly determine ValueEntity state package

codegen/java-gen/src/main/scala/com/lightbend/akkasls/codegen/java/ViewServiceSourceGenerator.scala, codegen/java-gen/src/test/scala/com/lightbend/akkasls/codegen/java/ViewServiceSourceGeneratorSuite.scala, sdk/java-sdk/src/main/java/com/akkaserverless/javasdk/view/ViewOptions.java, sdk/java-sdk/src/main/scala/com/akkaserverless/javasdk/impl/view/ViewOptionsImpl.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/impl/view/ViewAdapter.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/view/ViewOptions.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/view/ViewProvider.scala, tck/src/main/java/com/akkaserverless/javasdk/tck/model/view/ViewTckModelBehaviorProvider.java
=> fix: Missing options for Views added

samples/scala-fibonacci-action/build.sbt, samples/scala-value-entity-customer-registry/build.sbt
that's added automatically through
https://github.com/lightbend/akkaserverless-java-sdk/blob/main/codegen/scala-gen/src/main/scala/com/akkaserverless/codegen/scalasdk/AkkaserverlessGenerator.scala#L58
=> chore(scala-samples): remove sdk dependency

sdk/java-sdk/src/main/java/com/akkaserverless/javasdk/view/ViewOptions.java, sdk/java-sdk/src/main/scala/com/akkaserverless/javasdk/impl/view/ViewOptionsImpl.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/EntityOptions.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/action/ActionOptions.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/impl/ComponentOptions.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/impl/action/ActionAdapters.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/impl/valueentity/ValueEntityAdapter.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/impl/view/ViewAdapter.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/view/ViewOptions.scala
=> fix: add ComponentOptions for Scala SDK

codegen/java-gen/src/main/scala/com/lightbend/akkasls/codegen/java/ActionServiceSourceGenerator.scala, codegen/java-gen/src/main/scala/com/lightbend/akkasls/codegen/java/EventSourcedEntityTestKitGenerator.scala, codegen/java-gen/src/test/scala/com/lightbend/akkasls/codegen/java/ActionServiceSourceGeneratorSuite.scala, codegen/java-gen/src/test/scala/com/lightbend/akkasls/codegen/java/EventSourcedEntityTestKitGeneratorSuite.scala, proto-test-files/com/example/action/all_commands_api.proto
=> fix: Streaming out handlers did not compile 

project/Dependencies.scala, samples/scala-fibonacci-action/build.sbt, samples/scala-fibonacci-action/project/plugins.sbt, samples/scala-value-entity-customer-registry/build.sbt, samples/scala-value-entity-customer-registry/project/plugins.sbt, sbt-plugin/src/main/scala/com/akkaserverless/sbt/AkkaserverlessPlugin.scala, sbt-plugin/src/sbt-test/sbt-akkaserverless/basic/build.sbt
Will be useful later when we change the ServiceCall infrastructure to
use Akka gRPC as well
=> feat(sbt-plugin): automatically depend on Akka gRPC

build.sbt, project/Dependencies.scala, sdk/scala-sdk-testkit/src/main/scala/com/akkaserverless/scalasdk/testkit/ServiceCallDetails.scala, sdk/scala-sdk-testkit/src/main/scala/com/akkaserverless/scalasdk/testkit/ValueEntityResult.scala, testkit-java/src/main/java/com/akkaserverless/javasdk/testkit/EventSourcedResult.java
I have started on the codegen too, but PRed this first in case someone want to start with integration tests in parallel (in same testkit project)
Refs #372
=> feat(scalasdk): api for ValueEntity TestKit

codegen/scala-gen/src/main/scala/com/akkaserverless/codegen/scalasdk/impl/SourceGenerator.scala
I removed it initially in #483, but sending on a different PR since #483 is still broken.
=> fix: remove dummy foo/bar/baz

sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/AkkaServerless.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/AkkaServerlessRunner.scala
* and some cleanup in related area
=> chore(scalasdk): preferScalaProtobufs by default

sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/valueentity/ValueEntity.scala
=> chore: remove a ;

maven-java/akkaserverless-maven-archetype-event-sourced-entity/src/main/resources/archetype-resources/pom.xml, maven-java/akkaserverless-maven-archetype-value-entity/src/main/resources/archetype-resources/pom.xml, project/Dependencies.scala, samples/java-customer-registry-quickstart/pom.xml, samples/java-doc-snippets/pom.xml, samples/java-eventsourced-counter/pom.xml, samples/java-eventsourced-customer-registry/pom.xml, samples/java-eventsourced-shopping-cart/pom.xml, samples/java-fibonacci-action/pom.xml, samples/java-first-service/pom.xml, samples/java-replicatedentity-examples/pom.xml, samples/java-replicatedentity-shopping-cart/pom.xml, samples/java-shopping-cart-quickstart/pom.xml, samples/java-valueentity-counter/pom.xml, samples/java-valueentity-customer-registry/pom.xml, samples/java-valueentity-shopping-cart/pom.xml
=> feat: include logback dependencies in sdk

sdk/java-sdk/src/main/scala/com/akkaserverless/javasdk/impl/action/ActionsImpl.scala, sdk/java-sdk/src/test/scala/com/akkaserverless/javasdk/impl/action/ActionHandlerSpec.scala
=> fix: Turn thrown exception from user Action code into failure responses

.circleci/config.yml
=> chore: Verify unmanaged sources compile

codegen/scala-gen/src/main/scala/com/akkaserverless/codegen/scalasdk/impl/ValueEntitySourceGenerator.scala, codegen/scala-gen/src/test/scala/com/akkaserverless/codegen/scalasdk/ValueEntitySourceGeneratorSuite.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/SideEffect.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/impl/ComponentOptions.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/impl/ServiceCallAdapters.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/impl/Timeout.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/impl/action/ActionAdapters.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/impl/action/ActionEffectImpl.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/impl/action/ActionHandler.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/impl/action/MessageEnvelopeImpl.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/impl/valueentity/ValueEntityEffectImpl.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/impl/valueentity/ValueEntityHandler.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/impl/view/ViewHandler.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/impl/view/ViewUpdateEffectImpl.scala
=> chore(scalasdk): make a few more things internal

samples/java-customer-registry-quickstart/README.md
=> chore: better quickstart deploy instruction 

README.md, docs/src/modules/java/pages/index.adoc
=> docs(scalasdk): Developing with Java or Scala

codegen/java-gen/src/main/scala/com/lightbend/akkasls/codegen/java/EventSourcedEntityTestKitGenerator.scala, codegen/java-gen/src/main/scala/com/lightbend/akkasls/codegen/java/ValueEntityTestKitGenerator.scala, codegen/java-gen/src/test/scala/com/lightbend/akkasls/codegen/java/EventSourcedEntityTestKitGeneratorSuite.scala, codegen/java-gen/src/test/scala/com/lightbend/akkasls/codegen/java/ValueEntityTestKitGeneratorSuite.scala
* supposed to use static factory methods
=> chore(javasdk): make TestKit constructor private

sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/impl/action/ActionAdapters.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/impl/valueentity/ValueEntityAdapters.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/impl/view/ViewAdapters.scala
On top of #539.
Just some clean-up and name alignment. 
I'm finding it particular hard (and boring) to read the adapters code. It's becoming a soup of letters. So, I'm trying to add some breaklines to split things in pieces and help on the reading[^1]. 
[^1]: maybe it's just me getting old (also taking the opportunity to try footnotes 😄 )
=> chore: some formatting and name alignment in adapters

build.sbt
=> chore(scala-sdk): no java generation in scala sdk project

sdk/java-sdk/src/main/java/com/akkaserverless/javasdk/eventsourcedentity/EventSourcedEntity.java, sdk/java-sdk/src/main/scala/com/akkaserverless/javasdk/impl/eventsourcedentity/EventSourcedEntityEffectImpl.scala, sdk/java-sdk/src/main/scala/com/akkaserverless/javasdk/impl/eventsourcedentity/EventSourcedEntityHandler.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/AkkaServerless.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/eventsourcedentity/CommandContext.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/eventsourcedentity/EventContext.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/eventsourcedentity/EventSourcedEntity.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/eventsourcedentity/EventSourcedEntityContext.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/eventsourcedentity/EventSourcedEntityOptions.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/eventsourcedentity/EventSourcedEntityProvider.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/impl/eventsourcedentity/EventSourcedEntityAdapters.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/impl/eventsourcedentity/EventSourcedEntityEffectImpl.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/impl/eventsourcedentity/EventSourcedEntityHandler.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/valueentity/ValueEntity.scala
Public Scala API for EventSourcedEntity.
=> feat(scalasdk): EventSourcedEntity Public API.

.circleci/config.yml, project/Common.scala
References #523
Starting point ~35 minutes
=> Speed up ci PR validation

docs/bin/bundle.sh
Resolves #552. Just sed replace the SDK version in both Java and Scala samples that are bundled.
I've also deployed the docs from this commit, which will be included in the next build for the main docs.
=> fix: update sdk version in quickstart bundles

.circleci/config.yml, codegen/core/src/main/scala/com/lightbend/akkasls/codegen/SourceGeneratorUtils.scala, codegen/scala-gen/src/main/scala/com/akkaserverless/codegen/scalasdk/impl/EventSourcedEntitySourceGenerator.scala, codegen/scala-gen/src/test/scala/com/akkaserverless/codegen/scalasdk/EventSourcedEntitySourceGeneratorSuite.scala, samples/scala-eventsourced-counter/.scalafmt.conf, samples/scala-eventsourced-counter/README.md, samples/scala-eventsourced-counter/build.sbt, samples/scala-eventsourced-counter/docker-compose.yml, samples/scala-eventsourced-counter/project/build.properties, samples/scala-eventsourced-counter/project/plugins.sbt, samples/scala-eventsourced-counter/src/main/proto/com/example/actions/counter_topic.proto, samples/scala-eventsourced-counter/src/main/proto/com/example/actions/counter_topic_sub.proto, samples/scala-eventsourced-counter/src/main/proto/com/example/counter_api.proto, samples/scala-eventsourced-counter/src/main/proto/com/example/domain/counter_domain.proto, samples/scala-eventsourced-counter/src/main/scala/com/example/Main.scala, samples/scala-eventsourced-counter/src/main/scala/com/example/actions/CounterJournalToTopicAction.scala, samples/scala-eventsourced-counter/src/main/scala/com/example/actions/CounterTopicSubscriptionAction.scala, samples/scala-eventsourced-counter/src/main/scala/com/example/domain/Counter.scala, samples/scala-valueentity-counter/.scalafmt.conf, samples/scala-valueentity-counter/src/main/scala/com/example/Main.scala, samples/scala-valueentity-counter/src/main/scala/com/example/actions/CounterStateSubscriptionAction.scala, samples/scala-valueentity-counter/src/main/scala/com/example/actions/DoubleCounterAction.scala, samples/scala-valueentity-counter/src/main/scala/com/example/domain/Counter.scala, samples/scala-valueentity-counter/src/test/scala/com/example/domain/CounterSpec.scala
Includes some fixes for scala event sourced entity (including https://github.com/lightbend/akkaserverless-java-sdk/pull/563 which you likely already reviewed).
=> Scala eventsourced counter example

.github/release-drafter.yml
=> chore: try file-based labeling

project/ReflectiveCodeGen.scala
=> chore: remove obsolete comment

docs/src/modules/java/pages/quickstart-template.adoc
References https://github.com/lightbend/akkaserverless-docs/issues/1026
=> docs: Embed Java video in project template page

samples/java-customer-registry-quickstart/.bundleignore, samples/java-customer-registry-views-quickstart/.bundleignore, samples/java-shopping-cart-quickstart/.bundleignore, samples/scala-customer-registry-quickstart/.bundleignore
* exclude all hidden such as .idea .DS_Store and such
* exclude dependency-reduced-pom.xml which is from image packaging
Refs https://github.com/lightbend/akkaserverless-docs/issues/1043
=> Exclude more files from quickstart bundles

sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/valueentity/ValueEntity.scala, tck/scala-tck/src/main/scala/akkaserverless/tck/model/TckService.scala, tck/scala-tck/src/main/scala/com/akkaserverless/tck/model/valueentity/ValueEntityConfiguredEntity.scala, tck/scala-tck/src/main/scala/com/akkaserverless/tck/model/valueentity/ValueEntityTckModelEntity.scala, tck/scala-tck/src/main/scala/com/akkaserverless/tck/model/valueentity/ValueEntityTwoEntity.scala, tck/scala-tck/src/test/java/com/akkaserverless/javasdk/tck/RunTck.java
This one currently fails the configuration tests. Is there anything needed to make that work or could that be a bug in the Scala SDK?
Refs #683
=> feat: Scala TCK value entity implementation

tck/scala-tck/src/main/scala/akkaserverless/tck/model/TckService.scala, tck/scala-tck/src/main/scala/com/akkaserverless/tck/model/eventsourcedentity/EventSourcedConfiguredEntity.scala, tck/scala-tck/src/main/scala/com/akkaserverless/tck/model/eventsourcedentity/EventSourcedTckModelEntity.scala, tck/scala-tck/src/main/scala/com/akkaserverless/tck/model/eventsourcedentity/EventSourcedTwoEntity.scala, tck/scala-tck/src/test/java/com/akkaserverless/javasdk/tck/RunTck.java
=> feat: Scala TCK for event-sourced entities

sbt-plugin/src/main/scala/com/akkaserverless/sbt/AkkaserverlessPlugin.scala
References #509
Manually verified that a deployed service built with this that has invalid views shows the right error message including the view query definition from the service descriptor 👍
=> fix: Include service descriptor file in scala images 

docs/src/modules/java/pages/index.adoc
=> docs: Update Scala SDK support tier

codegen/core/src/main/scala/com/lightbend/akkasls/codegen/ModelBuilder.scala, codegen/core/src/main/scala/com/lightbend/akkasls/codegen/Packaging.scala, codegen/core/src/main/scala/com/lightbend/akkasls/codegen/SourceGeneratorUtils.scala, codegen/java-gen/src/main/scala/com/lightbend/akkasls/codegen/java/JavaGeneratorUtils.scala, codegen/java-gen/src/main/scala/com/lightbend/akkasls/codegen/java/Types.scala, codegen/java-gen/src/main/scala/com/lightbend/akkasls/codegen/java/ViewServiceSourceGenerator.scala, codegen/java-gen/src/test/scala/com/lightbend/akkasls/codegen/java/ViewServiceSourceGeneratorSuite.scala, codegen/scala-gen/src/main/scala/com/akkaserverless/codegen/scalasdk/impl/ActionServiceSourceGenerator.scala, codegen/scala-gen/src/main/scala/com/akkaserverless/codegen/scalasdk/impl/ScalaGeneratorUtils.scala
Refs #656
Part of my View problems in the TCK are again related to naming problems, so I started fixing this here.
=> Convert Java View code generation to new style

docs/src/modules/java/pages/actions-as-controller.adoc
=> Add a 's' to Controller

sdk/java-sdk/src/main/java/com/akkaserverless/javasdk/JwtClaims.java, sdk/java-sdk/src/main/java/com/akkaserverless/javasdk/Metadata.java, sdk/java-sdk/src/main/scala/com/akkaserverless/javasdk/impl/MetadataImpl.scala, sdk/java-sdk/src/test/scala/com/akkaserverless/javasdk/impl/MetadataImplSpec.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/JwtClaims.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/Metadata.scala, sdk/scala-sdk/src/main/scala/com/akkaserverless/scalasdk/impl/MetadataImpl.scala
This provides convenient access to JWT claim metadata.
=> feat: JWT claim metadata

build.sbt, sbt-plugin/src/main/scala/com/akkaserverless/sbt/AkkaserverlessPlugin.scala
This will help me a lot while working on #739
=> chore: add framework protocol to BuildInfo

samples/scala-doc-snippets/build.sbt, samples/scala-eventsourced-counter/build.sbt, samples/scala-eventsourced-customer-registry/build.sbt, samples/scala-eventsourced-shopping-cart/build.sbt, samples/scala-fibonacci-action/build.sbt, samples/scala-first-service/build.sbt, samples/scala-replicatedentity-examples/build.sbt, samples/scala-replicatedentity-shopping-cart/build.sbt, samples/scala-valueentity-counter/build.sbt, samples/scala-valueentity-customer-registry/build.sbt, samples/scala-valueentity-shopping-cart/build.sbt
Based on note in forums: https://discuss.lightbend.com/t/sbt-deploy-does-not-automatically-tag-docker-image-with-latest/9252
=> chore: Update latest tag when publishing to docker in Scala samples

build.sbt, codegen/java-gen/src/test/resources/tests/README.md, codegen/java-gen/src/test/resources/tests/action-service/generated-managed/com/example/service/AbstractMyServiceAction.java, codegen/java-gen/src/test/resources/tests/action-service/generated-managed/com/example/service/MyServiceActionProvider.java, codegen/java-gen/src/test/resources/tests/action-service/generated-managed/com/example/service/MyServiceActionRouter.java, codegen/java-gen/src/test/resources/tests/action-service/generated-managed/org/example/AkkaServerlessFactory.java, codegen/java-gen/src/test/resources/tests/action-service/generated-managed/org/example/Components.java, codegen/java-gen/src/test/resources/tests/action-service/generated-managed/org/example/ComponentsImpl.java, codegen/java-gen/src/test/resources/tests/action-service/generated-test-managed/com/example/service/MyServiceActionTestKit.java, codegen/java-gen/src/test/resources/tests/action-service/generated-test-unmanaged/com/example/service/MyServiceActionTest.java, codegen/java-gen/src/test/resources/tests/action-service/generated-unmanaged/com/example/service/MyServiceAction.java, codegen/java-gen/src/test/resources/tests/action-service/generated-unmanaged/org/example/Main.java, codegen/java-gen/src/test/resources/tests/action-service/proto/example-action.proto, codegen/java-gen/src/test/scala/com/lightbend/akkasls/codegen/java/ExampleSuite.scala, project/Common.scala
See the new README.md for a description.
=> chore: add round-trip tests for code-generation (Java)

docs/bin/deploy.sh
To make it easier to follow how this all fits together
=> chore(docs): better automated commit message

docs/Makefile, docs/src/modules/java/pages/quickstart/cr-value-entity-java.adoc, docs/src/modules/java/pages/quickstart/cr-value-entity-scala.adoc, docs/src/modules/java/pages/quickstart/cr-value-entity-views-java.adoc, docs/src/modules/java/pages/quickstart/sc-eventsourced-entity-java.adoc, samples/java-customer-registry-quickstart/src/main/proto/customer/api/customer_api.proto, samples/java-customer-registry-quickstart/src/main/proto/customer/domain/customer_domain.proto, samples/java-customer-registry-views-quickstart/src/main/proto/customer/api/customer_api.proto, samples/java-customer-registry-views-quickstart/src/main/proto/customer/domain/customer_domain.proto, samples/java-customer-registry-views-quickstart/src/main/proto/customer/view/customer_view.proto, samples/java-shopping-cart-quickstart/src/main/proto/shopping/cart/api/shopping_cart_api.proto, samples/java-shopping-cart-quickstart/src/main/proto/shopping/cart/domain/shopping_cart_domain.proto, samples/scala-customer-registry-quickstart/src/main/proto/customer/api/customer_api.proto, samples/scala-customer-registry-quickstart/src/main/proto/customer/domain/customer_domain.proto, samples/scala-customer-registry-quickstart/src/main/proto/customer/view/customer_view.proto
=> chore: move quickstart pages

codegen/java-gen/src/test/resources/tests/action-service/named-new-style/generated-managed/org/example/AkkaServerlessFactory.java, codegen/java-gen/src/test/resources/tests/action-service/named-new-style/generated-managed/org/example/Components.java, codegen/java-gen/src/test/resources/tests/action-service/named-new-style/generated-managed/org/example/ComponentsImpl.java, codegen/java-gen/src/test/resources/tests/action-service/named-new-style/generated-managed/org/example/service/AbstractMyServiceNamedAction.java, codegen/java-gen/src/test/resources/tests/action-service/named-new-style/generated-managed/org/example/service/MyServiceNamedActionProvider.java, codegen/java-gen/src/test/resources/tests/action-service/named-new-style/generated-managed/org/example/service/MyServiceNamedActionRouter.java, codegen/java-gen/src/test/resources/tests/action-service/named-new-style/generated-test-managed/org/example/service/MyServiceNamedActionTestKit.java, codegen/java-gen/src/test/resources/tests/action-service/named-new-style/generated-test-unmanaged/org/example/service/MyServiceNamedActionTest.java, codegen/java-gen/src/test/resources/tests/action-service/named-new-style/generated-unmanaged/org/example/Main.java, codegen/java-gen/src/test/resources/tests/action-service/named-new-style/generated-unmanaged/org/example/service/MyServiceNamedAction.java, codegen/java-gen/src/test/resources/tests/action-service/named-new-style/proto/example-action.proto, codegen/java-gen/src/test/resources/tests/action-service/simple-new-style/proto/example-action.proto
~Draft because on top of #774 because it requires the fix for #761.~
~Ready for review otherwise.~
=> chore: ExampleSuite tests for named action (new codegen)

codegen/core/src/main/scala/com/lightbend/akkasls/codegen/ModelBuilder.scala, codegen/core/src/test/scala/com/lightbend/akkasls/codegen/ModelBuilderSuite.scala
This is just some clean-up. 
The tests were duplicated but only one single line was different between then.
=> chore: reduce test duplication

maven-java/akkaserverless-maven-archetype-event-sourced-entity/src/main/resources/archetype-resources/docker-compose.yml, maven-java/akkaserverless-maven-archetype-value-entity/src/main/resources/archetype-resources/docker-compose.yml
=> chore: wrap whole docker-compose with Velocity escaping

samples/java-eventsourced-customer-registry/README.md, samples/java-first-service/README.md, samples/java-valueentity-customer-registry/README.md
=> Update instructions for samples

maven-java/akkaserverless-maven-archetype-event-sourced-entity/src/main/resources/archetype-resources/pom.xml, maven-java/akkaserverless-maven-archetype-value-entity/src/main/resources/archetype-resources/pom.xml, samples/java-customer-registry-quickstart/pom.xml, samples/java-customer-registry-views-quickstart/pom.xml, samples/java-doc-snippets/pom.xml, samples/java-eventsourced-counter/pom.xml, samples/java-eventsourced-customer-registry/pom.xml, samples/java-eventsourced-shopping-cart/pom.xml, samples/java-fibonacci-action/pom.xml, samples/java-first-service/pom.xml, samples/java-replicatedentity-examples/pom.xml, samples/java-replicatedentity-shopping-cart/pom.xml, samples/java-shopping-cart-quickstart/pom.xml, samples/java-valueentity-counter/pom.xml, samples/java-valueentity-customer-registry/pom.xml, samples/java-valueentity-shopping-cart/pom.xml
https://typesafe.slack.com/archives/C01FDELQMGR/p1643193193198700
=> bump protoc in samples to e.g. get support for optionals

docs/src/modules/java/pages/writing-grpc-descriptors-protobuf.adoc
=> docs: generated entity keys

.circleci/config.yml
Follow up to #822 
Ping @raboof
=> chore: Verify protoc versions in samples and archetypes

codegen/scala-gen/src/main/scala/com/akkaserverless/codegen/scalasdk/AbstractAkkaserverlessGenerator.scala, codegen/scala-gen/src/main/scala/com/akkaserverless/codegen/scalasdk/AkkaserverlessGenerator.scala, codegen/scala-gen/src/main/scala/com/akkaserverless/codegen/scalasdk/AkkaserverlessTestGenerator.scala, codegen/scala-gen/src/main/scala/com/akkaserverless/codegen/scalasdk/AkkaserverlessUnmanagedGenerator.scala, codegen/scala-gen/src/main/scala/com/akkaserverless/codegen/scalasdk/AkkaserverlessUnmanagedTestGenerator.scala
It doesn't seem like we need to treat them specially, we can just 'say' we support them.
I'm not sure we need to do anything at the Maven side, will check that next.
=> feat(sbt-plugin): announce support for proto3 optional fields

.circleci/config.yml
Got some mail saying we need to do this before May.
=> chore: Upgrade Circle-CI image to supported version

project/Dependencies.scala
* and Scala 2.13.8
* and Logback 1.2.9
=> bump: Akka HTTP 10.2.8, Akka 2.6.18

.circleci/config.yml, sdk/java-sdk-testkit/src/main/java/com/akkaserverless/javasdk/testkit/AkkaServerlessProxyContainer.java
Missed this use of testcontainers earlier...
References #974
=> fix(local-proxy): avoid telemetry from our CI

samples/java-eventsourced-shopping-cart/src/main/java/com/example/shoppingcart/Main.java, samples/java-valueentity-customer-registry/src/main/java/customer/Main.java, samples/scala-valueentity-customer-registry/src/main/scala/customer/Main.scala
Explicitly set the view ids for the ones that get to long ids autogenerated
=> Workaround sample view

maven-java/akkaserverless-maven-archetype-event-sourced-entity/src/main/resources/archetype-resources/docker-compose.yml, maven-java/akkaserverless-maven-archetype-value-entity/src/main/resources/archetype-resources/docker-compose.yml, project/Dependencies.scala, samples/java-customer-registry-kafka-quickstart/docker-compose.yml, samples/java-customer-registry-kafka-quickstart/kafka/docker-compose.yml, samples/java-customer-registry-quickstart/docker-compose.yml, samples/java-customer-registry-views-quickstart/docker-compose.yml, samples/java-eventsourced-counter/docker-compose.yml, samples/java-eventsourced-shopping-cart/docker-compose.yml, samples/java-fibonacci-action/docker-compose.yml, samples/java-first-service/docker-compose.yml, samples/java-replicatedentity-examples/docker-compose.yml, samples/java-replicatedentity-shopping-cart/docker-compose.yml, samples/java-shopping-cart-quickstart/docker-compose.yml, samples/java-valueentity-counter/docker-compose.yml, samples/java-valueentity-customer-registry/docker-compose.yml, samples/java-valueentity-shopping-cart/docker-compose.yml, samples/scala-customer-registry-quickstart/docker-compose.yml, samples/scala-eventsourced-counter/docker-compose.yml, samples/scala-eventsourced-customer-registry/docker-compose.yml, samples/scala-eventsourced-shopping-cart/docker-compose.yml, samples/scala-fibonacci-action/docker-compose.yml, samples/scala-first-service/docker-compose.yml, samples/scala-replicatedentity-examples/docker-compose.yml, samples/scala-replicatedentity-shopping-cart/docker-compose.yml, samples/scala-valueentity-counter/docker-compose.yml, samples/scala-valueentity-customer-registry/docker-compose.yml, samples/scala-valueentity-shopping-cart/docker-compose.yml, sbt-plugin/src/main/scala/kalix/sbt/KalixPlugin.scala
which is under the new groupId
=> rename: bump: framework 0.10.0-M4

docs/Makefile
This is now good to go. Image is published.
=> rename: update antora docbuilder image

CONTRIBUTING.md, README.md, codegen/java-gen/src/test/resources/tests/README.md, codegen/scala-gen/src/test/resources/tests/README.md, maven-java/kalix-maven-archetype-event-sourced-entity/README.md, maven-java/kalix-maven-archetype-event-sourced-entity/src/main/resources/archetype-resources/README.md, maven-java/kalix-maven-archetype-value-entity/README.md, maven-java/kalix-maven-archetype-value-entity/src/main/resources/archetype-resources/README.md, maven-java/kalix-maven-plugin/README.md, samples/java-customer-registry-kafka-quickstart/README.md, samples/java-customer-registry-quickstart/README.md, samples/java-customer-registry-views-quickstart/README.md, samples/java-eventsourced-counter/README.md, samples/java-eventsourced-shopping-cart/README.md, samples/java-fibonacci-action/README.md, samples/java-first-service/README.md, samples/java-replicatedentity-shopping-cart/README.md, samples/java-shopping-cart-quickstart/README.md, samples/java-valueentity-counter/README.md, samples/java-valueentity-shopping-cart/README.md, samples/scala-customer-registry-quickstart/README.md, samples/scala-eventsourced-counter/README.md, samples/scala-eventsourced-customer-registry/README.md, samples/scala-eventsourced-shopping-cart/README.md, samples/scala-fibonacci-action/README.md, samples/scala-first-service/README.md, samples/scala-replicatedentity-shopping-cart/README.md, samples/scala-valueentity-counter/README.md, samples/scala-valueentity-customer-registry/README.md, samples/scala-valueentity-shopping-cart/README.md
Changes the several README files we have
=> rename: markdown files

docs/Makefile
refs https://github.com/lightbend/akkaserverless/issues/6433
=> rename: deploy to doc/kalix-current

docs/src/modules/java/pages/views.adoc
Refs https://github.com/lightbend/kalix-proxy/issues/1335.
Add simple docs for some of the new features for views. Only targeted at `kalix-main` as these will be in the Kalix proxy.
=> docs: new view features

docs/src/modules/java/pages/views.adoc
References https://github.com/lightbend/kalix-proxy/issues/1341
=> docs: Cover optional fields in views

samples/java-eventsourced-shopping-cart/pom.xml, samples/java-valueentity-shopping-cart/pom.xml
as promised in https://docs.kalix.io/quickstart/prebuilt-samples.html#_deploying_the_sample
=> chore(samples): manually pushed updated samples

sdk/java-sdk/src/main/scala/kalix/javasdk/impl/DocLinks.scala
=> chore: fix error prefix and add JWT

maven-java/kalix-maven-archetype-event-sourced-entity/README.md, maven-java/kalix-maven-archetype-event-sourced-entity/src/main/resources/archetype-resources/README.md, maven-java/kalix-maven-archetype-value-entity/README.md, maven-java/kalix-maven-archetype-value-entity/src/main/resources/archetype-resources/README.md, samples/java-customer-registry-kafka-quickstart/README.md, samples/java-customer-registry-quickstart/README.md, samples/java-customer-registry-views-quickstart/README.md, samples/java-eventsourced-counter/README.md, samples/java-eventsourced-customer-registry/README.md, samples/java-eventsourced-shopping-cart/README.md, samples/java-fibonacci-action/README.md, samples/java-first-service/README.md, samples/java-replicatedentity-shopping-cart/README.md, samples/java-shopping-cart-quickstart/README.md, samples/java-valueentity-counter-spring-client/README.md, samples/java-valueentity-counter/README.md, samples/java-valueentity-customer-registry/README.md, samples/java-valueentity-shopping-cart/README.md, samples/scala-customer-registry-quickstart/README.md, samples/scala-eventsourced-counter/README.md, samples/scala-eventsourced-customer-registry/README.md, samples/scala-eventsourced-shopping-cart/README.md, samples/scala-fibonacci-action/README.md, samples/scala-first-service/README.md, samples/scala-replicatedentity-shopping-cart/README.md, samples/scala-valueentity-counter/README.md, samples/scala-valueentity-customer-registry/README.md, samples/scala-valueentity-shopping-cart/README.md
Fixes links into the docs and https://github.com/lightbend/kalix-docs/issues/1189
=> links and things in readmes for samples

samples/scala-customer-registry-quickstart/build.sbt, samples/scala-doc-snippets/build.sbt, samples/scala-eventsourced-counter/build.sbt, samples/scala-eventsourced-customer-registry/build.sbt, samples/scala-eventsourced-shopping-cart/build.sbt, samples/scala-fibonacci-action/build.sbt, samples/scala-first-service/build.sbt, samples/scala-replicatedentity-examples/build.sbt, samples/scala-replicatedentity-shopping-cart/build.sbt, samples/scala-valueentity-counter/build.sbt, samples/scala-valueentity-customer-registry/build.sbt, samples/scala-valueentity-shopping-cart/build.sbt
References #78
A somewhat sketchy solution, but seems to work so maybe worth it?
If we decide it is, needs to be applied to all samples and the quickstart g8 template.
=> feat(scala): Support for building Kalix images on Mac m1 #78

.circleci/config.yml
=> chore: re-enable doc links checking

.circleci/config.yml, docs/src/modules/java/pages/quickstart/cr-value-entity-kafka-java.adoc
Fixes https://github.com/lightbend/kalix/issues/6608
=> fix: show grpcurl instead of service explorer

samples/java-eventsourced-shopping-cart/src/main/java/com/example/shoppingcart/Main.java, samples/java-valueentity-customer-registry/src/main/java/customer/Main.java, samples/scala-valueentity-customer-registry/src/main/scala/customer/Main.scala
* Reverts https://github.com/lightbend/akkaserverless-java-sdk/pull/866
* Release this after https://github.com/lightbend/kalix-proxy/pull/1370
=> fix: Remove view id length restriction

codegen/scala-gen/src/main/scala/kalix/codegen/scalasdk/impl/ActionTestKitGenerator.scala, codegen/scala-gen/src/main/scala/kalix/codegen/scalasdk/impl/EventSourcedEntityTestKitGenerator.scala, codegen/scala-gen/src/main/scala/kalix/codegen/scalasdk/impl/ValueEntityTestKitGenerator.scala, codegen/scala-gen/src/test/resources/tests/action-service/named-new-style/generated-test-unmanaged/org/example/service/MyServiceNamedActionSpec.scala, codegen/scala-gen/src/test/resources/tests/action-service/simple-new-style/generated-test-unmanaged/org/example/service/MyServiceActionSpec.scala, codegen/scala-gen/src/test/resources/tests/action-service/simple-old-style/generated-test-unmanaged/org/example/service/MyServiceActionSpec.scala, codegen/scala-gen/src/test/resources/tests/action-service/with-action-in-name/generated-test-unmanaged/org/example/service/MyServiceActionImplSpec.scala, codegen/scala-gen/src/test/resources/tests/event-sourced-entity/absolute-packages/generated-test-unmanaged/org/example/domain/CounterSpec.scala, codegen/scala-gen/src/test/resources/tests/event-sourced-entity/absolute-packages/generated-test-unmanaged/org/example/eventsourcedentity/CounterServiceIntegrationSpec.scala, codegen/scala-gen/src/test/resources/tests/event-sourced-entity/domain-in-service-package/generated-test-unmanaged/org/example/eventsourcedentity/CounterServiceIntegrationSpec.scala, codegen/scala-gen/src/test/resources/tests/event-sourced-entity/domain-in-service-package/generated-test-unmanaged/org/example/eventsourcedentity/CounterSpec.scala, codegen/scala-gen/src/test/resources/tests/event-sourced-entity/named-new-style/generated-test-unmanaged/org/example/eventsourcedentity/CounterServiceIntegrationSpec.scala, codegen/scala-gen/src/test/resources/tests/event-sourced-entity/named-new-style/generated-test-unmanaged/org/example/eventsourcedentity/domain/CounterSpec.scala, codegen/scala-gen/src/test/resources/tests/event-sourced-entity/state-events-in-different-pacakge/generated-test-unmanaged/org/example/eventsourcedentity/CounterServiceIntegrationSpec.scala, codegen/scala-gen/src/test/resources/tests/event-sourced-entity/state-events-in-different-pacakge/generated-test-unmanaged/org/example/eventsourcedentity/domain/CounterSpec.scala, codegen/scala-gen/src/test/resources/tests/event-sourced-entity/unnamed-new-style/generated-test-unmanaged/org/example/eventsourcedentity/CounterServiceEntitySpec.scala, codegen/scala-gen/src/test/resources/tests/event-sourced-entity/unnamed-new-style/generated-test-unmanaged/org/example/eventsourcedentity/CounterServiceIntegrationSpec.scala, codegen/scala-gen/src/test/resources/tests/value-entity/absolute-packages/generated-test-unmanaged/org/example/domain/CounterSpec.scala, codegen/scala-gen/src/test/resources/tests/value-entity/absolute-packages/generated-test-unmanaged/org/example/valueentity/CounterServiceIntegrationSpec.scala, codegen/scala-gen/src/test/resources/tests/value-entity/domain-in-service-package/generated-test-unmanaged/org/example/valueentity/CounterServiceIntegrationSpec.scala, codegen/scala-gen/src/test/resources/tests/value-entity/domain-in-service-package/generated-test-unmanaged/org/example/valueentity/CounterSpec.scala, codegen/scala-gen/src/test/resources/tests/value-entity/named-new-style/generated-test-unmanaged/org/example/valueentity/CounterServiceIntegrationSpec.scala, codegen/scala-gen/src/test/resources/tests/value-entity/named-new-style/generated-test-unmanaged/org/example/valueentity/domain/CounterSpec.scala, codegen/scala-gen/src/test/resources/tests/value-entity/state-events-in-different-pacakge/generated-test-unmanaged/org/example/valueentity/CounterServiceIntegrationSpec.scala, codegen/scala-gen/src/test/resources/tests/value-entity/state-events-in-different-pacakge/generated-test-unmanaged/org/example/valueentity/domain/CounterSpec.scala, codegen/scala-gen/src/test/resources/tests/value-entity/unnamed-new-style/generated-test-unmanaged/org/example/valueentity/CounterServiceEntitySpec.scala, codegen/scala-gen/src/test/resources/tests/value-entity/unnamed-new-style/generated-test-unmanaged/org/example/valueentity/CounterServiceIntegrationSpec.scala
Fixes https://github.com/lightbend/kalix/issues/6600
Scala counterpart to #924 and #926
=> Codegen: Mark ScalaTest tests as pending

docs/src/modules/java/pages/views.adoc
Can't be merged/published until we switch db backend, since token based paging is not supported for spanner.
=> Docs for token based paging in views

docs/release-issue-template.md
To avoid ending up in the wrong branch such as https://github.com/lightbend/kalix-docs/pull/1294
=> chore: update the release checklist

project/Dependencies.scala
=> bump: Jackson 2.13.2; Databind 2.13.2.2

samples/scala-eventsourced-counter/src/main/scala/com/example/actions/CounterTopicSubscriptionAction.scala
it was calling to the java method instead of the scala one.
=> bug: it was calling the java method

docs/src/modules/java/pages/developer-tools.adoc, docs/src/modules/java/pages/quickstart-template.adoc, docs/src/modules/java/pages/quickstart/cr-value-entity-scala.adoc, samples/scala-customer-registry-quickstart/README.md, samples/scala-eventsourced-counter/README.md, samples/scala-eventsourced-customer-registry/README.md, samples/scala-eventsourced-shopping-cart/README.md, samples/scala-fibonacci-action/README.md, samples/scala-first-service/README.md, samples/scala-reliable-timers/README.md, samples/scala-replicatedentity-shopping-cart/README.md, samples/scala-valueentity-counter/README.md, samples/scala-valueentity-customer-registry/README.md, samples/scala-valueentity-shopping-cart/README.md
=> chore: modern sbt syntax in samples and docs #971

.circleci/config.yml, docs/src/modules/java/pages/developer-tools.adoc
=> chore: Some more places for modern sbt #971

codegen/java-gen/src/main/scala/kalix/codegen/java/EntityServiceSourceGenerator.scala, codegen/java-gen/src/test/resources/tests/event-sourced-entity/absolute-packages/generated-integration-unmanaged/org/example/eventsourcedentity/CounterIntegrationTest.java, codegen/java-gen/src/test/resources/tests/event-sourced-entity/domain-in-service-package/generated-integration-unmanaged/org/example/eventsourcedentity/CounterIntegrationTest.java, codegen/java-gen/src/test/resources/tests/event-sourced-entity/named-new-style-with-java-package/generated-integration-unmanaged/org/example/eventsourcedentity/CounterIntegrationTest.java, codegen/java-gen/src/test/resources/tests/event-sourced-entity/named-new-style/generated-integration-unmanaged/org/example/eventsourcedentity/CounterIntegrationTest.java, codegen/java-gen/src/test/resources/tests/event-sourced-entity/state-events-in-different-pacakge/generated-integration-unmanaged/org/example/eventsourcedentity/CounterIntegrationTest.java, codegen/java-gen/src/test/resources/tests/event-sourced-entity/unnamed-new-style/generated-integration-unmanaged/org/example/eventsourcedentity/CounterServiceEntityIntegrationTest.java, codegen/java-gen/src/test/resources/tests/replicated-entity/multimap-absolute-packages/generated-integration-unmanaged/com/example/replicated/multimap/SomeMultiMapIntegrationTest.java, codegen/java-gen/src/test/resources/tests/replicated-entity/multimap-domain-in-service-package/generated-integration-unmanaged/com/example/replicated/multimap/SomeMultiMapIntegrationTest.java, codegen/java-gen/src/test/resources/tests/replicated-entity/multimap-key-value-in-different-pacakge/generated-integration-unmanaged/com/example/replicated/multimap/SomeMultiMapIntegrationTest.java, codegen/java-gen/src/test/resources/tests/replicated-entity/multimap-named-new-style/generated-integration-unmanaged/com/example/replicated/multimap/SomeMultiMapIntegrationTest.java, codegen/java-gen/src/test/resources/tests/replicated-entity/multimap-scalar-named-new-style/generated-integration-unmanaged/com/example/replicated/multimap/SomeMultiMapIntegrationTest.java, codegen/java-gen/src/test/resources/tests/replicated-entity/multimap-unnamed-new-style/generated-integration-unmanaged/com/example/replicated/multimap/MultiMapServiceEntityIntegrationTest.java, codegen/java-gen/src/test/resources/tests/value-entity/absolute-packages/generated-integration-unmanaged/org/example/valueentity/CounterIntegrationTest.java, codegen/java-gen/src/test/resources/tests/value-entity/domain-in-service-package/generated-integration-unmanaged/org/example/valueentity/CounterIntegrationTest.java, codegen/java-gen/src/test/resources/tests/value-entity/named-new-style/generated-integration-unmanaged/org/example/valueentity/CounterIntegrationTest.java, codegen/java-gen/src/test/resources/tests/value-entity/state-events-in-different-pacakge/generated-integration-unmanaged/org/example/valueentity/CounterIntegrationTest.java, codegen/java-gen/src/test/resources/tests/value-entity/unnamed-new-style/generated-integration-unmanaged/org/example/valueentity/CounterServiceEntityIntegrationTest.java
=> fix: Add @Ignore for generated IT methods (#959)

.gitignore, docs/src/modules/java/pages/quickstart/cr-value-entity-scala.adoc
=> Fixes formatting of code block for downloading `plugins.sbt`

build.sbt, project/Dependencies.scala
Just basic build settings. 
References https://github.com/lightbend/kalix/issues/6859
=> feat: initial build structure for Spring SDK

.github/labeler.yml, sdk/scala-sdk/src/main/scala/kalix/scalasdk/action/Action.scala
Mainly looking to get the auto-labeler update here, but other commits are also useful.
=> chore: merge main into spring-sdk branch

sdk/java-sdk/src/main/java/kalix/javasdk/Kalix.java
=> chore: use Collections.empty()

docs/src/modules/java/pages/timers.adoc
=> chore: typo in timers doc

docs/src/modules/java/pages/actions-as-controller.adoc, samples/java-valueentity-shopping-cart/src/test/java/com/example/shoppingcart/ShoppingCartActionImplTest.java, samples/scala-valueentity-shopping-cart/src/test/scala/com/example/shoppingcart/ShoppingCartActionImplSpec.scala
=> docs: add testkit docs for unit testing with cross-component calls

samples/java-customer-registry-views-quickstart/src/it/java/customer/view/CustomerByNameIntegrationTest.java
I couldn't reproduce the timeout locally but I'm hopeful that by aligning the timeout with the other test, this flaky test will go away.
References #766
=> chore: increase timeout in flaky test

sdk/java-sdk/src/main/scala/kalix/javasdk/impl/DiscoveryImpl.scala, tck/scala-tck/src/main/scala/kalix/tck/model/view/ViewTckModelImpl.scala
* and proxy will report the version notification as warning instead of error
=> fix: Add severity to UserFunctionError

sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/ComponentDescriptor.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/ProtoDescriptorRenderer.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/ViewDescriptorFactory.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/reflection/KalixMethod.scala, sdk/spring-sdk/src/test/scala/kalix/springsdk/impl/ViewDescriptorFactorySpec.scala
Now works (but needs proxy fix https://github.com/lightbend/kalix-proxy/pull/1600 )
=> Spring views contd

samples/java-customer-registry-kafka-quickstart/kafka/docker-compose.yml
Fixes https://github.com/lightbend/kalix-jvm-sdk/issues/1059.
More discussion here: https://typesafe.slack.com/archives/C01FDELQMGR/p1658934207861259
=> use different kafka-image

maven-java/kalix-maven-archetype-event-sourced-entity/src/main/resources/archetype-resources/docker-compose.yml, maven-java/kalix-maven-archetype-value-entity/src/main/resources/archetype-resources/docker-compose.yml, project/Dependencies.scala, samples/java-customer-registry-kafka-quickstart/docker-compose.yml, samples/java-customer-registry-kafka-quickstart/kafka/docker-compose.yml, samples/java-customer-registry-quickstart/docker-compose.yml, samples/java-customer-registry-views-quickstart/docker-compose.yml, samples/java-eventsourced-counter/docker-compose.yml, samples/java-eventsourced-shopping-cart/docker-compose.yml, samples/java-fibonacci-action/docker-compose.yml, samples/java-first-service/docker-compose.yml, samples/java-reliable-timers/docker-compose.yml, samples/java-replicatedentity-examples/docker-compose.yml, samples/java-replicatedentity-shopping-cart/docker-compose.yml, samples/java-shopping-cart-quickstart/docker-compose.yml, samples/java-valueentity-counter/docker-compose.yml, samples/java-valueentity-customer-registry/docker-compose.yml, samples/java-valueentity-shopping-cart/docker-compose.yml, samples/scala-customer-registry-quickstart/docker-compose.yml, samples/scala-eventsourced-counter/docker-compose.yml, samples/scala-eventsourced-customer-registry/docker-compose.yml, samples/scala-eventsourced-shopping-cart/docker-compose.yml, samples/scala-fibonacci-action/docker-compose.yml, samples/scala-first-service/docker-compose.yml, samples/scala-reliable-timers/docker-compose.yml, samples/scala-replicatedentity-examples/docker-compose.yml, samples/scala-replicatedentity-shopping-cart/docker-compose.yml, samples/scala-valueentity-counter/docker-compose.yml, samples/scala-valueentity-customer-registry/docker-compose.yml, samples/scala-valueentity-shopping-cart/docker-compose.yml
References [Kalix Proxy 1.0.15](https://github.com/lightbend/kalix-proxy/issues/1605)
=> chore: bump Kalix Proxy version to 1.0.15

docs/Makefile
=> fix: creates latest-version.txt for scala sdk

build.sbt, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/KalixServer.scala
Refs #1045 
Since we've done it recently for scala vs java, might as well get it out of the way for Spring.
=> chore: report spring sdk info

sdk/spring-sdk/src/it/java/com/example/wiring/SpringSdkWiringIntegrationTest.java, sdk/spring-sdk/src/it/resources/logback.xml, sdk/spring-sdk/src/main/java/kalix/springsdk/annotations/Publish.java, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/ActionDescriptorFactory.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/ComponentDescriptorFactory.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/reflection/KalixMethod.scala, sdk/spring-sdk/src/test/java/kalix/springsdk/testmodels/Message2.java, sdk/spring-sdk/src/test/java/kalix/springsdk/testmodels/subscriptions/PubSubTestModels.java, sdk/spring-sdk/src/test/scala/kalix/springsdk/impl/ActionDescriptorFactorySpec.scala
References publishing 
https://github.com/lightbend/kalix/issues/7363
Superseding PR https://github.com/lightbend/kalix-jvm-sdk/pull/1086
References subscription 
https://github.com/lightbend/kalix/issues/7362
https://github.com/lightbend/kalix-jvm-sdk/pull/1079
=> feat(spring-sdk): pub and sub with mixing spring annotations

sdk/spring-sdk/src/it/java/com/example/wiring/SpringSdkWiringIntegrationTest.java, sdk/spring-sdk/src/it/java/com/example/wiring/valueentities/user/User.java, sdk/spring-sdk/src/it/java/com/example/wiring/valueentities/user/UserEntity.java, sdk/spring-sdk/src/it/java/com/example/wiring/views/UsersByEmail.java, sdk/spring-sdk/src/it/java/com/example/wiring/views/UsersByName.java, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/ViewDescriptorFactory.scala, sdk/spring-sdk/src/test/java/kalix/springsdk/testmodels/view/ViewTestModels.java, sdk/spring-sdk/src/test/scala/kalix/springsdk/impl/ViewDescriptorFactorySpec.scala
Tests are not yet passing. Will fixed it tomorrow.
=> feat(spring-sdk): streaming views

sdk/spring-sdk/src/main/java/kalix/springsdk/annotations/Subscribe.java, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/ActionDescriptorFactory.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/ComponentDescriptorFactory.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/reflection/KalixMethod.scala, sdk/spring-sdk/src/test/java/kalix/springsdk/testmodels/subscriptions/PubSubTestModels.java, sdk/spring-sdk/src/test/scala/kalix/springsdk/impl/ActionDescriptorFactorySpec.scala
References https://github.com/lightbend/kalix/issues/7361
=> feat: adding Subcribe to Event Sourced Entitites

.github/labeler.yml, .github/release-drafter.yml
=> chore: update release drafter to include Spring SDK

sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/ViewDescriptorFactory.scala
Small follow up of #1092 suggested by @franciscolopezsancho
=> chore: refactor on error message for views

.circleci/config.yml, samples/spring-eventsourced-counter/README.md, samples/spring-eventsourced-counter/docker-compose.yml, samples/spring-eventsourced-counter/pom.xml, samples/spring-eventsourced-counter/src/it/java/com/example/CounterIntegrationTest.java, samples/spring-eventsourced-counter/src/main/java/com/example/Counter.java, samples/spring-eventsourced-counter/src/main/java/com/example/Main.java, samples/spring-eventsourced-counter/src/main/java/com/example/ValueIncreased.java, samples/spring-eventsourced-counter/src/main/java/com/example/ValueMultiplied.java, samples/spring-eventsourced-counter/src/main/resources/logback.xml
Refs https://github.com/lightbend/kalix/issues/7473
Ended up going with the most simple sample of all with the Counter. Let me know if you think if would be worth to add a more complex one.
=> chore: adding new event-sourced sample with Spring SDK

.github/workflows/linting.yml, samples/java-reliable-timers/README.md, samples/java-valueentity-counter/README.md
=> chore: Lint docs in samples directory in CI

sdk/spring-sdk/src/main/java/kalix/springsdk/action/ReflectiveActionProvider.java, sdk/spring-sdk/src/main/java/kalix/springsdk/eventsourced/ReflectiveEventSourcedEntityProvider.java, sdk/spring-sdk/src/main/java/kalix/springsdk/valueentity/ReflectiveValueEntityProvider.java, sdk/spring-sdk/src/main/java/kalix/springsdk/view/ReflectiveViewProvider.java, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/KalixServer.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/SpringSdkMessageCodec.scala, sdk/spring-sdk/src/test/scala/kalix/springsdk/impl/SpringSdkMessageCodecSpec.scala
References https://github.com/lightbend/kalix/issues/7453
=> feat: use JsonTypeInfo to fill typeUrl

.circleci/config.yml
References https://github.com/lightbend/kalix/issues/7448, https://github.com/lightbend/kalix-javascript-sdk/pull/418
=> ci: run Fossa once per weekday

.circleci/config.yml, project/build.properties
References https://github.com/lightbend/kalix-proxy/pull/1644, https://github.com/lightbend/kalix/pull/7560
=> chore: try to improve CircleCI caching

project/Dependencies.scala, samples/spring-customer-registry-views-quickstart/src/test/java/customer/api/CustomerEntityTest.java, samples/spring-eventsourced-counter/src/test/java/com/example/CounterTest.java, samples/spring-eventsourced-customer-registry/src/test/java/customer/api/CustomerEntityTest.java, samples/spring-fibonacci-action/src/test/java/com/example/fibonacci/FibonacciActionTest.java, sdk/java-sdk-testkit/src/main/java/kalix/javasdk/testkit/ActionResult.java, sdk/java-sdk-testkit/src/main/java/kalix/javasdk/testkit/EventSourcedResult.java, sdk/java-sdk-testkit/src/main/java/kalix/javasdk/testkit/ValueEntityResult.java, sdk/java-sdk-testkit/src/main/java/kalix/javasdk/testkit/impl/EventSourcedEntityEffectsRunner.java, sdk/spring-sdk-testkit/src/main/java/kalix/springsdk/testkit/ActionTestkit.java, sdk/spring-sdk-testkit/src/main/java/kalix/springsdk/testkit/EventSourcedTestKit.java, sdk/spring-sdk-testkit/src/main/java/kalix/springsdk/testkit/ValueEntityTestKit.java, sdk/spring-sdk-testkit/src/test/java/springsdk/testmodels/actions/EchoAction.java, sdk/spring-sdk-testkit/src/test/java/springsdk/testmodels/actions/EchoActionTest.java, sdk/spring-sdk-testkit/src/test/java/springsdk/testmodels/eventsourced/CounterEventSourcedEntity.java, sdk/spring-sdk-testkit/src/test/java/springsdk/testmodels/eventsourced/CounterEventSourcedEntityTest.java, sdk/spring-sdk-testkit/src/test/java/springsdk/testmodels/eventsourced/Increased.java, sdk/spring-sdk-testkit/src/test/java/springsdk/testmodels/valueentity/CounterValueEntity.java, sdk/spring-sdk-testkit/src/test/java/springsdk/testmodels/valueentity/CounterValueEntityTest.java
References https://github.com/lightbend/kalix/issues/7439
Still need to add the javadocs, but opening it already for review to get feedback on the API.
TODOs
=> feat: add unit test kit for Spring SDK

maven-java/kalix-maven-plugin/pom.xml
Align to make Fossa a bit happier.
https://github.com/lightbend/kalix-jvm-sdk/blob/ab7243fad8fcc3ee1dce777efff69233715cf0c5/project/Dependencies.scala#L25
=> bump: logback 1.2.11 in kalix-maven-plugin

docs/src/modules/java/pages/replicated-entity-crdt.adoc
Fixes https://github.com/lightbend/kalix-docs/issues/1532
=> fix: language selection syntax

maven-java/kalix-spring-boot-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml, maven-java/kalix-spring-boot-archetype/src/main/resources/archetype-resources/pom.xml, maven-java/kalix-spring-boot-archetype/src/main/resources/archetype-resources/src/it/java/__packageInPathFormat__/IntegrationTest.java
https://github.com/lightbend/kalix/issues/7529
=> feat: add IntegrationTest template to SpringSDK archetype

sdk/spring-sdk/src/it/java/com/example/wiring/SpringSdkWiringIntegrationTest.java, sdk/spring-sdk/src/it/java/com/example/wiring/eventsourcedentities/counter/IncreaseAction.java, sdk/spring-sdk/src/it/java/com/example/wiring/eventsourcedentities/counter/ValueMultiplied.java, sdk/spring-sdk/src/it/java/com/example/wiring/views/CountersByValueSubscriptions.java, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/ActionDescriptorFactory.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/ComponentDescriptor.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/ComponentDescriptorFactory.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/ComponentMethod.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/KalixServer.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/ProtoMessageDescriptors.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/SpringSdkMessageCodec.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/ViewDescriptorFactory.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/action/ReflectiveActionRouter.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/eventsourcedentity/ReflectiveEventSourcedEntityRouter.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/reflection/KalixMethod.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/reflection/ParameterExtractor.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/valueentity/ReflectiveValueEntityRouter.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/view/ReflectiveViewRouter.scala, sdk/spring-sdk/src/test/java/kalix/springsdk/testmodels/subscriptions/PubSubTestModels.java, sdk/spring-sdk/src/test/java/kalix/springsdk/testmodels/valueentity/CounterState.java, sdk/spring-sdk/src/test/java/kalix/springsdk/testmodels/valueentity/CreateUser.java, sdk/spring-sdk/src/test/scala/kalix/springsdk/impl/ActionDescriptorFactorySpec.scala, sdk/spring-sdk/src/test/scala/kalix/springsdk/impl/reflection/ParameterExtractorsSpec.scala
References https://github.com/lightbend/kalix/issues/7512
=> feat: Allow multiple subscription to topics or EventSourced Entities' events

sdk/spring-sdk/src/main/java/kalix/springsdk/annotations/JWT.java, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/ActionDescriptorFactory.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/ComponentDescriptor.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/ComponentDescriptorFactory.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/EntityDescriptorFactory.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/ViewDescriptorFactory.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/reflection/KalixMethod.scala, sdk/spring-sdk/src/test/java/kalix/springsdk/testmodels/action/ActionsTestModels.java, sdk/spring-sdk/src/test/java/kalix/springsdk/testmodels/eventsourcedentity/EventSourcedEntitiesTestModels.java, sdk/spring-sdk/src/test/java/kalix/springsdk/testmodels/view/ViewTestModels.java, sdk/spring-sdk/src/test/scala/kalix/springsdk/impl/ActionDescriptorFactorySpec.scala, sdk/spring-sdk/src/test/scala/kalix/springsdk/impl/EventSourcedEntityDescriptorFactorySpec.scala, sdk/spring-sdk/src/test/scala/kalix/springsdk/impl/ViewDescriptorFactorySpec.scala, sdk/spring-sdk/src/test/scala/kalix/springsdk/impl/reflection/KalixMethodSpec.scala
References https://github.com/lightbend/kalix/issues/7369
=> feat: JWT annotations 

.circleci/config.yml, build.sbt, project/Dependencies.scala, project/build.properties, project/plugins.sbt, samples/scala-customer-registry-quickstart/project/build.properties, samples/scala-doc-snippets/project/build.properties, samples/scala-eventsourced-counter/project/build.properties, samples/scala-eventsourced-customer-registry/project/build.properties, samples/scala-eventsourced-shopping-cart/project/build.properties, samples/scala-fibonacci-action/project/build.properties, samples/scala-first-service/project/build.properties, samples/scala-reliable-timers/project/build.properties, samples/scala-replicatedentity-examples/project/build.properties, samples/scala-replicatedentity-shopping-cart/project/build.properties, samples/scala-valueentity-counter/project/build.properties, samples/scala-valueentity-customer-registry/project/build.properties, samples/scala-valueentity-shopping-cart/project/build.properties, sdk/java-sdk-testkit/src/main/scala/kalix/javasdk/testkit/impl/ActionResultImpl.scala, sdk/java-sdk-testkit/src/main/scala/kalix/javasdk/testkit/impl/MockRegistryImpl.scala, sdk/java-sdk-testkit/src/main/scala/kalix/javasdk/testkit/impl/TestKitActionContext.scala, sdk/java-sdk-testkit/src/main/scala/kalix/javasdk/testkit/impl/TestKitEventSourcedEntityCommandContext.scala, sdk/java-sdk-testkit/src/main/scala/kalix/javasdk/testkit/impl/TestKitEventSourcedEntityContext.scala, sdk/java-sdk-testkit/src/main/scala/kalix/javasdk/testkit/impl/TestKitValueEntityCommandContext.scala, sdk/java-sdk-testkit/src/main/scala/kalix/javasdk/testkit/impl/TestKitValueEntityContext.scala, sdk/java-sdk/src/main/scala/kalix/javasdk/KalixRunner.scala, sdk/java-sdk/src/main/scala/kalix/javasdk/impl/PassivationStrategies.scala, sdk/scala-sdk-testkit/src/main/scala/kalix/scalasdk/testkit/impl/EventSourcedResultImpl.scala
Trying out a wealth of more current versions.
Not sure if all upgrades are desired.
=> bump: brute-force versions upgrade

samples/spring-customer-registry-views-quickstart/src/main/java/customer/api/Address.java, samples/spring-customer-registry-views-quickstart/src/main/java/customer/api/Customer.java, samples/spring-customer-registry-views-quickstart/src/main/java/customer/view/CustomerByEmailView.java, samples/spring-customer-registry-views-quickstart/src/main/java/customer/view/CustomerByNameView.java, samples/spring-eventsourced-customer-registry/src/main/java/customer/api/Address.java, samples/spring-eventsourced-customer-registry/src/main/java/customer/api/Customer.java, samples/spring-eventsourced-customer-registry/src/main/java/customer/api/CustomerEntity.java, samples/spring-eventsourced-customer-registry/src/main/java/customer/view/CustomerByEmailView.java, samples/spring-eventsourced-customer-registry/src/main/java/customer/view/CustomerByNameView.java, samples/spring-eventsourced-customer-registry/src/main/java/customer/view/CustomerView.java
First commit is the main change 73ade90db9b89fe72d79600dadd2545d23d440fd
Second commit is just some clean-up of copyright headers 4924c6816de2cdd5e233f277d49c24c4f7b218e0
=> chore: use overloaded event handlers in views

styles/Lightbend/Spacing.yml
Change related to issue https://github.com/lightbend/kalix-docs/issues/1547
(See also PR https://github.com/lightbend/kalix-docs/pull/1548)
=> Lightbend style accepts 2 spaces at the end of a sentence

maven-java/kalix-spring-boot-archetype/src/main/resources/archetype-resources/src/main/java/__packageInPathFormat__/Main.java, samples/spring-customer-registry-views-quickstart/src/main/java/customer/Main.java, samples/spring-eventsourced-counter/src/main/java/com/example/Main.java, samples/spring-eventsourced-customer-registry/src/main/java/customer/Main.java, samples/spring-fibonacci-action/src/main/java/com/example/Main.java, sdk/java-sdk/src/main/java/kalix/javasdk/Kalix.java, sdk/java-sdk/src/main/scala/kalix/javasdk/KalixRunner.scala, sdk/java-sdk/src/main/scala/kalix/javasdk/impl/DiscoveryImpl.scala, sdk/spring-sdk/src/it/java/com/example/Main.java, sdk/spring-sdk/src/it/java/kalix/springsdk/KalixConfigurationTest.java, sdk/spring-sdk/src/main/java/kalix/springsdk/annotations/Acl.java, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/AclDescriptorFactory.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/CommandHandler.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/KalixServer.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/ProtoDescriptorRenderer.scala, sdk/spring-sdk/src/test/java/kalix/springsdk/testmodels/AclTestModels.java, sdk/spring-sdk/src/test/scala/kalix/springsdk/impl/AclDescriptorFactorySpec.scala
References https://github.com/lightbend/kalix/issues/7368
=> feat: ACL support for Spring SDK

.circleci/config.yml, updateSdkVersions.sh
Follow-up of #1137 
Ended-up adding another clause to update docs (= the spring-client.adoc for now at least).
Successfully tested on circleci.
(Not very pretty to have all the `sed`s there.. but it's bash after all..)
=> chore: fix automate PR for sdk bump

.circleci/config.yml, samples/spring-reliable-timers/pom.xml, samples/spring-reliable-timers/src/main/java/com/example/Main.java
Follow-up of #1166 and #1175 combined with #1153 
Mainly for consistency purposes I guess
=> chore: adding acl to spring reliable timers sample

docs/src/modules/spring/nav.adoc, docs/src/modules/spring/pages/developer-tools.adoc, docs/src/modules/spring/pages/index.adoc, docs/src/modules/spring/pages/quickstart-template.adoc, docs/src/modules/spring/partials/actions.adoc, docs/src/modules/spring/partials/eventsourced.adoc, docs/src/modules/spring/partials/pubsub-note.adoc
Refs: https://github.com/lightbend/kalix/issues/7717
=> Add placeholders for Spring docs

docs/src/modules/developing/pages/development-process-java.adoc
No issue.
Changes provides a more useful link (imho)
=> doc: Update development-process-java.adoc

sdk/java-sdk/src/main/java/kalix/javasdk/action/Action.java, sdk/java-sdk/src/main/scala/kalix/javasdk/impl/action/ActionEffectImpl.scala, sdk/java-sdk/src/main/scala/kalix/javasdk/impl/action/ActionsImpl.scala, sdk/scala-sdk/src/main/scala/kalix/scalasdk/action/Action.scala, sdk/scala-sdk/src/main/scala/kalix/scalasdk/impl/action/ActionEffectImpl.scala
References https://github.com/lightbend/kalix-jvm-sdk/issues/1169
=> feat: Reintroduce ignore/noReply effect #1169

maven-java/kalix-spring-boot-archetype/src/main/resources/archetype-resources/pom.xml, samples/spring-customer-registry-views-quickstart/pom.xml, samples/spring-eventsourced-counter/pom.xml, samples/spring-eventsourced-customer-registry/pom.xml, samples/spring-eventsourced-customer-registry/src/main/resources/logback.xml, samples/spring-fibonacci-action/pom.xml, samples/spring-reliable-timers/pom.xml
Just noticed these leftovers, inspired by https://github.com/lightbend/kalix-jvm-sdk/pull/1197
=> chore: clean-up spring samples poms

docs/Makefile
to allow loading samples to the docs on the `spring` folder
=> feat: samples available for spring docs

sdk/spring-sdk/src/it/java/com/example/wiring/SpringSdkWiringIntegrationTest.java, sdk/spring-sdk/src/it/java/com/example/wiring/eventsourcedentities/counter/IncreaseActionWithIgnore.java, sdk/spring-sdk/src/it/java/com/example/wiring/views/CountersByValueWithIgnore.java, sdk/spring-sdk/src/it/java/kalix/springsdk/KalixConfigurationTest.java, sdk/spring-sdk/src/main/java/kalix/springsdk/action/ReflectiveActionProvider.java, sdk/spring-sdk/src/main/java/kalix/springsdk/annotations/Subscribe.java, sdk/spring-sdk/src/main/java/kalix/springsdk/view/ReflectiveViewProvider.java, sdk/spring-sdk/src/main/scala/kalix/springsdk/KalixConfiguration.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/ActionDescriptorFactory.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/CommandHandler.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/ComponentDescriptor.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/ComponentDescriptorFactory.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/KalixServer.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/ViewDescriptorFactory.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/action/ReflectiveActionRouter.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/eventsourcedentity/ReflectiveEventSourcedEntityRouter.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/valueentity/ReflectiveValueEntityRouter.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/view/ReflectiveViewRouter.scala, sdk/spring-sdk/src/test/java/kalix/springsdk/testmodels/eventsourcedentity/EmployeeEmailUpdated.java, sdk/spring-sdk/src/test/java/kalix/springsdk/testmodels/eventsourcedentity/EventSourcedEntitiesTestModels.java, sdk/spring-sdk/src/test/java/kalix/springsdk/testmodels/subscriptions/PubSubTestModels.java, sdk/spring-sdk/src/test/java/kalix/springsdk/testmodels/view/ViewTestModels.java, sdk/spring-sdk/src/test/scala/kalix/springsdk/impl/ActionDescriptorFactorySpec.scala, sdk/spring-sdk/src/test/scala/kalix/springsdk/impl/EventSourcedEntityDescriptorFactorySpec.scala, sdk/spring-sdk/src/test/scala/kalix/springsdk/impl/ViewDescriptorFactorySpec.scala, sdk/spring-sdk/src/test/scala/kalix/springsdk/impl/eventsourceentity/EventSourcedHandlersExtractorSpec.scala
References https://github.com/lightbend/kalix/issues/7407
It partially the eventing in from this issue https://github.com/lightbend/kalix-jvm-sdk/issues/1169
=> feat: Event subscription with ignore option #7407

samples/java-eventsourced-customer-registry-subscriber/src/main/java/customer/view/AllCustomersViewImpl.java, samples/java-eventsourced-customer-registry-subscriber/src/main/proto/customer/view/customer_view.proto
=> docs: Missing view update method in Java s2s sample

docs/Makefile, docs/dev/src/antora.yml, docs/dev/src/modules/ROOT/partials/include.adoc
Those are some basic changes to the docs that will help us add the Spring SDK docs.
=> chore: minor improvements to accomotade spring docs

sdk/spring-sdk-testkit/src/main/java/kalix/springsdk/testkit/ActionTestkit.java
References https://github.com/lightbend/kalix/issues/7786
=> feat: adding stream capabilities to the Action test kit 7786

docs/src/modules/java/pages/access-control.adoc, maven-java/kalix-maven-archetype-event-sourced-entity/src/main/resources/archetype-resources/docker-compose.yml, maven-java/kalix-maven-archetype-value-entity/src/main/resources/archetype-resources/docker-compose.yml, maven-java/kalix-spring-boot-archetype/src/main/resources/archetype-resources/docker-compose.yml, sdk/java-sdk-testkit/src/main/java/kalix/javasdk/testkit/KalixTestKit.java, sdk/scala-sdk-testkit/src/main/scala/kalix/scalasdk/testkit/KalixTestKit.scala
References https://github.com/lightbend/kalix/issues/7783
=> fix: disable ACL in dev-mode

sdk/spring-sdk-testkit/src/main/java/kalix/springsdk/testkit/ActionTestkit.java
=> renaming action testkit method to streamedCall

sdk/spring-sdk/src/main/java/kalix/springsdk/annotations/Query.java, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/ViewDescriptorFactory.scala, sdk/spring-sdk/src/test/java/kalix/springsdk/testmodels/view/ViewTestModels.java, sdk/spring-sdk/src/test/scala/kalix/springsdk/impl/ViewDescriptorFactorySpec.scala
References https://github.com/lightbend/kalix/issues/7696
=> feat: support for stream updates in Views

docs/src/modules/spring/pages/getting-started.adoc, samples/spring-valueentity-counter/src/main/java/com/example/CounterEntity.java, sdk/spring-sdk/src/main/java/kalix/springsdk/annotations/EntityKey.java, sdk/spring-sdk/src/main/java/kalix/springsdk/annotations/GenerateEntityKey.java, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/EntityDescriptorFactory.scala, sdk/spring-sdk/src/test/java/kalix/springsdk/testmodels/eventsourcedentity/EventSourcedEntitiesTestModels.java, sdk/spring-sdk/src/test/scala/kalix/springsdk/impl/EventSourcedEntityDescriptorFactorySpec.scala
References https://github.com/lightbend/kalix/issues/7790
=> feat: adds support for entity key generator

docs/src/modules/java/pages/value-entity.adoc, docs/src/modules/spring/pages/getting-started.adoc, docs/src/modules/spring/pages/value-entity.adoc, docs/src/modules/spring/partials/testing-entity.adoc, samples/spring-valueentity-counter/src/it/java/com/example/CounterIntegrationTest.java, samples/spring-valueentity-counter/src/main/java/com/example/CounterEntity.java, samples/spring-valueentity-counter/src/test/java/com/example/CounterTest.java, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/ComponentDescriptorFactory.scala
References https://github.com/lightbend/kalix/issues/7714
=> docs(springsdk): add page for value entities docs

docs/dev/src/modules/ROOT/partials/timers-intro.adoc, docs/src/modules/java/pages/timers.adoc, docs/src/modules/spring/pages/timers.adoc, samples/java-reliable-timers/src/main/java/com/example/actions/OrderAction.java, samples/java-reliable-timers/src/main/java/com/example/domain/Order.java, samples/spring-reliable-timers/src/main/java/com/example/actions/OrderAction.java, samples/spring-reliable-timers/src/main/java/com/example/domain/OrderEntity.java
Adding docs for timers. refs https://github.com/lightbend/kalix/issues/7721
=> docs(spring-sdk): add docs for timers

docs/src/modules/java/pages/actions-publishing-subscribing.adoc, docs/src/modules/java/pages/service-to-service.adoc, samples/scala-doc-snippets/src/main/scala/com/example/Main.scala, samples/scala-doc-snippets/src/main/scala/com/example/MyTopicsActionImpl.scala, samples/scala-doc-snippets/src/test/scala/com/example/DelegatingServiceActionSpec.scala, samples/scala-doc-snippets/src/test/scala/com/example/MyTopicsActionImplSpec.scala, sdk/java-sdk/src/main/resources/reference.conf, sdk/java-sdk/src/main/scala/kalix/javasdk/impl/DiscoveryImpl.scala, sdk/java-sdk/src/test/scala/kalix/javasdk/impl/DiscoverySpec.scala
Depends on protocol change in proxy https://github.com/lightbend/kalix-proxy/pull/1692
=> feat: Pass along env to proxy for substitution

sdk/spring-sdk/src/it/java/com/example/wiring/eventsourcedentities/counter/IncreaseAction.java, sdk/spring-sdk/src/it/java/com/example/wiring/eventsourcedentities/counter/IncreaseActionWithIgnore.java, sdk/spring-sdk/src/it/java/com/example/wiring/valueentities/user/ValidateUserAction.java, sdk/spring-sdk/src/main/scala/kalix/springsdk/KalixClient.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/RestKalixClientImpl.scala
References https://github.com/lightbend/kalix/issues/7824
=> feat: KalixClient.post without body

.circleci/config.yml, docs/Makefile, docs/src/modules/java/pages/quickstart/cr-value-entity-java.adoc, docs/src/modules/spring/pages/getting-started.adoc, docs/src/modules/spring/pages/quickstart/cr-value-entity-spring.adoc, docs/src/modules/spring/partials/maven-archetype.adoc, samples/java-customer-registry-quickstart/pom.xml, samples/spring-customer-registry-quickstart/.bundleignore, samples/spring-customer-registry-quickstart/README.md, samples/spring-customer-registry-quickstart/docker-compose.yml, samples/spring-customer-registry-quickstart/pom.xml, samples/spring-customer-registry-quickstart/src/it/java/customer/api/CustomerIntegrationTest.java, samples/spring-customer-registry-quickstart/src/main/java/customer/Main.java, samples/spring-customer-registry-quickstart/src/main/java/customer/api/CustomerEntity.java, samples/spring-customer-registry-quickstart/src/main/java/customer/domain/Address.java, samples/spring-customer-registry-quickstart/src/main/java/customer/domain/Customer.java, samples/spring-customer-registry-quickstart/src/main/resources/application.properties, samples/spring-customer-registry-quickstart/src/main/resources/logback.xml, samples/spring-customer-registry-quickstart/src/test/java/customer/api/CustomerEntityTest.java
References https://github.com/lightbend/kalix/issues/7745
=> docs: quickstart page

codegen/java-gen/src/main/scala/kalix/codegen/java/ActionTestKitGenerator.scala, codegen/java-gen/src/main/scala/kalix/codegen/java/ValueEntityTestKitGenerator.scala, codegen/java-gen/src/test/resources/tests/value-entity/absolute-packages/generated-test-managed/org/example/domain/CounterTestKit.java, codegen/java-gen/src/test/resources/tests/value-entity/domain-in-service-package/generated-test-managed/org/example/valueentity/CounterTestKit.java, codegen/java-gen/src/test/resources/tests/value-entity/named-new-style/generated-test-managed/org/example/valueentity/domain/CounterTestKit.java, codegen/java-gen/src/test/resources/tests/value-entity/state-events-in-different-pacakge/generated-test-managed/org/example/valueentity/domain/CounterTestKit.java, codegen/java-gen/src/test/resources/tests/value-entity/unnamed-new-style/generated-test-managed/org/example/valueentity/CounterServiceEntityTestKit.java, codegen/scala-gen/src/main/scala/kalix/codegen/scalasdk/impl/ActionTestKitGenerator.scala, codegen/scala-gen/src/main/scala/kalix/codegen/scalasdk/impl/ValueEntityTestKitGenerator.scala, codegen/scala-gen/src/test/resources/tests/value-entity/absolute-packages/generated-test-managed/org/example/domain/CounterTestKit.scala, codegen/scala-gen/src/test/resources/tests/value-entity/domain-in-service-package/generated-test-managed/org/example/valueentity/CounterTestKit.scala, codegen/scala-gen/src/test/resources/tests/value-entity/named-new-style/generated-test-managed/org/example/valueentity/domain/CounterTestKit.scala, codegen/scala-gen/src/test/resources/tests/value-entity/state-events-in-different-pacakge/generated-test-managed/org/example/valueentity/domain/CounterTestKit.scala, codegen/scala-gen/src/test/resources/tests/value-entity/unnamed-new-style/generated-test-managed/org/example/valueentity/CounterServiceEntityTestKit.scala, sdk/spring-sdk-testkit/src/main/java/kalix/springsdk/testkit/ValueEntityTestKit.java, sdk/spring-sdk-testkit/src/test/java/springsdk/testmodels/valueentity/CounterValueEntity.java, sdk/spring-sdk-testkit/src/test/java/springsdk/testmodels/valueentity/CounterValueEntityTest.java, tck/scala-tck/src/main/scala/kalix/tck/model/valueentity/ValueEntityTckModelEntity.scala
=> fix: value entity test kit deletes support

docs/src/modules/spring/pages/failures-and-errors.adoc
References https://github.com/lightbend/kalix/issues/7730
=> docs: 7730 spring docs failures and errors

sdk/java-sdk/src/main/scala/kalix/javasdk/impl/AnySupport.scala, sdk/spring-sdk/src/it/java/com/example/wiring/SpringSdkIntegrationTest.java, sdk/spring-sdk/src/it/java/com/example/wiring/views/UserWithVersionView.java, sdk/spring-sdk/src/it/java/com/example/wiring/views/UsersByName.java, sdk/spring-sdk/src/it/resources/logback-test.xml, sdk/spring-sdk/src/main/java/kalix/springsdk/annotations/Subscribe.java, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/ActionDescriptorFactory.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/CommandHandler.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/ComponentDescriptor.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/ComponentDescriptorFactory.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/ProtoDescriptorGenerator.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/ViewDescriptorFactory.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/reflection/KalixMethod.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/view/ReflectiveViewRouter.scala, sdk/spring-sdk/src/test/java/kalix/springsdk/testmodels/view/ViewTestModels.java, sdk/spring-sdk/src/test/scala/kalix/springsdk/impl/ViewDescriptorFactorySpec.scala
References https://github.com/lightbend/kalix/issues/7773
=> feat: handle deletes in views

docs/src/modules/spring/pages/quickstart/cr-value-entity-spring.adoc
Rephrase inheritance description.
Fix CustomerEntity src path.
Fix typos.
=> docs(spring-sdk): small fixes to Quickstart

sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/action/ReflectiveActionRouter.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/eventsourcedentity/ReflectiveEventSourcedEntityRouter.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/valueentity/ReflectiveValueEntityRouter.scala
Notice that we were not always passing the metadata
=> fix: pass metadata further whenever available

codegen/core/src/main/scala/kalix/codegen/ModelBuilder.scala
=> fix: (codegen,views) missing validation when in/out params are different

sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/ComponentDescriptor.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/http/HttpEndpointMethodDefinition.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/reflection/KalixMethod.scala, sdk/spring-sdk/src/test/scala/kalix/springsdk/impl/ActionDescriptorFactorySpec.scala
=> fix: removed http option from subscription methods

sdk/spring-sdk/src/it/java/com/example/wiring/SpringSdkIntegrationTest.java, sdk/spring-sdk/src/it/java/com/example/wiring/ValueEntityIntegrationTest.java, sdk/spring-sdk/src/it/java/com/example/wiring/valueentities/user/UserEntity.java, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/valueentity/ReflectiveValueEntityRouter.scala
Fix https://github.com/lightbend/kalix/issues/8002
Similar to #1288 but now for the state in VE
=> fix(spring-sdk): avoid exception when using currentState in VE after persistence

docs/src/modules/spring/pages/index.adoc
Close https://github.com/lightbend/kalix/issues/7989
=> docs(spring-sdk): add reference to s2s in features

sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/ComponentDescriptor.scala, sdk/spring-sdk/src/test/java/kalix/springsdk/testmodels/valueentity/ValueEntitiesTestModels.java, sdk/spring-sdk/src/test/scala/kalix/springsdk/impl/ComponentDescriptorSuite.scala, sdk/spring-sdk/src/test/scala/kalix/springsdk/impl/ValueEntityDescriptorFactorySpec.scala
=> fix: using query params should not collide with path params

docs/src/modules/java/pages/views.adoc, docs/src/modules/spring/pages/views.adoc, samples/java-valueentity-customer-registry/src/main/proto/customer/view/customer_view.proto, samples/scala-valueentity-customer-registry/src/main/proto/customer/view/customer_view.proto, samples/spring-valueentity-customer-registry/src/main/java/com/example/api/CustomersResponse.java, samples/spring-valueentity-customer-registry/src/main/java/com/example/view/CustomersResponseByName.java
References https://github.com/lightbend/kalix-docs/issues/1613
=> chore: use more explicit name for colleciton result

docs/src/modules/spring/pages/development-process-spring.adoc
References https://github.com/lightbend/kalix-docs/issues/1605
=> docs: fix typo about writing views

samples/spring-eventsourced-customer-registry-subscriber/src/main/java/customer/views/CustomersByNameView.java, samples/spring-valueentity-customer-registry/src/main/java/com/example/view/CustomersResponseByName.java, samples/spring-valueentity-customer-registry/src/main/java/com/example/view/CustomersStreamByName.java
References https://github.com/lightbend/kalix-docs/issues/1614
=> chore: use multi-line string in queries

docs/src/modules/spring/pages/event-sourced-entities.adoc
References https://github.com/lightbend/kalix-docs/issues/1608
=> docs: remove 'with Spring' from title

docs/src/modules/java/pages/event-sourced-entities.adoc, docs/src/modules/java/pages/value-entity.adoc, docs/src/modules/spring/pages/event-sourced-entities.adoc, docs/src/modules/spring/pages/value-entity.adoc, samples/spring-eventsourced-shopping-cart/src/test/java/com/example/shoppingcart/domain/ShoppingCartTest.java, samples/spring-valueentity-counter/src/test/java/com/example/CounterTest.java
References https://github.com/lightbend/kalix-docs/issues/1610
=> chore: make it explicit that teskit is stateful

sdk/spring-sdk/src/it/java/com/example/wiring/SpringSdkIntegrationTest.java, sdk/spring-sdk/src/it/java/com/example/wiring/actions/echo/ActionWithPrimitives.java, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/ComponentDescriptor.scala
References https://github.com/lightbend/kalix/issues/8053
=> fix: support for java primitives in path variables

sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/eventsourcedentity/ReflectiveEventSourcedEntityRouter.scala
=> chore: removing fixme about missing metadata

docs/Makefile
References:
- https://github.com/lightbend/kalix/issues/8031
- https://github.com/lightbend/kalix/issues/7732
=> docs: adding spring API docs #7732

build.sbt, docs/src/modules/java/pages/event-sourced-entities.adoc
I'm back with https://github.com/lightbend/kalix-jvm-sdk/issues/1314
=> bug: (the second half) mixing Java and Scala docs #1314

sdk/java-sdk/src/main/java/kalix/javasdk/action/Action.java, sdk/java-sdk/src/main/scala/kalix/javasdk/impl/action/ActionEffectImpl.scala, sdk/java-sdk/src/main/scala/kalix/javasdk/impl/action/ActionsImpl.scala, sdk/java-sdk/src/test/scala/kalix/javasdk/impl/action/ActionHandlerSpec.scala, sdk/scala-sdk/src/main/scala/kalix/scalasdk/action/Action.scala, sdk/scala-sdk/src/main/scala/kalix/scalasdk/impl/action/ActionEffectImpl.scala
=> fix: Allow ignore as async effect #1318

sdk/java-sdk-testkit/src/main/java/kalix/javasdk/testkit/ActionResult.java, sdk/java-sdk-testkit/src/main/scala/kalix/javasdk/testkit/impl/ActionResultImpl.scala, sdk/scala-sdk-testkit/src/main/scala/kalix/scalasdk/testkit/ActionResult.scala, sdk/scala-sdk-testkit/src/main/scala/kalix/scalasdk/testkit/impl/ActionResultImpl.scala
=> feat: Support ignore in action result testkit API

samples/scala-replicatedentity-examples/src/test/resources/application.conf, samples/scala-replicatedentity-examples/src/test/scala/com/example/replicated/counter/SomeCounterIntegrationSpec.scala, sdk/scala-sdk/src/main/scala/kalix/scalasdk/impl/replicatedentity/ReplicatedEntityAdapters.scala, sdk/scala-sdk/src/main/scala/kalix/scalasdk/replicatedentity/ReplicatedCounterMap.scala, sdk/scala-sdk/src/main/scala/kalix/scalasdk/replicatedentity/ReplicatedMap.scala
Resolves https://github.com/lightbend/kalix-jvm-sdk/issues/1289
=> fix(scala-sdk): replicated entities CCE after entity passivation

samples/spring-valueentity-customer-registry/src/it/java/com/example/CustomerIntegrationTest.java, samples/spring-valueentity-customer-registry/src/main/java/com/example/view/CustomersResponseByCity.java, sdk/spring-sdk/src/it/java/com/example/wiring/SpringSdkIntegrationTest.java, sdk/spring-sdk/src/it/java/com/example/wiring/actions/echo/ActionWithPrimitives.java, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/ComponentDescriptor.scala
References https://github.com/lightbend/kalix-jvm-sdk/issues/1369
=> feat(spring-sdk): support multi-value query parameters

sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/Validations.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/ViewDescriptorFactory.scala, sdk/spring-sdk/src/test/java/kalix/springsdk/testmodels/view/ViewTestModels.java, sdk/spring-sdk/src/test/scala/kalix/springsdk/impl/ViewDescriptorFactorySpec.scala
=> fix: better error message for value entity subscription

sdk/java-sdk/src/main/java/kalix/javasdk/action/ActionOptions.java, sdk/java-sdk/src/main/java/kalix/javasdk/eventsourcedentity/EventSourcedEntityOptions.java, sdk/java-sdk/src/main/java/kalix/javasdk/valueentity/ValueEntityOptions.java, sdk/java-sdk/src/main/scala/kalix/javasdk/impl/eventsourcedentity/EventSourcedEntityOptionsImpl.scala, sdk/scala-sdk/src/main/scala/kalix/scalasdk/EntityOptions.scala, sdk/scala-sdk/src/main/scala/kalix/scalasdk/eventsourcedentity/EventSourcedEntityOptions.scala, sdk/scala-sdk/src/main/scala/kalix/scalasdk/valueentity/ValueEntityOptions.scala, sdk/spring-sdk/src/it/java/com/example/wiring/SpringSdkIntegrationTest.java, sdk/spring-sdk/src/it/java/com/example/wiring/actions/headers/ForwardHeadersAction.java, sdk/spring-sdk/src/it/java/com/example/wiring/eventsourcedentities/headers/ForwardHeadersESEntity.java, sdk/spring-sdk/src/it/java/com/example/wiring/valueentities/headers/ForwardHeadersValueEntity.java, sdk/spring-sdk/src/it/java/com/example/wiring/valueentities/user/ValidateUserAction.java, sdk/spring-sdk/src/main/java/kalix/springsdk/action/ReflectiveActionProvider.java, sdk/spring-sdk/src/main/java/kalix/springsdk/annotations/ForwardHeaders.java, sdk/spring-sdk/src/main/java/kalix/springsdk/common/ForwardHeadersExtractor.java, sdk/spring-sdk/src/main/java/kalix/springsdk/eventsourced/ReflectiveEventSourcedEntityProvider.java, sdk/spring-sdk/src/main/java/kalix/springsdk/valueentity/ReflectiveValueEntityProvider.java, sdk/spring-sdk/src/main/java/kalix/springsdk/view/ReflectiveMultiTableViewProvider.java, sdk/spring-sdk/src/main/java/kalix/springsdk/view/ReflectiveViewProvider.java
=> feat: forward headers option support

docs/src/modules/java/pages/views.adoc, docs/src/modules/java/partials/query-syntax-reference.adoc, docs/src/modules/spring/pages/views.adoc, sdk/java-sdk/src/main/resources/reference.conf
Closes https://github.com/lightbend/kalix-jvm-sdk/issues/1336
=> docs(spring-sdk): update supported types for views

sdk/java-sdk/src/main/java/kalix/javasdk/workflow/Workflow.java, sdk/java-sdk/src/main/scala/kalix/javasdk/impl/workflow/WorkflowImpl.scala, sdk/java-sdk/src/main/scala/kalix/javasdk/impl/workflow/WorkflowRouter.scala, sdk/java-sdk/src/test/java/kalix/javasdk/workflow/TransferWorkflow.java, sdk/java-sdk/src/test/java/kalix/javasdk/workflow/TransferWorkflowRouter.java, sdk/java-sdk/src/test/proto/workflow/transfer_workflow.proto, sdk/java-sdk/src/test/scala/kalix/javasdk/impl/workflow/WorkflowImplSpec.scala, sdk/java-sdk/src/test/scala/kalix/testkit/workflow/WorkflowMessages.scala
References https://github.com/lightbend/kalix-jvm-sdk/issues/1381
Add support for async call and waitForInput transitions
=> feat: support async calls and waitForInput

sdk/spring-sdk/src/it/java/com/example/wiring/SpringSdkIntegrationTest.java, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/ComponentDescriptor.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/ProtoDescriptorRenderer.scala, sdk/spring-sdk/src/test/java/kalix/springsdk/testmodels/action/ActionsTestModels.java, sdk/spring-sdk/src/test/scala/kalix/springsdk/impl/ActionDescriptorFactorySpec.scala, sdk/spring-sdk/src/test/scala/kalix/springsdk/impl/ComponentDescriptorSuite.scala, sdk/spring-sdk/src/test/scala/kalix/springsdk/impl/reflection/ParameterExtractorsSpec.scala
Closes https://github.com/lightbend/kalix-jvm-sdk/issues/1372
=> fix(spring-sdk)!: mark params as required according to annotation

sdk/spring-sdk/src/it/java/com/example/wiring/SpringSdkIntegrationTest.java, sdk/spring-sdk/src/it/java/com/example/wiring/workflowentities/FraudDetectionResult.java, sdk/spring-sdk/src/it/java/com/example/wiring/workflowentities/Main.java, sdk/spring-sdk/src/it/java/com/example/wiring/workflowentities/SpringWorkflowIntegrationTest.java, sdk/spring-sdk/src/it/java/com/example/wiring/workflowentities/TransferState.java, sdk/spring-sdk/src/it/java/com/example/wiring/workflowentities/TransferWorkflow.java, sdk/spring-sdk/src/it/java/com/example/wiring/workflowentities/TransferWorkflowWithFraudDetection.java, sdk/spring-sdk/src/it/java/com/example/wiring/workflowentities/WalletEntity.java
=> chore: testing async calls and wait for input in Spring SDK

docs/src/modules/spring/pages/access-control.adoc, samples/spring-doc-snippets/src/main/java/com/example/acl/MyAction.java, samples/spring-doc-snippets/src/main/java/com/example/acl/UserAction.java, sdk/spring-sdk/src/main/java/kalix/springsdk/annotations/Acl.java, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/AclDescriptorFactory.scala, sdk/spring-sdk/src/test/java/kalix/springsdk/testmodels/AclTestModels.java, sdk/spring-sdk/src/test/scala/kalix/springsdk/impl/AclDescriptorFactorySpec.scala
=> chore: using HTTP status codes for ACL denyCode #1348

sdk/java-sdk-testkit/src/main/java/kalix/javasdk/testkit/KalixTestKit.java
… for it tests
References #1047
=> feat: KALIX_TESTKIT_USE_TEST_CONTAINERS env to disable testcontainers

project/Dependencies.scala, sdk/java-sdk/src/main/java/kalix/javasdk/workflowentity/WorkflowEntity.java, sdk/java-sdk/src/main/scala/kalix/javasdk/impl/workflowentity/WorkflowEntityEffectImpl.scala, sdk/java-sdk/src/main/scala/kalix/javasdk/impl/workflowentity/WorkflowEntityImpl.scala, sdk/java-sdk/src/test/java/kalix/javasdk/workflowentity/TransferWorkflowEntity.java, sdk/java-sdk/src/test/scala/kalix/javasdk/impl/workflowentity/WorkflowEntityImplSpec.scala, sdk/spring-sdk/src/it/java/com/example/wiring/workflowentities/TransferWorkflowWithFraudDetection.java
Draft becasue depends on https://github.com/lightbend/kalix-proxy/pull/1856
=> feat: pause and no-transition

maven-java/kalix-spring-boot-archetype/src/main/resources/archetype-resources/README.md, maven-java/kalix-spring-boot-kotlin-archetype/README.md, maven-java/kalix-spring-boot-kotlin-archetype/pom.xml, maven-java/kalix-spring-boot-kotlin-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml, maven-java/kalix-spring-boot-kotlin-archetype/src/main/resources/archetype-resources/.gitignore, maven-java/kalix-spring-boot-kotlin-archetype/src/main/resources/archetype-resources/README.md, maven-java/kalix-spring-boot-kotlin-archetype/src/main/resources/archetype-resources/docker-compose.yml, maven-java/kalix-spring-boot-kotlin-archetype/src/main/resources/archetype-resources/pom.xml, maven-java/kalix-spring-boot-kotlin-archetype/src/main/resources/archetype-resources/src/it/kotlin/__packageInPathFormat__/IntegrationTest.kt, maven-java/kalix-spring-boot-kotlin-archetype/src/main/resources/archetype-resources/src/main/kotlin/__packageInPathFormat__/Main.kt, maven-java/kalix-spring-boot-kotlin-archetype/src/main/resources/archetype-resources/src/main/resources/application.properties, maven-java/kalix-spring-boot-kotlin-archetype/src/main/resources/archetype-resources/src/main/resources/logback.xml, maven-java/pom.xml
Only the archetype for now. No docs, no samples. We can experiment a bit with it and eventually produce more content.
=> feat: maven archetype for Spring SDK with Kotlin

docs/src/modules/spring/pages/index.adoc
=> doc: remove Spring SDK beta label

maven-java/kalix-spring-boot-archetype/src/main/resources/archetype-resources/pom.xml, maven-java/kalix-spring-boot-kotlin-archetype/src/main/resources/archetype-resources/pom.xml, project/Dependencies.scala, samples/spring-customer-registry-quickstart/pom.xml, samples/spring-customer-registry-views-quickstart/pom.xml, samples/spring-doc-snippets/pom.xml, samples/spring-eventsourced-counter/pom.xml, samples/spring-eventsourced-customer-registry-subscriber/pom.xml, samples/spring-eventsourced-customer-registry/pom.xml, samples/spring-eventsourced-shopping-cart/pom.xml, samples/spring-fibonacci-action/pom.xml, samples/spring-reliable-timers/pom.xml, samples/spring-valueentity-counter/pom.xml, samples/spring-valueentity-customer-registry/pom.xml, samples/spring-valueentity-shopping-cart/pom.xml, samples/spring-view-store/pom.xml
=> feat: update to spring 3

sdk/java-sdk/src/main/scala/kalix/javasdk/impl/EntityExceptions.scala, sdk/java-sdk/src/main/scala/kalix/javasdk/impl/workflowentity/WorkflowEntityImpl.scala, sdk/java-sdk/src/main/scala/kalix/javasdk/impl/workflowentity/WorkflowEntityRouter.scala, sdk/java-sdk/src/test/scala/kalix/testkit/workflowentity/WorkflowMessages.scala, sdk/spring-sdk/src/it/java/com/example/wiring/workflowentities/SpringWorkflowIntegrationTest.java, sdk/spring-sdk/src/it/java/com/example/wiring/workflowentities/TransferWorkflow.java
=> feat: improved workflow error handling is sdk

.circleci/config.yml, build.sbt
* Spring SDK requires JDK 17
* Others JDK 11
=> chore: release 11 and 17 flags

sdk/java-sdk/src/main/scala/kalix/javasdk/impl/GrpcDeferredCall.scala
JVM SDK version of the more general https://github.com/akka/akka-grpc/pull/1748
=> feat: More error details about what service when a cross call fails

docs/README.md, docs/release-issue-template.md
Reminders for my future self :)
=> chore: updating docs and broken link

project/Dependencies.scala, sdk/java-sdk/src/main/java/kalix/javasdk/workflowentity/WorkflowEntity.java, sdk/spring-sdk/src/it/java/com/example/wiring/workflowentities/TransferWorkflow.java, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/KalixServer.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/SpringSdkMessageCodec.scala, sdk/spring-sdk/src/main/scala/kalix/springsdk/impl/workflow/ReflectiveWorkflowEntityRouter.scala
References https://github.com/lightbend/kalix-proxy/issues/1882
=> fix: decode messages from proxy after workflow restart

docs/src/modules/spring/pages/access-control.adoc, maven-java/kalix-maven-archetype-event-sourced-entity/src/main/resources/archetype-resources/docker-compose.yml, maven-java/kalix-maven-archetype-value-entity/src/main/resources/archetype-resources/docker-compose.yml, maven-java/kalix-spring-boot-archetype/src/main/resources/archetype-resources/docker-compose.yml, maven-java/kalix-spring-boot-kotlin-archetype/src/main/resources/archetype-resources/docker-compose.yml
=> chore: A few missed places for proxy plain text log config

sdk/spring-sdk/src/main/scala/kalix/spring/boot/KalixReactiveWebServerFactory.scala
=> fix: KalixReactiveWebServer.start (take 2)

maven-java/kalix-spring-boot-archetype/src/main/resources/archetype-resources/pom.xml, maven-java/kalix-spring-boot-kotlin-archetype/src/main/resources/archetype-resources/pom.xml, samples/spring-customer-registry-quickstart/pom.xml, samples/spring-customer-registry-views-quickstart/pom.xml, samples/spring-doc-snippets/pom.xml, samples/spring-eventsourced-counter/pom.xml, samples/spring-eventsourced-customer-registry-subscriber/pom.xml, samples/spring-eventsourced-customer-registry/pom.xml, samples/spring-eventsourced-shopping-cart/pom.xml, samples/spring-fibonacci-action/pom.xml, samples/spring-reliable-timers/pom.xml, samples/spring-transfer-workflow/pom.xml, samples/spring-valueentity-counter/pom.xml, samples/spring-valueentity-customer-registry/pom.xml, samples/spring-valueentity-shopping-cart/pom.xml, samples/spring-view-store/pom.xml
=> fix: bind to 0.0.0.0 when running springboot:run

sdk/spring-sdk/src/main/scala/kalix/spring/impl/KalixSpringApplication.scala
This is in preparation for #1489.  
Not really needed for now but it is in any case a good measure to keep all project classes on the same loader. We never know which other tooling can be used by the users.
=> chore: load components using Main's ClassLoader

docs/src/modules/spring/pages/workflow-entities.adoc
=> chore: updating links in workflow doc

docs/src/modules/java/pages/timers.adoc, docs/src/modules/java/partials/timers-intro.adoc, docs/src/modules/spring/pages/timers.adoc, sdk/java-sdk/src/main/java/kalix/javasdk/timer/TimerScheduler.java, sdk/java-sdk/src/main/scala/kalix/javasdk/impl/timer/TimerSchedulerImpl.scala, sdk/scala-sdk/src/main/scala/kalix/scalasdk/impl/timer/TimerSchedulerImpl.scala, sdk/scala-sdk/src/main/scala/kalix/scalasdk/timer/TimerScheduler.scala
References https://github.com/lightbend/kalix-proxy/issues/1462
=> feat: Upper limit to timer retries, document backoff on failure

sdk/java-sdk-spring/src/it/java/com/example/wiring/SpringSdkIntegrationTest.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/eventsourcedentities/counter/IncreaseAction.java, sdk/java-sdk-spring/src/main/scala/kalix/spring/impl/KalixSpringApplication.scala, sdk/java-sdk/src/main/scala/kalix/javasdk/impl/action/ActionsImpl.scala, sdk/java-sdk/src/main/scala/kalix/javasdk/impl/effect/EffectSupport.scala
=> fix: support RestDeferredCall as side effects

sdk/java-sdk-spring/src/it/java/com/example/wiring/workflowentities/SpringWorkflowIntegrationTest.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/workflowentities/TransferWorkflowWithoutInputs.java, sdk/java-sdk-spring/src/main/scala/kalix/spring/impl/KalixSpringApplication.scala, sdk/java-sdk/src/main/java/kalix/javasdk/workflowentity/WorkflowEntity.java, sdk/java-sdk/src/main/scala/kalix/javasdk/impl/workflowentity/WorkflowEntityEffectImpl.scala, sdk/java-sdk/src/main/scala/kalix/javasdk/impl/workflowentity/WorkflowEntityImpl.scala, sdk/java-sdk/src/main/scala/kalix/javasdk/impl/workflowentity/WorkflowEntityRouter.scala
References https://github.com/lightbend/kalix-proxy/issues/1913
=> feat: step transition without input param

samples/java-protobuf-eventsourced-counter/docker-compose.yml, samples/java-spring-eventsourced-counter/docker-compose.yml, samples/java-spring-reliable-timers/docker-compose.yml, samples/scala-protobuf-eventsourced-counter/docker-compose.yml
FIx some samples missing the pubsub active and another small change that sneak in to main.
=> chore: fix some samples docker-compose.yml

docs/src/modules/java-protobuf/pages/access-control.adoc, docs/src/modules/java-protobuf/pages/actions-as-controller.adoc, docs/src/modules/java-protobuf/pages/actions-publishing-subscribing.adoc, docs/src/modules/java-protobuf/pages/actions.adoc, docs/src/modules/java-protobuf/pages/call-another-service.adoc, docs/src/modules/java-protobuf/pages/event-sourced-entities.adoc, docs/src/modules/java-protobuf/pages/serialization.adoc, docs/src/modules/java-protobuf/pages/service-to-service.adoc, docs/src/modules/java-protobuf/pages/side-effects.adoc, docs/src/modules/java-protobuf/pages/timers.adoc, docs/src/modules/java-protobuf/pages/value-entity.adoc, docs/src/modules/java-protobuf/pages/views.adoc, docs/src/modules/java-protobuf/pages/writing-grpc-descriptors-protobuf.adoc, docs/src/modules/java/pages/access-control.adoc, docs/src/modules/java/pages/actions-as-controller.adoc, docs/src/modules/java/pages/actions-publishing-subscribing.adoc, docs/src/modules/java/pages/actions.adoc, docs/src/modules/java/pages/event-sourced-entities.adoc, docs/src/modules/java/pages/getting-started.adoc, docs/src/modules/java/pages/serialization.adoc, docs/src/modules/java/pages/service-to-service.adoc, docs/src/modules/java/pages/side-effects.adoc, docs/src/modules/java/pages/value-entity.adoc, docs/src/modules/java/pages/views.adoc, docs/src/modules/java/pages/workflow-entities.adoc
I noticed some inconsistency on callout style when working on #1532. 
#1532 fix few. This PR tackles the rest.
=> chore: align callouts style

.circleci/config.yml, docs/Makefile, docs/src/modules/java/pages/quickstart/cr-value-entity-java.adoc, docs/src/modules/java/pages/quickstart/cr-value-entity-views-java.adoc, docs/src/modules/java/pages/quickstart/expose-service.adoc, docs/src/modules/java/pages/quickstart/sc-eventsourced-entity-java.adoc, samples/java-spring-shopping-cart-quickstart/.bundleignore, samples/java-spring-shopping-cart-quickstart/README.md, samples/java-spring-shopping-cart-quickstart/docker-compose.yml, samples/java-spring-shopping-cart-quickstart/pom.xml, samples/java-spring-shopping-cart-quickstart/src/it/java/shoppingcart/cart/IntegrationTest.java, samples/java-spring-shopping-cart-quickstart/src/main/java/shoppingcart/Main.java, samples/java-spring-shopping-cart-quickstart/src/main/java/shoppingcart/api/ShoppingCartEntity.java, samples/java-spring-shopping-cart-quickstart/src/main/java/shoppingcart/domain/ShoppingCart.java, samples/java-spring-shopping-cart-quickstart/src/main/resources/logback-dev-mode.xml, samples/java-spring-shopping-cart-quickstart/src/main/resources/logback.xml
References https://github.com/lightbend/kalix-jvm-sdk/issues/1343
=> docs: adds event sourced quickstart

samples/java-spring-customer-registry-quickstart/README.md, samples/java-spring-customer-registry-views-quickstart/README.md, samples/java-spring-eventsourced-counter/README.md, samples/java-spring-eventsourced-customer-registry/README.md, samples/java-spring-eventsourced-shopping-cart/README.md, samples/java-spring-fibonacci-action/README.md, samples/java-spring-reliable-timers/README.md, samples/java-spring-valueentity-counter/README.md, samples/java-spring-valueentity-customer-registry/README.md, samples/java-spring-valueentity-shopping-cart/README.md
Follow up of https://github.com/lightbend/kalix-jvm-sdk/pull/1535
=> chore: sample's README mention spring-boot plugin

sdk/java-sdk-spring/src/it/java/com/example/wiring/eventsourcedentities/counter/CounterEntity.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/valueentities/user/UserEntity.java, sdk/java-sdk-spring/src/main/scala/kalix/javasdk/impl/ActionDescriptorFactory.scala, sdk/java-sdk-spring/src/main/scala/kalix/javasdk/impl/ComponentDescriptorFactory.scala, sdk/java-sdk-spring/src/test/java/kalix/spring/testmodels/eventsourcedentity/EventSourcedEntitiesTestModels.java, sdk/java-sdk-spring/src/test/scala/kalix/javasdk/impl/ActionDescriptorFactorySpec.scala, sdk/java-sdk-spring/src/test/scala/kalix/javasdk/impl/ViewDescriptorFactorySpec.scala
=> fix: escaping hypen from view name based on ES entity

project/Dependencies.scala, sdk/java-sdk-protobuf-testkit/src/main/java/kalix/javasdk/testkit/KalixProxyContainer.java, sdk/java-sdk-protobuf-testkit/src/main/java/kalix/javasdk/testkit/KalixTestKit.java, sdk/java-sdk-protobuf/src/main/java/kalix/javasdk/workflowentity/WorkflowEntity.java, sdk/java-sdk-protobuf/src/main/scala/kalix/javasdk/impl/workflowentity/WorkflowEntityEffectImpl.scala, sdk/java-sdk-protobuf/src/main/scala/kalix/javasdk/impl/workflowentity/WorkflowEntityImpl.scala, sdk/java-sdk-protobuf/src/main/scala/kalix/javasdk/impl/workflowentity/WorkflowEntityRouter.scala, sdk/java-sdk-protobuf/src/test/scala/kalix/testkit/workflowentity/WorkflowMessages.scala, sdk/java-sdk-spring/src/it/java/com/example/wiring/TestkitConfig.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/workflowentities/FailingCounterEntity.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/workflowentities/FailingCounterState.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/workflowentities/SpringWorkflowIntegrationTest.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/workflowentities/TransferWorkflow.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/workflowentities/WalletEntity.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/workflowentities/WorkflowWithDefaultRecoverStrategy.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/workflowentities/WorkflowWithErrorHandling.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/workflowentities/WorkflowWithRecoverStrategy.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/workflowentities/WorkflowWithStepTimeout.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/workflowentities/WorkflowWithTimeout.java, sdk/java-sdk-spring/src/main/scala/kalix/spring/impl/KalixSpringApplication.scala
References 
- https://github.com/lightbend/kalix-proxy/issues/1948
- https://github.com/lightbend/kalix-proxy/issues/1950
- https://github.com/lightbend/kalix-proxy/issues/1949
- https://github.com/lightbend/kalix-proxy/issues/1878
- https://github.com/lightbend/kalix-proxy/issues/1975
=> feat: sdk for workflow timeout, step timeout and recover strategy

.github/workflows/labeler.yml
References 
- https://github.com/actions/labeler/releases
=> bump(ci): labeler action security updates

.github/workflows/linting.yml, styles/Vocab/Base/accept.txt
References
- https://github.com/lightbend/kalix/issues/7490
=> security(ci): lock versions in linting workflow

docs/src/modules/java-protobuf/pages/service-to-service.adoc, docs/src/modules/java/pages/service-to-service.adoc, samples/java-spring-eventsourced-customer-registry-subscriber/docker-compose.yml, samples/java-spring-eventsourced-customer-registry-subscriber/pom.xml, samples/java-spring-eventsourced-customer-registry-subscriber/src/main/java/customer/views/CustomerPublicEvent.java, samples/java-spring-eventsourced-customer-registry/src/main/java/customer/domain/CustomerEvent.java
Small fix for the s2s java sample and some docs improvement.
=> fix(samples): s2s java example and improve docs

.circleci/config.yml, .github/workflows/samples.yml
We might consider to migrate CI to GitHub over time.
=> ci: migrate samples to GitHub actions

project/Dependencies.scala, samples/java-spring-transfer-workflow-compensation/src/main/java/com/example/transfer/TransferWorkflow.java, samples/java-spring-transfer-workflow/src/main/java/com/example/transfer/TransferWorkflow.java, sdk/java-sdk-protobuf/src/main/java/kalix/javasdk/workflowentity/WorkflowEntity.java, sdk/java-sdk-protobuf/src/test/java/kalix/javasdk/workflowentity/TransferWorkflowEntity.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/workflowentities/TransferWorkflow.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/workflowentities/TransferWorkflowWithFraudDetection.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/workflowentities/TransferWorkflowWithoutInputs.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/workflowentities/WorkflowWithDefaultRecoverStrategy.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/workflowentities/WorkflowWithRecoverStrategy.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/workflowentities/WorkflowWithStepTimeout.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/workflowentities/WorkflowWithTimeout.java
=> fix: explicit input types for workflow step definition

devtools/src/main/scala/kalix/devtools/impl/KalixProxyContainer.scala
@aludwiko, found a way to remove the STDOUT
=> chore: suppress STDOUT in proxy container logs

devtools/src/main/scala/kalix/devtools/impl/KalixProxyContainer.scala, maven-java/kalix-maven-plugin/src/main/scala/kalix/RunMojo.scala
Seems to work, but needs more testing. So in draft for now. 
Btw, we must have integration tests using `mvn kalix:run`. Not yet clear how to do it though.
=> fix: mount current dir as volume under /conf

sdk/core/src/main/java/kalix/devtools/impl/DevModeSettings.java, sdk/java-sdk-protobuf/src/main/scala/kalix/javasdk/KalixRunner.scala, sdk/java-sdk-protobuf/src/main/scala/kalix/javasdk/impl/HostAndPort.scala, sdk/java-sdk-spring/src/main/scala/kalix/spring/impl/WebClientProviderHolder.scala
Follow up of #1580 
Adds support for local discovery for the Spring WebClient
=> feat: local discovery for WebClient

.github/workflows/scripted-tests.yml
=> chore(ci): correct workflow naming

.circleci/config.yml, project/build.properties, samples/java-spring-fibonacci-action/project/build.properties, samples/scala-protobuf-customer-registry-quickstart/project/build.properties, samples/scala-protobuf-doc-snippets/project/build.properties, samples/scala-protobuf-eventsourced-counter/project/build.properties, samples/scala-protobuf-eventsourced-customer-registry-subscriber/project/build.properties, samples/scala-protobuf-eventsourced-customer-registry/project/build.properties, samples/scala-protobuf-eventsourced-shopping-cart/project/build.properties, samples/scala-protobuf-fibonacci-action/project/build.properties, samples/scala-protobuf-first-service/project/build.properties, samples/scala-protobuf-reliable-timers/project/build.properties, samples/scala-protobuf-replicatedentity-examples/project/build.properties, samples/scala-protobuf-replicatedentity-shopping-cart/project/build.properties, samples/scala-protobuf-valueentity-counter/project/build.properties, samples/scala-protobuf-valueentity-customer-registry/project/build.properties, samples/scala-protobuf-valueentity-shopping-cart/project/build.properties, samples/scala-protobuf-view-store/project/build.properties, samples/scala-protobuf-web-resources/project/build.properties
https://eed3si9n.com/sbt-1.8.2
=> bump: sbt 1.8.2

samples/java-protobuf-eventsourced-customer-registry-subscriber/docker-compose.yml, samples/java-spring-eventsourced-customer-registry-subscriber/docker-compose.yml, samples/scala-protobuf-eventsourced-customer-registry-subscriber/docker-compose.yml
Reverting port changed introduced in #1608
=> fix: revert proxy port in subscriber samples

sdk/java-sdk-protobuf/src/main/scala/kalix/javasdk/impl/EntityExceptions.scala, sdk/java-sdk-protobuf/src/main/scala/kalix/javasdk/impl/action/ActionsImpl.scala, sdk/java-sdk-protobuf/src/main/scala/kalix/javasdk/impl/eventsourcedentity/EventSourcedEntitiesImpl.scala, sdk/java-sdk-protobuf/src/main/scala/kalix/javasdk/impl/eventsourcedentity/EventSourcedEntityRouter.scala, sdk/java-sdk-protobuf/src/main/scala/kalix/javasdk/impl/replicatedentity/ReplicatedEntitiesImpl.scala, sdk/java-sdk-protobuf/src/main/scala/kalix/javasdk/impl/valueentity/ValueEntitiesImpl.scala, sdk/java-sdk-protobuf/src/main/scala/kalix/javasdk/impl/workflowentity/WorkflowEntityImpl.scala, sdk/java-sdk-spring/src/it/java/com/example/wiring/EventSourcedEntityIntegrationTest.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/SpringSdkIntegrationTest.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/ValueEntityIntegrationTest.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/actions/echo/ActionWithPrimitives.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/actions/echo/BodyWithPrimitives.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/eventsourcedentities/counter/Counter.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/eventsourcedentities/counter/CounterEntity.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/eventsourcedentities/counter/CounterEvent.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/eventsourcedentities/counter/IncreaseAction.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/eventsourcedentities/counter/IncreaseActionWithIgnore.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/valueentities/user/UserEntity.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/views/CountersByValue.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/views/UserCounter.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/workflowentities/SpringWorkflowIntegrationTest.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/workflowentities/WorkflowWithTimer.java, sdk/java-sdk-spring/src/it/resources/logback-test.xml, sdk/java-sdk-spring/src/main/scala/kalix/javasdk/impl/ComponentDescriptor.scala, sdk/java-sdk-spring/src/main/scala/kalix/javasdk/impl/ProtoDescriptorRenderer.scala, sdk/java-sdk-spring/src/main/scala/kalix/javasdk/impl/reflection/KalixMethod.scala, sdk/java-sdk-spring/src/main/scala/kalix/javasdk/impl/reflection/ParameterExtractor.scala, sdk/java-sdk-spring/src/test/java/kalix/spring/testmodels/action/ActionsTestModels.java, sdk/java-sdk-spring/src/test/scala/kalix/javasdk/impl/ActionDescriptorFactorySpec.scala, sdk/java-sdk-spring/src/test/scala/kalix/javasdk/impl/ComponentDescriptorSuite.scala
References https://github.com/lightbend/kalix-proxy/issues/2003
=> fix: handling path variables and query parameters with proto default values

.github/workflows/ci.yml, devtools/src/main/scala/kalix/devtools/impl/DockerComposeUtils.scala, samples/java-protobuf-eventsourced-customer-registry-subscriber/README.md, samples/java-protobuf-eventsourced-customer-registry-subscriber/docker-compose-integration.yml, samples/java-protobuf-eventsourced-customer-registry-subscriber/docker-compose.yml, samples/java-protobuf-eventsourced-customer-registry-subscriber/pom.xml, samples/java-protobuf-eventsourced-customer-registry-subscriber/src/it/java/customer/CustomerIntegrationTest.java, samples/java-protobuf-eventsourced-customer-registry-subscriber/src/main/java/customer/Main.java, samples/java-protobuf-eventsourced-customer-registry-subscriber/src/main/java/customer/action/CustomerActionImpl.java, samples/java-protobuf-eventsourced-customer-registry-subscriber/src/main/java/customer/view/AllCustomersViewImpl.java, samples/java-protobuf-eventsourced-customer-registry-subscriber/src/main/proto/customer/api/customer_action.proto, samples/java-protobuf-eventsourced-customer-registry-subscriber/src/main/proto/customer/api/customer_api.proto, samples/java-protobuf-eventsourced-customer-registry-subscriber/src/main/proto/customer/api/publisher_api.proto, samples/java-protobuf-eventsourced-customer-registry-subscriber/src/main/proto/customer/view/customer_view.proto, samples/java-protobuf-eventsourced-customer-registry-subscriber/src/main/resources/logback-dev-mode.xml, samples/java-protobuf-eventsourced-customer-registry-subscriber/src/test/java/customer/action/CustomerActionImplTest.java, samples/java-protobuf-eventsourced-customer-registry/README.md, samples/java-protobuf-eventsourced-customer-registry/docker-compose.yml, samples/java-spring-eventsourced-customer-registry-subscriber/README.md, samples/java-spring-eventsourced-customer-registry-subscriber/docker-compose.yml, samples/java-spring-eventsourced-customer-registry-subscriber/src/it/java/customer/api/CustomerIntegrationTest.java, sdk/java-sdk-protobuf/src/main/scala/kalix/javasdk/KalixRunner.scala
Same as #1582, but covering Java Protobuf SDK
=> chore: add multi-service tests Java/Proto

.github/workflows/ci.yml, samples/scala-protobuf-eventsourced-customer-registry-subscriber/README.md, samples/scala-protobuf-eventsourced-customer-registry-subscriber/build-customer-service-image.sh, samples/scala-protobuf-eventsourced-customer-registry-subscriber/build.sbt, samples/scala-protobuf-eventsourced-customer-registry-subscriber/docker-compose-integration.yml, samples/scala-protobuf-eventsourced-customer-registry-subscriber/docker-compose.yml, samples/scala-protobuf-eventsourced-customer-registry-subscriber/src/main/proto/customer/api/customer_action.proto, samples/scala-protobuf-eventsourced-customer-registry-subscriber/src/main/proto/customer/api/customer_api.proto, samples/scala-protobuf-eventsourced-customer-registry-subscriber/src/main/proto/customer/view/customer_view.proto, samples/scala-protobuf-eventsourced-customer-registry-subscriber/src/main/scala/customer/Main.scala, samples/scala-protobuf-eventsourced-customer-registry-subscriber/src/main/scala/customer/action/CustomerActionImpl.scala, samples/scala-protobuf-eventsourced-customer-registry-subscriber/src/main/scala/customer/view/AllCustomersViewImpl.scala, samples/scala-protobuf-eventsourced-customer-registry-subscriber/src/test/scala/customer/CustomerServiceIntegrationSpec.scala, samples/scala-protobuf-eventsourced-customer-registry-subscriber/src/test/scala/customer/action/CustomerActionImplSpec.scala, samples/scala-protobuf-eventsourced-customer-registry/docker-compose.yml
Same as #1582, but covering Scala Protobuf SDK
=> chore: add multi-service tests Scala/Proto

docs/dev/antora.yml, docs/src/modules/java/pages/actions.adoc
References https://github.com/lightbend/kalix/8860
=> fix: hide todos from published docs

maven-java/kalix-maven-plugin/src/main/scala/kalix/RunAllMojo.scala, maven-java/kalix-maven-plugin/src/main/scala/kalix/RunMojo.scala, maven-java/kalix-maven-plugin/src/main/scala/kalix/RunParameters.scala
References https://github.com/lightbend/kalix-jvm-sdk/issues/1626
=> fix: supporting custom JVM args in kalix-maven-plugin

sdk/java-sdk-spring/src/main/java/kalix/javasdk/annotations/Subscribe.java, sdk/java-sdk-spring/src/main/scala/kalix/javasdk/impl/ActionDescriptorFactory.scala, sdk/java-sdk-spring/src/main/scala/kalix/javasdk/impl/ComponentDescriptorFactory.scala, sdk/java-sdk-spring/src/main/scala/kalix/javasdk/impl/Validations.scala, sdk/java-sdk-spring/src/test/java/kalix/spring/testmodels/subscriptions/PubSubTestModels.java, sdk/java-sdk-spring/src/test/scala/kalix/javasdk/impl/ActionDescriptorFactorySpec.scala, sdk/java-sdk-spring/src/test/scala/kalix/javasdk/impl/ComponentDescriptorSuite.scala, sdk/java-sdk-spring/src/test/scala/kalix/javasdk/impl/DescriptorPrinter.scala
References https://github.com/lightbend/kalix-jvm-sdk/issues/1613
=> fix: publishing to a topic from different sources

sdk/java-sdk-spring/src/main/scala/kalix/javasdk/impl/ActionDescriptorFactory.scala, sdk/java-sdk-spring/src/main/scala/kalix/javasdk/impl/ComponentDescriptorFactory.scala, sdk/java-sdk-spring/src/main/scala/kalix/javasdk/impl/Validations.scala, sdk/java-sdk-spring/src/main/scala/kalix/javasdk/impl/ViewDescriptorFactory.scala, sdk/java-sdk-spring/src/test/java/kalix/spring/testmodels/subscriptions/PubSubTestModels.java, sdk/java-sdk-spring/src/test/scala/kalix/javasdk/impl/ActionDescriptorFactorySpec.scala, sdk/java-sdk-spring/src/test/scala/kalix/javasdk/impl/ViewDescriptorFactorySpec.scala
References https://github.com/lightbend/kalix-jvm-sdk/issues/1610
=> fix: supporting value entity type level subscription

sdk/java-sdk-spring/src/main/scala/kalix/javasdk/impl/ActionDescriptorFactory.scala, sdk/java-sdk-spring/src/main/scala/kalix/javasdk/impl/ComponentDescriptorFactory.scala, sdk/java-sdk-spring/src/main/scala/kalix/javasdk/impl/Validations.scala, sdk/java-sdk-spring/src/main/scala/kalix/javasdk/impl/ViewDescriptorFactory.scala, sdk/java-sdk-spring/src/test/java/kalix/spring/testmodels/subscriptions/PubSubTestModels.java, sdk/java-sdk-spring/src/test/java/kalix/spring/testmodels/view/ViewTestModels.java, sdk/java-sdk-spring/src/test/scala/kalix/javasdk/impl/ActionDescriptorFactorySpec.scala, sdk/java-sdk-spring/src/test/scala/kalix/javasdk/impl/ViewDescriptorFactorySpec.scala
=> fix: support topic subscription for Views (code first sdk)

sbt-plugin/src/main/scala/kalix/sbt/KalixPlugin.scala
=> fix: allow passing docker-compose file as arg

docs/src/modules/java/pages/spring-boot-integration.adoc
Remove duplicated word and correct incomplete statement.
=> Remove duplicated word and correct statement.

docs/src/modules/java/pages/serialization.adoc, samples/java-spring-eventsourced-counter/src/main/java/com/example/actions/SubscribeToRawBytesAction.java, sdk/java-sdk-protobuf/src/main/scala/kalix/javasdk/impl/AnySupport.scala, sdk/java-sdk-spring/src/it/java/com/example/wiring/pubsub/DummyCustomerStore.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/pubsub/PubSubIntegrationTest.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/pubsub/PublishBytesToTopic.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/pubsub/SubscribeToBytesFromTopic.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/pubsub/SubscribeToCustomers2Topic.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/pubsub/SubscribeToCustomersTopic.java, sdk/java-sdk-spring/src/main/scala/kalix/javasdk/impl/ComponentDescriptor.scala, sdk/java-sdk-spring/src/main/scala/kalix/javasdk/impl/InvocationContext.scala, sdk/java-sdk-spring/src/main/scala/kalix/javasdk/impl/JsonMessageCodec.scala, sdk/java-sdk-spring/src/main/scala/kalix/javasdk/impl/ProtoDescriptorGenerator.scala, sdk/java-sdk-spring/src/main/scala/kalix/javasdk/impl/reflection/ParameterExtractor.scala, sdk/java-sdk-spring/src/test/java/kalix/spring/testmodels/subscriptions/PubSubTestModels.java, sdk/java-sdk-spring/src/test/scala/kalix/javasdk/impl/ActionDescriptorFactorySpec.scala
=> feat: code first sdk raw bytes pub/sub

sdk/java-sdk-spring/src/it/java/com/example/wiring/actions/headers/EchoAction.java, sdk/java-sdk-spring/src/main/scala/kalix/javasdk/impl/ProtoDescriptorGenerator.scala, sdk/java-sdk-spring/src/test/scala/kalix/javasdk/impl/ActionDescriptorFactorySpec.scala
=> fix: file description name with package name to avoid collisions

maven-java/kalix-spring-boot-archetype/src/main/resources/archetype-resources/src/it/resources/logback-test.xml, maven-java/kalix-spring-boot-kotlin-archetype/src/main/resources/archetype-resources/src/it/resources/logback-test.xml
=> chore: logs in integration tests be plain text by default

docs/src/modules/java/pages/serialization.adoc
The smallest PR you'll review today. Was afraid I would forget if I did not do it right away.
=> docs: fix content-type value for cloudevents

sdk/java-sdk-spring/src/it/java/com/example/wiring/valueentities/customer/CustomerEntity.java, sdk/java-sdk-spring/src/main/scala/kalix/spring/impl/KalixSpringApplication.scala
Notices these two minor issues when preparing the brown bag presentation
=> chore: minor fixes

samples/java-protobuf-eventsourced-customer-registry-subscriber/docker-compose-integration.yml, samples/java-spring-eventsourced-customer-registry-subscriber/docker-compose-integration.yml, samples/scala-protobuf-eventsourced-customer-registry-subscriber/docker-compose-integration.yml, sdk/java-sdk-spring/docker-compose-integration.yml, updateProxyVersions.sh
Close https://github.com/lightbend/kalix-proxy/issues/2061
=> ci: fix proxy version update script

docs/src/modules/java/pages/workflows.adoc
Refs: https://github.com/lightbend/kalix/issues/9035
=> Simplify Workflows intro paragraph

docs/src/modules/java/pages/event-sourced-entities.adoc, docs/src/modules/java/pages/value-entity.adoc
=> docs: rewording regarding public/private interfaces

sdk/java-sdk-spring/src/it/java/com/example/wiring/SpringSdkIntegrationTest.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/views/CustomerByCreationTime.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/views/UserCountersView.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/views/UsersByEmail.java, sdk/java-sdk-spring/src/main/java/kalix/javasdk/client/ActionCallBuilder.java, sdk/java-sdk-spring/src/main/java/kalix/javasdk/client/ComponentClient.java, sdk/java-sdk-spring/src/main/java/kalix/javasdk/client/EventSourcedEntityCallBuilder.java, sdk/java-sdk-spring/src/main/java/kalix/javasdk/client/ValueEntityCallBuilder.java, sdk/java-sdk-spring/src/main/java/kalix/javasdk/client/ViewCallBuilder.java, sdk/java-sdk-spring/src/main/java/kalix/javasdk/client/WorkflowCallBuilder.java, sdk/java-sdk-spring/src/main/scala/kalix/javasdk/client/ComponentCall.scala, sdk/java-sdk-spring/src/main/scala/kalix/javasdk/impl/client/ViewCallValidator.scala, sdk/java-sdk-spring/src/test/java/kalix/javasdk/client/ComponentClientTest.java, sdk/java-sdk-spring/src/test/java/kalix/spring/testmodels/view/ViewTestModels.java, sdk/java-sdk-spring/src/test/scala/kalix/javasdk/impl/ViewDescriptorFactorySpec.scala
=> fix: view unary calls support in ComponentClient

docs/src/modules/java-protobuf/pages/running-locally.adoc
=> docs: remove unnecessary -d flag in grpcurl commands

sdk/java-sdk-spring/src/it/java/com/example/wiring/actions/echo/EchoAction.java, sdk/java-sdk-spring/src/main/scala/kalix/javasdk/impl/ComponentDescriptor.scala, sdk/java-sdk-spring/src/main/scala/kalix/javasdk/impl/reflection/RestServiceIntrospector.scala, sdk/java-sdk-spring/src/test/java/kalix/spring/testmodels/action/ActionsTestModels.java, sdk/java-sdk-spring/src/test/scala/kalix/javasdk/impl/ActionDescriptorFactorySpec.scala
=> fix: using overridden path variable name

sdk/java-sdk-protobuf/src/main/scala/kalix/javasdk/impl/workflow/WorkflowImpl.scala, sdk/java-sdk-protobuf/src/main/scala/kalix/javasdk/impl/workflow/WorkflowRouter.scala, sdk/java-sdk-spring/src/it/java/com/example/wiring/workflowentities/DummyWorkflow.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/workflowentities/SpringWorkflowIntegrationTest.java
=> fix: skipping state update for finished workflow

docs/src/modules/java-protobuf/partials/timers-intro.adoc, docs/src/modules/java/pages/workflows.adoc, samples/java-spring-transfer-workflow-compensation/src/it/java/com/example/transfer/TransferWorkflowIntegrationTest.java, samples/java-spring-transfer-workflow-compensation/src/main/java/com/example/transfer/TransferState.java, samples/java-spring-transfer-workflow-compensation/src/main/java/com/example/transfer/TransferWorkflow.java, samples/java-spring-transfer-workflow-compensation/src/main/java/com/example/wallet/WalletEntity.java
=> docs: documenting workflow pause and timers

sdk/java-sdk-protobuf/src/main/scala/kalix/javasdk/impl/workflow/WorkflowImpl.scala
=> fix: using workflow finished flag from the init msg

docs/src/modules/java/nav.adoc, docs/src/modules/java/pages/actions-publishing-subscribing.adoc, docs/src/modules/java/pages/event-sourced-entities.adoc, docs/src/modules/java/pages/serialization.adoc, docs/src/modules/java/pages/views.adoc, docs/src/modules/java/pages/workflows.adoc, samples/java-spring-eventsourced-customer-registry-subscriber/README.md, samples/java-spring-eventsourced-customer-registry-subscriber/src/it/java/customer/api/CustomerIntegrationTest.java, samples/java-spring-eventsourced-customer-registry-subscriber/src/main/java/customer/actions/CustomerRegistryAction.java, samples/java-spring-eventsourced-customer-registry/src/main/java/customer/Main.java, samples/java-spring-eventsourced-customer-registry/src/main/java/customer/domain/CustomerCreatedMigration.java, samples/java-spring-eventsourced-customer-registry/src/main/java/customer/domain/CustomerEvent.java, samples/java-spring-eventsourced-customer-registry/src/test/java/customer/domain/CustomerEventSerializationTest.java, samples/java-spring-eventsourced-customer-registry/src/test/java/customer/domain/schemaevolution/AddressChangedMigration.java, samples/java-spring-eventsourced-customer-registry/src/test/java/customer/domain/schemaevolution/CustomerEvent.java, samples/java-spring-eventsourced-customer-registry/src/test/java/customer/domain/schemaevolution/NameChangedMigration.java, sdk/java-sdk-spring-testkit/src/main/java/kalix/javasdk/testkit/EventSourcedTestKit.java, styles/Vocab/Base/accept.txt
Currently without the rolling update section, but I plan to add it later.
=> docs: JSON schema evolution documentation

sdk/java-sdk-protobuf/src/test/scala/kalix/testkit/workflow/WorkflowMessages.scala, sdk/java-sdk-spring/src/it/java/com/example/wiring/SpringSdkIntegrationTest.java, sdk/java-sdk-spring/src/main/scala/kalix/javasdk/impl/JsonMessageCodec.scala, sdk/java-sdk-spring/src/main/scala/kalix/spring/impl/KalixSpringApplication.scala, sdk/java-sdk-spring/src/test/java/kalix/javasdk/workflow/Result.java, sdk/java-sdk-spring/src/test/java/kalix/javasdk/workflow/TestWorkflowSerializationDeferredCall.java, sdk/java-sdk-spring/src/test/scala/kalix/javasdk/impl/WorkflowImplSpec.scala
=> fix: improving JSON polymorphic types support in workflows

docs/src/modules/java/pages/quickstart/cr-value-entity-java.adoc, docs/src/modules/java/pages/quickstart/cr-value-entity-views-java.adoc
Close https://github.com/lightbend/kalix-jvm-sdk/issues/1784
=> docs: fix curl snippet after exposing service

project/Dependencies.scala, sdk/java-sdk-spring/src/main/java/kalix/javasdk/annotations/JWT.java, sdk/java-sdk-spring/src/main/scala/kalix/javasdk/impl/ActionDescriptorFactory.scala, sdk/java-sdk-spring/src/main/scala/kalix/javasdk/impl/ComponentDescriptorFactory.scala, sdk/java-sdk-spring/src/main/scala/kalix/javasdk/impl/EntityDescriptorFactory.scala, sdk/java-sdk-spring/src/main/scala/kalix/javasdk/impl/JwtDescriptorFactory.scala, sdk/java-sdk-spring/src/main/scala/kalix/javasdk/impl/Reflect.scala, sdk/java-sdk-spring/src/main/scala/kalix/javasdk/impl/Validations.scala, sdk/java-sdk-spring/src/main/scala/kalix/javasdk/impl/ViewDescriptorFactory.scala, sdk/java-sdk-spring/src/test/java/kalix/spring/testmodels/action/ActionsTestModels.java, sdk/java-sdk-spring/src/test/java/kalix/spring/testmodels/eventsourcedentity/EventSourcedEntitiesTestModels.java, sdk/java-sdk-spring/src/test/java/kalix/spring/testmodels/valueentity/ValueEntitiesTestModels.java, sdk/java-sdk-spring/src/test/java/kalix/spring/testmodels/view/ViewTestModels.java, sdk/java-sdk-spring/src/test/java/kalix/spring/testmodels/workflow/WorkflowTestModels.java, sdk/java-sdk-spring/src/test/scala/kalix/javasdk/impl/ActionDescriptorFactorySpec.scala, sdk/java-sdk-spring/src/test/scala/kalix/javasdk/impl/EventSourcedEntityDescriptorFactorySpec.scala, sdk/java-sdk-spring/src/test/scala/kalix/javasdk/impl/ValueEntityDescriptorFactorySpec.scala, sdk/java-sdk-spring/src/test/scala/kalix/javasdk/impl/ViewDescriptorFactorySpec.scala, sdk/java-sdk-spring/src/test/scala/kalix/javasdk/impl/WorkflowEntityDescriptorFactorySpec.scala
Still draft because depends on proxy release
Refs
- https://github.com/lightbend/kalix-proxy/pull/2107
- https://github.com/lightbend/kalix-proxy/releases/tag/v1.1.19
=> feat: add service level JWT support

maven-java/kalix-spring-boot-archetype/src/main/resources/archetype-resources/pom.xml, maven-java/kalix-spring-boot-kotlin-archetype/src/main/resources/archetype-resources/pom.xml, project/Dependencies.scala, samples/java-spring-customer-registry-quickstart/pom.xml, samples/java-spring-customer-registry-views-quickstart/pom.xml, samples/java-spring-doc-snippets/pom.xml, samples/java-spring-eventsourced-counter/pom.xml, samples/java-spring-eventsourced-customer-registry-subscriber/pom.xml, samples/java-spring-eventsourced-customer-registry/pom.xml, samples/java-spring-eventsourced-shopping-cart/pom.xml, samples/java-spring-fibonacci-action/pom.xml, samples/java-spring-reliable-timers/pom.xml, samples/java-spring-shopping-cart-quickstart/pom.xml, samples/java-spring-transfer-workflow-compensation/pom.xml, samples/java-spring-transfer-workflow/pom.xml, samples/java-spring-valueentity-counter/pom.xml, samples/java-spring-valueentity-customer-registry/pom.xml, samples/java-spring-valueentity-shopping-cart/pom.xml, samples/java-spring-view-store/pom.xml
Current versions of Spring fresh off the press.
- https://github.com/spring-projects/spring-framework/releases/tag/v6.0.13
- https://github.com/spring-projects/spring-boot/releases/tag/v3.1.4
=> bump: Spring 6.0.13 (was 6.0.9); Boot 3.1.4 (was 3.1.0)

docs/src/modules/java/pages/using-jwts.adoc, samples/java-spring-doc-snippets/src/main/java/com/example/jwt/HelloJwtAction.java, samples/java-spring-doc-snippets/src/main/java/com/example/jwt/JWTAction.java
References https://github.com/lightbend/kalix-proxy/issues/1594
Also, document multi-issuer configuration as seen here https://github.com/lightbend/kalix-docs/pull/1906
=> docs: document service level jwt

sdk/java-sdk-protobuf/src/main/scala/kalix/javasdk/impl/eventsourcedentity/EventSourcedEntitiesImpl.scala, sdk/java-sdk-protobuf/src/main/scala/kalix/javasdk/impl/telemetry/Telemetry.scala, sdk/java-sdk-protobuf/src/main/scala/kalix/javasdk/impl/valueentity/ValueEntitiesImpl.scala
References https://github.com/lightbend/kalix/issues/9381
=> feat: adding tracing for Value Entities #9381

sdk/java-sdk-protobuf/src/main/java/kalix/javasdk/action/Action.java, sdk/java-sdk-protobuf/src/main/java/kalix/javasdk/replicatedentity/ReplicatedEntity.java, sdk/java-sdk-protobuf/src/main/java/kalix/javasdk/valueentity/ValueEntity.java, sdk/java-sdk-protobuf/src/main/java/kalix/javasdk/workflow/Workflow.java, sdk/java-sdk-protobuf/src/main/scala/kalix/javasdk/impl/workflow/WorkflowEffectImpl.scala, sdk/java-sdk-spring/src/it/java/com/example/wiring/workflowentities/TransferWorkflow.java
=> fix: support HTTP status codes in workflows effect

docs/src/modules/java/pages/running-locally.adoc
=> chore: improving running locally

.github/labeler.yml
References
- https://github.com/lightbend/kalix/issues/9895
=> chore: kalix-runtime labels

docs/src/modules/java/pages/views.adoc
No issue.  Was just reading the docs...
=> Small language changes to views.adoc

sdk/java-sdk-spring/src/it/java/com/example/wiring/SpringSdkIntegrationTest.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/valueentities/user/CompoundIdCounterEntity.java, sdk/java-sdk-spring/src/main/java/kalix/javasdk/client/ActionCallBuilder.java, sdk/java-sdk-spring/src/main/java/kalix/javasdk/client/ComponentClient.java, sdk/java-sdk-spring/src/main/java/kalix/javasdk/client/EventSourcedEntityCallBuilder.java, sdk/java-sdk-spring/src/main/java/kalix/javasdk/client/ValueEntityCallBuilder.java, sdk/java-sdk-spring/src/main/java/kalix/javasdk/client/ViewCallBuilder.java, sdk/java-sdk-spring/src/main/java/kalix/javasdk/client/WorkflowCallBuilder.java, sdk/java-sdk-spring/src/main/scala/kalix/javasdk/client/ComponentCall.scala
=> fix: supporting compound key in component client

sdk/java-sdk-spring/src/it/java/com/example/wiring/SpringSdkIntegrationTest.java, sdk/java-sdk-spring/src/it/java/com/example/wiring/views/UsersByEmailAndName.java, sdk/java-sdk-spring/src/main/scala/kalix/javasdk/client/ComponentCall.scala
=> fix: calling a view with more than one parameter

docs/src/modules/java/pages/using-jwts.adoc, project/Dependencies.scala, sdk/java-sdk-spring/src/main/java/kalix/javasdk/annotations/JWT.java, sdk/java-sdk-spring/src/main/scala/kalix/javasdk/impl/JwtDescriptorFactory.scala, sdk/java-sdk-spring/src/test/java/kalix/spring/testmodels/action/ActionsTestModels.java, sdk/java-sdk-spring/src/test/java/kalix/spring/testmodels/eventsourcedentity/EventSourcedEntitiesTestModels.java, sdk/java-sdk-spring/src/test/java/kalix/spring/testmodels/valueentity/ValueEntitiesTestModels.java, sdk/java-sdk-spring/src/test/java/kalix/spring/testmodels/view/ViewTestModels.java, sdk/java-sdk-spring/src/test/java/kalix/spring/testmodels/workflow/WorkflowTestModels.java, sdk/java-sdk-spring/src/test/scala/kalix/javasdk/impl/ActionDescriptorFactorySpec.scala, sdk/java-sdk-spring/src/test/scala/kalix/javasdk/impl/EventSourcedEntityDescriptorFactorySpec.scala, sdk/java-sdk-spring/src/test/scala/kalix/javasdk/impl/ValueEntityDescriptorFactorySpec.scala, sdk/java-sdk-spring/src/test/scala/kalix/javasdk/impl/ViewDescriptorFactorySpec.scala, sdk/java-sdk-spring/src/test/scala/kalix/javasdk/impl/WorkflowEntityDescriptorFactorySpec.scala
Refs https://github.com/lightbend/kalix/issues/9443
=> feat(java-sdk): support JWT static claims

sdk/java-sdk-spring/src/main/scala/kalix/javasdk/impl/JsonMessageCodec.scala, sdk/java-sdk-spring/src/test/scala/kalix/javasdk/impl/ActionDescriptorFactorySpec.scala, sdk/java-sdk-spring/src/test/scala/kalix/javasdk/impl/JsonMessageCodecSpec.scala, sdk/java-sdk-spring/src/test/scala/kalix/javasdk/impl/eventsourceentity/EventSourcedHandlersExtractorSpec.scala
=> fix: generic typeUrls for Java primitives

docs/src/modules/java-protobuf/pages/actions.adoc, docs/src/modules/java-protobuf/partials/actions.adoc, samples/java-protobuf-doc-snippets/src/main/proto/com/example/on_startup.proto
Refs https://github.com/lightbend/kalix-jvm-sdk/issues/1858
=> docs: actions as service life-cycle hooks

docs/release-issue-template.md
We are introducing a new way to communicate Kalix updates to other channels.
=> docs: add release information for aggregation

docs/src/modules/java-protobuf/pages/event-sourced-entities.adoc, docs/src/modules/java-protobuf/pages/running-locally.adoc, docs/src/modules/java-protobuf/pages/value-entity.adoc, docs/src/modules/java/pages/event-sourced-entities.adoc, docs/src/modules/java/pages/value-entity.adoc, samples/java-protobuf-eventsourced-customer-registry-subscriber/docker-compose-integration.yml, samples/java-protobuf-eventsourced-customer-registry-subscriber/docker-compose.yml, samples/java-spring-eventsourced-customer-registry-subscriber/docker-compose-integration.yml, samples/java-spring-eventsourced-customer-registry-subscriber/docker-compose.yml
Fix https://github.com/lightbend/kalix-runtime/issues/2188
Also fix #1941
=> docs: internal and external port match when running multiple

.github/workflows/ci.yml
=> chore: silencing build download output

docs/src/modules/java-protobuf/pages/quickstart-template.adoc, docs/src/modules/java/pages/getting-started.adoc
Close https://github.com/lightbend/kalix-docs/issues/1602
=> docs: replace generated service with Kalix service

docs/src/modules/java-protobuf/pages/actions.adoc, docs/src/modules/java/pages/actions.adoc, samples/java-spring-doc-snippets/src/main/java/com/example/trigger/OnStartupAction.java, sdk/java-sdk-spring/src/main/java/kalix/javasdk/annotations/Trigger.java, sdk/java-sdk-spring/src/main/scala/kalix/javasdk/impl/ActionDescriptorFactory.scala, sdk/java-sdk-spring/src/test/java/kalix/spring/testmodels/action/ActionsTestModels.java, sdk/java-sdk-spring/src/test/scala/kalix/javasdk/impl/ActionDescriptorFactorySpec.scala
Close https://github.com/lightbend/kalix-jvm-sdk/issues/1858
Depends on https://github.com/lightbend/kalix-runtime/pull/2253
=> feat: support on startup hook for java sdk

codegen/core/src/main/scala/kalix/codegen/ModelBuilder.scala, docs/src/modules/developing/pages/development-process-proto.adoc, docs/src/modules/java-protobuf/pages/actions.adoc, docs/src/modules/java-protobuf/pages/event-sourced-entities.adoc, docs/src/modules/java-protobuf/pages/replicated-entity-crdt.adoc, docs/src/modules/java-protobuf/pages/value-entity.adoc, docs/src/modules/java-protobuf/pages/views.adoc, docs/src/modules/java-protobuf/partials/effects-action.adoc, docs/src/modules/java-protobuf/partials/effects-api.adoc, docs/src/modules/java-protobuf/partials/effects-event-sourced-entity.adoc, docs/src/modules/java-protobuf/partials/effects-replicated-entity.adoc, docs/src/modules/java-protobuf/partials/effects-value-entity.adoc, docs/src/modules/java-protobuf/partials/effects-view.adoc, docs/src/modules/java-protobuf/partials/effects-workflow.adoc, docs/src/modules/java/pages/actions.adoc, docs/src/modules/java/pages/development-process.adoc, docs/src/modules/java/pages/event-sourced-entities.adoc, docs/src/modules/java/pages/value-entity.adoc, docs/src/modules/java/pages/views.adoc, docs/src/modules/java/pages/workflows.adoc, sdk/java-sdk-protobuf/src/main/java/kalix/javasdk/action/Action.java, sdk/java-sdk-protobuf/src/main/java/kalix/javasdk/eventsourcedentity/EventSourcedEntity.java, sdk/java-sdk-protobuf/src/main/java/kalix/javasdk/replicatedentity/ReplicatedEntity.java, sdk/java-sdk-protobuf/src/main/java/kalix/javasdk/valueentity/ValueEntity.java, sdk/java-sdk-protobuf/src/main/java/kalix/javasdk/workflow/Workflow.java, sdk/scala-sdk-protobuf/src/main/scala/kalix/scalasdk/action/Action.scala, sdk/scala-sdk-protobuf/src/main/scala/kalix/scalasdk/eventsourcedentity/EventSourcedEntity.scala, sdk/scala-sdk-protobuf/src/main/scala/kalix/scalasdk/replicatedentity/ReplicatedEntity.scala, sdk/scala-sdk-protobuf/src/main/scala/kalix/scalasdk/valueentity/ValueEntity.scala
Add docs about what an Effect is.
Related to https://github.com/lightbend/kalix-docs/pull/1995
=> docs: describe what an effect is

maven-java/kalix-spring-boot-archetype/src/main/resources/archetype-resources/pom.xml, maven-java/kalix-spring-boot-kotlin-archetype/src/main/resources/archetype-resources/pom.xml, project/Dependencies.scala, samples/java-spring-choreography-saga-quickstart/pom.xml, samples/java-spring-customer-registry-quickstart/pom.xml, samples/java-spring-customer-registry-views-quickstart/pom.xml, samples/java-spring-doc-snippets/pom.xml, samples/java-spring-eventsourced-counter/pom.xml, samples/java-spring-eventsourced-customer-registry-subscriber/pom.xml, samples/java-spring-eventsourced-customer-registry/pom.xml, samples/java-spring-eventsourced-shopping-cart/pom.xml, samples/java-spring-fibonacci-action/pom.xml, samples/java-spring-reliable-timers/pom.xml, samples/java-spring-shopping-cart-quickstart/pom.xml, samples/java-spring-transfer-workflow-compensation/pom.xml, samples/java-spring-transfer-workflow/pom.xml, samples/java-spring-valueentity-counter/pom.xml, samples/java-spring-valueentity-customer-registry/pom.xml, samples/java-spring-valueentity-shopping-cart/pom.xml, samples/java-spring-view-store/pom.xml
Close https://github.com/lightbend/kalix/issues/10420
=> bump: spring to 6.1.3 and spring boot to 3.2.1

.github/workflows/sample-repo-sync.yml
I'm quite sure this will not work out this simple -- this user can't open a PR on the other organisation and repo.
=> infra: GH workflow to update kalix-io repo

.github/workflows/sample-repo-sync.yml
follow-up https://github.com/lightbend/kalix-jvm-sdk/pull/1928
=> ci: fix sync repo workflow

project/Dependencies.scala
=> bump: Logback 1.4.11 -> 1.4.14

maven-java/pom.xml
=> bump: Maven 3.6.0 -> 3.9.0

docs/src/modules/java-protobuf/pages/views.adoc, docs/src/modules/java/pages/views.adoc, sdk/java-sdk-spring/src/main/scala/kalix/javasdk/impl/Validations.scala, sdk/java-sdk-spring/src/test/java/kalix/spring/testmodels/view/ViewTestModels.java, sdk/java-sdk-spring/src/test/scala/kalix/javasdk/impl/ViewDescriptorFactorySpec.scala
Depends on support in runtime 1.1.30
References https://github.com/lightbend/kalix-runtime/pull/2275
=> feat: Allow multiple queries in code first views

docs/release-issue-template.md
=> chore: fix grafana link

samples/java-protobuf-transfer-workflow/docker-compose.yml, samples/java-spring-choreography-saga-quickstart/docker-compose.yml
Found some old runtime images lingering around.
=> chore: update runtime images

samples/java-spring-eventsourced-customer-registry-subscriber/src/it/java/customer/api/CustomersByNameViewIntegrationTest.java, samples/java-spring-eventsourced-customer-registry-subscriber/src/main/java/customer/views/CustomersByEmailView.java, sdk/java-sdk-spring/src/main/java/kalix/javasdk/annotations/Subscribe.java, sdk/java-sdk-spring/src/main/scala/kalix/javasdk/impl/ComponentDescriptorFactory.scala
waiting for the runtime release, but can be reviewed now
=> feat: (java-spring) support multiple subscriptions of the same stream

sdk/java-sdk-protobuf/src/main/scala/kalix/javasdk/impl/telemetry/Telemetry.scala
=> fix: using command name for tracing span for VE, ES entities

samples/java-spring-choreography-saga-quickstart/src/it/java/user/registry/UserCreationIntegrationTest.java, sdk/java-sdk-protobuf/src/main/java/kalix/javasdk/action/Action.java, sdk/java-sdk-protobuf/src/main/scala/kalix/javasdk/impl/telemetry/Telemetry.scala, sdk/java-sdk-protobuf/src/main/scala/kalix/javasdk/impl/timer/TimerSchedulerImpl.scala, sdk/java-sdk-protobuf/src/main/scala/kalix/javasdk/impl/workflow/WorkflowImpl.scala, sdk/scala-sdk-protobuf/src/main/scala/kalix/scalasdk/action/Action.scala, sdk/scala-sdk-protobuf/src/main/scala/kalix/scalasdk/impl/timer/TimerSchedulerImpl.scala, sdk/scala-sdk-protobuf/src/main/scala/kalix/scalasdk/impl/workflow/WorkflowAdapters.scala
=> feat: tracing support for timer calls

docs/src/modules/java-protobuf/pages/quickstart/cr-value-entity-views-java.adoc, docs/src/modules/java-protobuf/pages/views.adoc, docs/src/modules/java/pages/quickstart/cr-value-entity-views-java.adoc, docs/src/modules/java/pages/views.adoc
=> docs: changing entity_key to component_id

sdk/java-sdk-protobuf-testkit/src/main/scala/kalix/javasdk/testkit/impl/EventingTestKitImpl.scala, sdk/java-sdk-protobuf/src/main/scala/kalix/javasdk/impl/MetadataImpl.scala, sdk/java-sdk-protobuf/src/main/scala/kalix/javasdk/impl/action/ActionsImpl.scala, sdk/java-sdk-protobuf/src/main/scala/kalix/javasdk/impl/eventsourcedentity/EventSourcedEntitiesImpl.scala, sdk/java-sdk-protobuf/src/main/scala/kalix/javasdk/impl/replicatedentity/ReplicatedEntitiesImpl.scala, sdk/java-sdk-protobuf/src/main/scala/kalix/javasdk/impl/telemetry/Telemetry.scala, sdk/java-sdk-protobuf/src/main/scala/kalix/javasdk/impl/valueentity/ValueEntitiesImpl.scala, sdk/java-sdk-protobuf/src/main/scala/kalix/javasdk/impl/view/ViewsImpl.scala, sdk/java-sdk-protobuf/src/main/scala/kalix/javasdk/impl/workflow/WorkflowImpl.scala, sdk/java-sdk-protobuf/src/test/scala/kalix/javasdk/impl/MetadataImplSpec.scala, sdk/scala-sdk-protobuf/src/main/scala/kalix/scalasdk/Metadata.scala, sdk/scala-sdk-protobuf/src/main/scala/kalix/scalasdk/impl/DeferredCallAdapters.scala, sdk/scala-sdk-protobuf/src/main/scala/kalix/scalasdk/impl/InternalContext.scala, sdk/scala-sdk-protobuf/src/main/scala/kalix/scalasdk/impl/MetadataImpl.scala, sdk/scala-sdk-protobuf/src/main/scala/kalix/scalasdk/impl/action/ActionAdapters.scala
Convert events are using `ce_` prefix, we convert to `ce-`
=> fix: cloud events - convert kafka prefix

devtools/src/main/scala/kalix/devtools/impl/DockerComposeUtils.scala
=> chore: use docker compose instead of docker-compose

samples/java-protobuf-tracing/.env, samples/java-protobuf-tracing/docker-compose.yml
https://github.com/lightbend/kalix-jvm-sdk/pull/2051#discussion_r1547754766
=> chore: aligning .env and  docker-compose.yml

docs/src/modules/java/pages/using-jwts.adoc
Refs https://github.com/lightbend/kalix-runtime/issues/2381
=> docs: match at least once in JWT static claim with pattern

devtools/src/main/scala/kalix/devtools/impl/TracingPortExtractor.scala, devtools/src/test/scala/kalix/devtools/impl/TracingPortExtractorSpec.scala, sdk/scala-sdk-protobuf/src/main/scala/kalix/scalasdk/TraceContext.scala, sdk/scala-sdk-protobuf/src/main/scala/kalix/scalasdk/impl/MetadataImpl.scala, sdk/scala-sdk-protobuf/src/main/scala/kalix/scalasdk/impl/action/ActionAdapters.scala
Files from main needed new headers.
=> chore: file headers

.github/workflows/publish.yml, build.sbt, docs/release-issue-template.md, project/ProtocolProject.scala, project/PublishPlugin.scala
=> Publishing fixes (round 1)

.github/publish-maven.sh, .github/workflows/publish.yml
Configure repo.akka.io as target repo for the Maven deploy command.
=> Publishing from Maven

.github/publish-maven.sh, .github/workflows/publish.yml
Extracting values from sbt this way is hard but proven in akka-projection.
=> Publishing to Maven (Take 3)

maven-java/pom.xml
IIUC, the Cloudsmith repository doesn't support release staging.
=> Publish Maven plugin (Take 4)

.github/publish-maven.sh, .github/workflows/publish.yml
Releasing the Maven artefacts depends on the artefacts published by sbt.
=> Publish Maven plugin (Take 5)

.github/workflows/ci.yml, .github/workflows/documentation.yml, .github/workflows/fossa.yml, .github/workflows/samples-repo-sync.yml
=> bump: current GH actions versions

.github/publish-maven.sh
Turns out that the output is slightly different when using `--client`...
=> Extract sbt props in client mode

.github/workflows/ci.yml, .github/workflows/documentation.yml, .github/workflows/fossa.yml
=> bump: GH setup-action, upload/download actions

.github/workflows/update-sdk-version.yml
The last bit that is still left in CircleCI.
=> SDK version bump creation (transfer from Circle)

.github/publish-maven.sh, .github/workflows/publish.yml, maven-java/pom.xml
Debug help, comments and back to publishing to Sonatype for Maven things.
=> Publish Maven plugin (Take 6)

.github/workflows/publish.yml
Use the name we actually use in the other places.
=> Maven publishing (Take 7)

.github/determine-sdk-version.sh, .gitignore
Remove even more control chars.
References
- #2109
=> Extracting the SDK version (Take 2)

.github/determine-sdk-version.sh
=> Determine SDK version (Take 3)

.github/determine-sdk-version.sh
References
- #2111 
- #2110 
- #2109
=> Extracting the SDK version (Take 4)

.github/publish-maven.sh, maven-java/kalix-spring-boot-parent/pom.xml, maven-java/pom.xml, publishLocally.sh
=> feat: kalix-spring-parent pom

.github/patch-maven-versions.sh, .github/publish-maven.sh, .github/workflows/ci.yml, maven-java/kalix-java-protobuf-parent/pom.xml, maven-java/kalix-maven-archetype-event-sourced-entity/src/main/resources/archetype-resources/pom.xml, maven-java/kalix-maven-archetype-value-entity/src/main/resources/archetype-resources/pom.xml, maven-java/kalix-spring-boot-archetype/src/main/resources/archetype-resources/pom.xml, maven-java/kalix-spring-boot-kotlin-archetype/src/main/resources/archetype-resources/pom.xml, maven-java/kalix-spring-boot-parent/pom.xml, publishLocally.sh, updateSdkVersions.sh
Parent poms were not working because we need to explicitly enable the plugins.
=> fix: enable all parent pom plugins

docs/src/modules/java-protobuf/pages/index.adoc, project/Dependencies.scala, samples/scala-protobuf-customer-registry-quickstart/build.sbt, samples/scala-protobuf-doc-snippets/build.sbt, samples/scala-protobuf-eventsourced-counter/build.sbt, samples/scala-protobuf-eventsourced-customer-registry-subscriber/build.sbt, samples/scala-protobuf-eventsourced-customer-registry/build.sbt, samples/scala-protobuf-eventsourced-shopping-cart/build.sbt, samples/scala-protobuf-fibonacci-action/build.sbt, samples/scala-protobuf-first-service/build.sbt, samples/scala-protobuf-reliable-timers/build.sbt, samples/scala-protobuf-replicatedentity-examples/build.sbt, samples/scala-protobuf-replicatedentity-shopping-cart/build.sbt, samples/scala-protobuf-tracing/build.sbt, samples/scala-protobuf-transfer-workflow-compensation/build.sbt, samples/scala-protobuf-transfer-workflow/build.sbt, samples/scala-protobuf-validated/build.sbt, samples/scala-protobuf-valueentity-counter/build.sbt, samples/scala-protobuf-valueentity-customer-registry/build.sbt, samples/scala-protobuf-valueentity-shopping-cart/build.sbt, samples/scala-protobuf-view-store/build.sbt, samples/scala-protobuf-web-resources/build.sbt, sbt-plugin/src/sbt-test/sbt-kalix/compile-only/build.sbt, sbt-plugin/src/sbt-test/sbt-kalix/eventsourcedentity/build.sbt, sbt-plugin/src/sbt-test/sbt-kalix/no-common-pkg-root/build.sbt
=> chore: upgrade to scala 2.13.14

maven-java/kalix-maven-plugin/pom.xml
References
- https://github.com/lightbend/kalix-jvm-sdk/pull/1987
=> bump(maven plugin): logback-classic 1.4.14 (was 1.2.11)

docs/src/modules/java-protobuf/pages/writing-grpc-descriptors-protobuf.adoc
Needs to wait for runtime release
=> docs: Document nested id fields

maven-java/kalix-spring-boot-archetype/src/main/resources/archetype-resources/pom.xml
Good catch, tks @ennru 
Follow up https://github.com/lightbend/kalix-jvm-sdk/pull/2141
=> chore: remove deps also from archetypes

LICENSE, docs/release-issue-template.md
Refs https://github.com/lightbend/kalix-jvm-sdk/issues/2139
=> build: update license change date

.github/workflows/publish.yml, build.sbt
Attempt at fixing [issue](https://github.com/lightbend/kalix-jvm-sdk/actions/runs/9257023633/job/25464278539) in CI after release.
=> build: cross versions publish and avoid publishing twice

.github/determine-sdk-version.sh, .github/workflows/update-sdk-version.yml, docs/release-issue-template.md
Refs https://github.com/lightbend/kalix-jvm-sdk/issues/2139
Fix typo on auto pr version file and have it run only after publish job.
=> ci: fix auto pr and have it depend on publish

.github/workflows/samples-repo-sync.yml
References
- https://github.com/lightbend/kalix-jvm-sdk/pull/2156
=> fix: keep .env during repo sync 2

project/Dependencies.scala, sdk/java-sdk-protobuf/src/main/scala/kalix/javasdk/impl/telemetry/Telemetry.scala
CVE: https://github.com/advisories/GHSA-w33c-445m-f8w7
https://github.com/lightbend/kalix/issues/9955
=> bumping opentelemetry to avoid CVE

codegen/core/src/main/scala/kalix/codegen/ModelBuilder.scala
=> chore: Get rid of incorrect entity_type deprecation warning #2166

sdk/java-sdk-protobuf/src/main/scala/kalix/javasdk/impl/action/ActionsImpl.scala, sdk/java-sdk-protobuf/src/main/scala/kalix/javasdk/impl/eventsourcedentity/EventSourcedEntitiesImpl.scala, sdk/java-sdk-protobuf/src/main/scala/kalix/javasdk/impl/telemetry/Telemetry.scala, sdk/java-sdk-protobuf/src/main/scala/kalix/javasdk/impl/valueentity/ValueEntitiesImpl.scala, sdk/java-sdk-protobuf/src/test/scala/kalix/javasdk/impl/eventsourcedentity/TestEventSourced.scala, sdk/java-sdk-protobuf/src/test/scala/kalix/javasdk/impl/valueentity/TestValueEntity.scala, sdk/java-sdk-protobuf/src/test/scala/kalix/javasdk/impl/valueentity/ValueEntitiesImplSpec.scala, sdk/java-sdk-protobuf/src/test/scala/kalix/testkit/eventsourcedentity/EventSourcedMessages.scala, sdk/java-sdk-protobuf/src/test/scala/kalix/testkit/valueentity/ValueEntityMessages.scala, sdk/java-sdk-spring/src/test/java/kalix/javasdk/action/TestTracingAction.java, sdk/java-sdk-spring/src/test/java/kalix/javasdk/eventsourcedentity/TestEventSourcedEntity.java, sdk/java-sdk-spring/src/test/java/kalix/javasdk/valueentity/TestValueEntity.java, sdk/java-sdk-spring/src/test/scala/kalix/javasdk/impl/ActionsImplSpec.scala, sdk/java-sdk-spring/src/test/scala/kalix/javasdk/impl/EvenSourcedEntitiesImplSpec.scala, sdk/java-sdk-spring/src/test/scala/kalix/javasdk/impl/ValueEntitiesImplSpec.scala
References https://github.com/lightbend/kalix-runtime/issues/2444#issuecomment-2175215532
Looking into adding tests for it.
=> feat:  adding tracing id to UF logs

LICENSE
For release
https://github.com/lightbend/kalix-jvm-sdk/issues/2169
=> chore: updating licence

.jvmopts
https://github.com/lightbend/kalix-jvm-sdk/actions/runs/10471822019/job/29048800882?pr=2190#step:8:1897
=> fix: avoiding OOM when 'sbt test'

.github/workflows/update-sdk-version.yml
The [version](https://github.com/lightbend/kalix-jvm-sdk/pull/2191) was wrong. Fixed now.
=> Towards fixing updating sdk samples 2

.github/workflows/update-sdk-version.yml
whether is manual trigger or auto
=> use either value from the SDK

docs/src/modules/java-protobuf/pages/call-another-service.adoc, samples/java-protobuf-doc-snippets/src/main/java/com/example/DelegatingServiceAction.java, samples/scala-protobuf-doc-snippets/src/main/scala/com/example/DelegatingServiceAction.scala
https://github.com/lightbend/kalix-runtime/issues/2708
=> chore: adding docs about how to add headers to grpcClient

docs/Makefile, docs/README.md, docs/bin/bundle.sh
Add how to build docs with windows
=> Handle windows

project/Dependencies.scala, project/plugins.sbt, sbt-plugin/src/sbt-test/sbt-kalix/compile-only/project/plugins.sbt, sbt-plugin/src/sbt-test/sbt-kalix/eventsourcedentity/project/plugins.sbt, sbt-plugin/src/sbt-test/sbt-kalix/no-common-pkg-root/project/plugins.sbt, sdk/java-sdk-protobuf/src/main/java/kalix/javasdk/KalixRunnerLicenseKeySupplier.java, sdk/java-sdk-protobuf/src/main/scala/kalix/javasdk/KalixRunner.scala
=> bump: Akka 2.9.7, grpc 1.4.4

LICENSE
Refs https://github.com/lightbend/kalix-jvm-sdk/issues/2261
=> chore: update LICENSE for v1.5.6

project/Dependencies.scala
References
- https://github.com/lightbend/kalix-runtime/issues/3429
=> bump: Kalix runtime 1.2.8

LICENSE
Refs https://github.com/lightbend/kalix-jvm-sdk/issues/2274
=> chore: update license ahead of 1.5.7

maven-java/kalix-java-protobuf-parent/pom.xml, samples/scala-protobuf-customer-registry-quickstart/build.sbt, samples/scala-protobuf-doc-snippets/build.sbt, samples/scala-protobuf-eventsourced-counter/build.sbt, samples/scala-protobuf-eventsourced-customer-registry-subscriber/build.sbt, samples/scala-protobuf-eventsourced-customer-registry/build.sbt, samples/scala-protobuf-eventsourced-shopping-cart/build.sbt, samples/scala-protobuf-fibonacci-action/build.sbt, samples/scala-protobuf-first-service/build.sbt, samples/scala-protobuf-reliable-timers/build.sbt, samples/scala-protobuf-replicatedentity-examples/build.sbt, samples/scala-protobuf-replicatedentity-shopping-cart/build.sbt, samples/scala-protobuf-tracing/build.sbt, samples/scala-protobuf-transfer-workflow-compensation/build.sbt, samples/scala-protobuf-transfer-workflow/build.sbt, samples/scala-protobuf-validated/build.sbt, samples/scala-protobuf-valueentity-counter/build.sbt, samples/scala-protobuf-valueentity-customer-registry/build.sbt, samples/scala-protobuf-valueentity-shopping-cart/build.sbt, samples/scala-protobuf-view-store/build.sbt, samples/scala-protobuf-web-resources/build.sbt
Refs https://github.com/lightbend/kalix-runtime/issues/3607
=> bump: java 21 and ubuntu version to latest versions

LICENSE
References
- https://github.com/lightbend/kalix-jvm-sdk/issues/2284
=> chore: License change for 1.5.8

sdk/java-sdk-protobuf/src/main/java/kalix/javasdk/action/ActionCreationContext.java, sdk/java-sdk-protobuf/src/main/java/kalix/javasdk/workflow/WorkflowContext.java, sdk/scala-sdk-protobuf/src/main/scala/kalix/scalasdk/action/ActionCreationContext.scala, sdk/scala-sdk-protobuf/src/main/scala/kalix/scalasdk/impl/action/ActionAdapters.scala, sdk/scala-sdk-protobuf/src/main/scala/kalix/scalasdk/impl/workflow/WorkflowAdapters.scala, sdk/scala-sdk-protobuf/src/main/scala/kalix/scalasdk/workflow/WorkflowContext.scala
=> feat: Access to component gRPC clients in actions and workflows

LICENSE
References
- https://github.com/lightbend/kalix-jvm-sdk/issues/2301
=> chore: License change date for 1.5.9

sdk/java-sdk-protobuf-testkit/src/main/java/kalix/javasdk/testkit/KalixTestKit.java, sdk/scala-sdk-protobuf-testkit/src/main/scala/kalix/scalasdk/testkit/KalixTestKit.scala
Close https://github.com/lightbend/kalix-jvm-sdk/issues/2216
=> feat: allow override of max joins in integration tests

LICENSE
References 
- https://github.com/lightbend/kalix-jvm-sdk/issues/2315
=> chore: License change date for 1.5.11

maven-java/kalix-java-protobuf-parent/pom.xml, samples/scala-protobuf-customer-registry-quickstart/build.sbt, samples/scala-protobuf-doc-snippets/build.sbt, samples/scala-protobuf-eventsourced-counter/build.sbt, samples/scala-protobuf-eventsourced-customer-registry-subscriber/build.sbt, samples/scala-protobuf-eventsourced-customer-registry-subscriber/docker-compose.yml, samples/scala-protobuf-eventsourced-customer-registry/build.sbt, samples/scala-protobuf-eventsourced-shopping-cart/build.sbt, samples/scala-protobuf-fibonacci-action/build.sbt, samples/scala-protobuf-first-service/build.sbt, samples/scala-protobuf-reliable-timers/build.sbt, samples/scala-protobuf-replicatedentity-examples/build.sbt, samples/scala-protobuf-replicatedentity-shopping-cart/build.sbt, samples/scala-protobuf-tracing/build.sbt, samples/scala-protobuf-transfer-workflow-compensation/build.sbt, samples/scala-protobuf-transfer-workflow/build.sbt, samples/scala-protobuf-validated/build.sbt, samples/scala-protobuf-valueentity-counter/build.sbt, samples/scala-protobuf-valueentity-customer-registry/build.sbt, samples/scala-protobuf-valueentity-shopping-cart/build.sbt, samples/scala-protobuf-view-store/build.sbt, samples/scala-protobuf-web-resources/build.sbt
References
- https://github.com/lightbend/kalix/issues/13770
=> bump: JRE 21.0.7 as base image

.github/publish-maven.sh
=> fix: publishing server id

project/Dependencies.scala, project/plugins.sbt
* Akka grpc 2.5.5
* Akka core 2.10.9
* Akka HTTP 10.7.1
* Jackson 2.18.4
Fixes https://github.com/lightbend/kalix-runtime/issues/4107
=> bump: Several dependencies

LICENSE
References
- https://github.com/lightbend/kalix-jvm-sdk/issues/2346
=> chore: License change date for 1.5.16
